const {PARAMETER, SUBMETRIC_TYPE, PARAMETER_INITIAL_CONFIGS} = require("../constants")

const RESOLUTION = 2

const SUBMETRIC_CONFIGS = Object.values(SUBMETRIC_TYPE).map(submetricType => {
    return { [PARAMETER.SUBMETRIC_TYPE]: submetricType }
})

const PARAMETER_CONFIGS = [
    { [PARAMETER.K]: PARAMETER_INITIAL_CONFIGS[PARAMETER.K]},
    { [PARAMETER.K]: PARAMETER_INITIAL_CONFIGS[PARAMETER.K], [PARAMETER.K_IS_BASE]: true},
    { [PARAMETER.K]: PARAMETER_INITIAL_CONFIGS[PARAMETER.K], [PARAMETER.K_IS_EXPONENT]: true},
    { [PARAMETER.J]: PARAMETER_INITIAL_CONFIGS[PARAMETER.J]},
    { [PARAMETER.J]: PARAMETER_INITIAL_CONFIGS[PARAMETER.J], [PARAMETER.J_IS_BASE]: true},
    { [PARAMETER.J]: PARAMETER_INITIAL_CONFIGS[PARAMETER.J], [PARAMETER.J_IS_EXPONENT]: true},
    { [PARAMETER.A]: PARAMETER_INITIAL_CONFIGS[PARAMETER.A]},
    { [PARAMETER.A]: PARAMETER_INITIAL_CONFIGS[PARAMETER.A], [PARAMETER.A_IS_BASE]: true},
    { [PARAMETER.A]: PARAMETER_INITIAL_CONFIGS[PARAMETER.A], [PARAMETER.A_IS_EXPONENT]: true},
    { [PARAMETER.W]: PARAMETER_INITIAL_CONFIGS[PARAMETER.W]},
    { [PARAMETER.X]: PARAMETER_INITIAL_CONFIGS[PARAMETER.X]},
    { [PARAMETER.Y]: PARAMETER_INITIAL_CONFIGS[PARAMETER.Y]},
    { [PARAMETER.V]: PARAMETER_INITIAL_CONFIGS[PARAMETER.V]},
    { [PARAMETER.T]: PARAMETER_INITIAL_CONFIGS[PARAMETER.T]},
    { [PARAMETER.MODIFIED_COUNT]: PARAMETER_INITIAL_CONFIGS[PARAMETER.MODIFIED_COUNT]},
]

const SUBMETRIC_CONFIG_COMBINATIONS = []

const PARAMETER_CONFIG_COMBINATIONS = []

module.exports = {
    RESOLUTION,
    SUBMETRIC_CONFIGS,
    PARAMETER_CONFIGS,
    SUBMETRIC_CONFIG_COMBINATIONS,
    PARAMETER_CONFIG_COMBINATIONS,
}
