import { Cents, Id, NEWLINE } from "../../../../../../../src/general"
import { JiNotationBound } from "../../../../../../../src/sagittal/notations/ji"
import { JiNotationBoundAnalysis } from "../../../../../../../src/scripts/jiNotationBound/bound"
import { EventType } from "../../../../../../../src/scripts/jiNotationBound/histories"
import { formatJiNotationBound } from "../../../../../../../src/scripts/jiNotationBound/io"
import { RANKS } from "../../../../../../../src/scripts/jiNotationBound/ranks"
import {
    jiNotationBoundAnalysisFixture,
    jiNotationBoundFixture,
} from "../../../../../../helpers/src/scripts/jiNotationBound/fixtures"

describe("formatJiNotationBound", (): void => {
    it("returns a string which is a multi-line, properly indented rendition of the JI notation bound analysis, as well as identifying information for the JI notation bound", (): void => {
        const jiNotationBound = {
            ...jiNotationBoundFixture,
            cents: 5.447635 as Cents,
            id: 10 as Id<JiNotationBound>,
        }
        const jiNotationBoundAnalysis: JiNotationBoundAnalysis = {
            ...jiNotationBoundAnalysisFixture,
            bestRank: RANKS[ EventType.SIZE_CATEGORY_BOUND ],
        }

        const actual = formatJiNotationBound(jiNotationBoundAnalysis, { jiNotationBound })

        const expected = [
            `{`,
            `    "extremeLevelLesserBoundedSymbolClass": ",,|(",`,
            `    "extremeLevelGreaterBoundedSymbolClass": ",|(",`,
            `    "cents": 5.447635,`,
            `    "boundedSymbolClassAnalyses": {`,
            `        "id": 10,`,
            `        "extreme": [`,
            `            {`,
            `                "id": 10,`,
            `                "distance": 0.20389718131741752,`,
            `                "inaDistance": 0.417891900562867,`,
            `                "elements": [`,
            `                    ",,|",`,
            `                    "|("`,
            `                ],`,
            `                "smallestSymbolSubset": "olympian",`,
            `                "minaName": "10",`,
            `                "ascii": ",,|(",`,
            `                "unicode": "",`,
            `                "introducingJiNotationLevel": "extreme",`,
            `                "primaryCommaAnalysis": {`,
            `                    "id": 10,`,
            `                    "monzo": [`,
            `                        5,`,
            `                        -3,`,
            `                        0,`,
            `                        0,`,
            `                        1,`,
            `                        -1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        352,`,
            `                        351`,
            `                    ],`,
            `                    "cents": 4.925277999283972,`,
            `                    "twoThreeFreeClassAnalysis": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            1`,
            `                        ],`,
            `                        "twoThreeFreePrimeLimit": 13,`,
            `                        "twoThreeFreeSopfr": 24,`,
            `                        "twoThreeFreeCopfr": 2,`,
            `                        "n2d3p9": 34.425925925925924`,
            `                    },`,
            `                    "apotomeSlope": -3.3032673101806025,`,
            `                    "name": "11/13k"`,
            `                }`,
            `            },`,
            `            {`,
            `                "id": 11,`,
            `                "distance": 0.3184601112166945,`,
            `                "inaDistance": 0.6526912254006633,`,
            `                "elements": [`,
            `                    ",|",`,
            `                    "|("`,
            `                ],`,
            `                "smallestSymbolSubset": "olympian",`,
            `                "minaName": "11",`,
            `                "ascii": ",|(",`,
            `                "unicode": "",`,
            `                "introducingJiNotationLevel": "extreme",`,
            `                "primaryCommaAnalysis": {`,
            `                    "id": 11,`,
            `                    "monzo": [`,
            `                        -11,`,
            `                        6,`,
            `                        0,`,
            `                        0,`,
            `                        -1,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        22599,`,
            `                        22528`,
            `                    ],`,
            `                    "cents": 5.447635291818084,`,
            `                    "twoThreeFreeClassAnalysis": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            1`,
            `                        ],`,
            `                        "twoThreeFreePrimeLimit": 31,`,
            `                        "twoThreeFreeSopfr": 42,`,
            `                        "twoThreeFreeCopfr": 2,`,
            `                        "n2d3p9": 195.75925925925924`,
            `                    },`,
            `                    "apotomeSlope": 5.664569248266845,`,
            `                    "name": "31/11k"`,
            `                }`,
            `            }`,
            `        ],`,
            `        "insane": [`,
            `            {`,
            `                "id": 10,`,
            `                "distance": 0.20389718131741752,`,
            `                "inaDistance": 1.4509637234135597,`,
            `                "elements": [`,
            `                    ",,|",`,
            `                    "|("`,
            `                ],`,
            `                "smallestSymbolSubset": "olympian",`,
            `                "minaName": "10",`,
            `                "ascii": ",,|(",`,
            `                "unicode": "",`,
            `                "introducingJiNotationLevel": "extreme",`,
            `                "primaryCommaAnalysis": {`,
            `                    "id": 10,`,
            `                    "monzo": [`,
            `                        5,`,
            `                        -3,`,
            `                        0,`,
            `                        0,`,
            `                        1,`,
            `                        -1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        352,`,
            `                        351`,
            `                    ],`,
            `                    "cents": 4.925277999283972,`,
            `                    "twoThreeFreeClassAnalysis": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            1`,
            `                        ],`,
            `                        "twoThreeFreePrimeLimit": 13,`,
            `                        "twoThreeFreeSopfr": 24,`,
            `                        "twoThreeFreeCopfr": 2,`,
            `                        "n2d3p9": 34.425925925925924`,
            `                    },`,
            `                    "apotomeSlope": -3.3032673101806025,`,
            `                    "name": "11/13k"`,
            `                }`,
            `            },`,
            `            {`,
            `                "id": 11,`,
            `                "distance": 0.3184601112166945,`,
            `                "inaDistance": 2.2662111645885687,`,
            `                "elements": [`,
            `                    ",|",`,
            `                    "|("`,
            `                ],`,
            `                "smallestSymbolSubset": "olympian",`,
            `                "minaName": "11",`,
            `                "ascii": ",|(",`,
            `                "unicode": "",`,
            `                "introducingJiNotationLevel": "extreme",`,
            `                "primaryCommaAnalysis": {`,
            `                    "id": 11,`,
            `                    "monzo": [`,
            `                        -11,`,
            `                        6,`,
            `                        0,`,
            `                        0,`,
            `                        -1,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        22599,`,
            `                        22528`,
            `                    ],`,
            `                    "cents": 5.447635291818084,`,
            `                    "twoThreeFreeClassAnalysis": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            1`,
            `                        ],`,
            `                        "twoThreeFreePrimeLimit": 31,`,
            `                        "twoThreeFreeSopfr": 42,`,
            `                        "twoThreeFreeCopfr": 2,`,
            `                        "n2d3p9": 195.75925925925924`,
            `                    },`,
            `                    "apotomeSlope": 5.664569248266845,`,
            `                    "name": "31/11k"`,
            `                }`,
            `            }`,
            `        ]`,
            `    },`,
            `    "lesserBoundedMinaName": "10",`,
            `    "greaterBoundedMinaName": "11"`,
            `}`,
            `{`,
            `    "bestPossibleHistory": {`,
            `        "eventAnalyses": [],`,
            `        "cents": 0,`,
            `        "rank": 0,`,
            `        "score": 0,`,
            `        "totalDistance": 0,`,
            `        "exact": false,`,
            `        "totalInaDistance": 0,`,
            `        "possible": false,`,
            `        "tinaError": 0,`,
            `        "initialPositionTinaDistance": 0`,
            `    },`,
            `    "bestRank": 3,`,
            `    "initialPosition": 0,`,
            `    "initialPositionTinaDistance": 0,`,
            `    "bestPossibleHistoryTotalDistance": 0,`,
            `    "bestPossibleHistoryTotalInaDistance": 0,`,
            `    "historyConsolidation": {},`,
            `    "possibleHistoryCount": 0`,
            `}`,
        ]

        expect(actual.split(NEWLINE)).toEqual(expected)
    })
})
