export { computeRationalDecimalCopfr } from "./copfr"
export { computeRationalDecimalGpf } from "./gpf"
export { isRationalDecimal, isIntegerDecimal } from "./typeGuards"
export { isSmoothIntegerDecimal, computeRationalDecimalSmoothness, computeIntegerDecimalSmoothness } from "./smoothness"
export { computeRoughIntegerDecimal, isRoughIntegerDecimal } from "./roughness"
export { ceil, floor, integerDivide } from "./typedOperations"
