import { SIZE_CATEGORY_BOUNDS } from "./sizeCategoryBounds"

const MAX_SIZE_CATEGORY_BOUND = SIZE_CATEGORY_BOUNDS[ SIZE_CATEGORY_BOUNDS.length - 1 ].cents   // 227.370012115

export {
    MAX_SIZE_CATEGORY_BOUND,
}
