// tslint:disable max-line-length

import {Combination} from "../../../../src/general/math"
import {Parameter} from "../../../../src/scripts/types"
import {computeUsefulnessParameterSets} from "../../../../src/scripts/usefulnessMetricLfc/parameters"
import {UsefulnessParameterId} from "../../../../src/scripts/usefulnessMetricLfc/types"

describe("computeUsefulnessParameterSets", (): void => {
    it("for each parameter ID, includes its range of possible values in the set", (): void => {
        const usefulnessParameterIds = [UsefulnessParameterId.SE, UsefulnessParameterId.TE]

        const actual = computeUsefulnessParameterSets(usefulnessParameterIds)

        const expected = [
            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0010 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0012 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0014 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0016 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0018 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0020 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0022 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0024 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0026 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0028 as Parameter},

            {[UsefulnessParameterId.SE]: 0.0010 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0012 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0014 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0016 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0018 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0020 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0022 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0024 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0026 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0028 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
            {[UsefulnessParameterId.SE]: 0.0030 as Parameter, [UsefulnessParameterId.TE]: 0.0030 as Parameter},
        ] as Combination<Partial<Record<UsefulnessParameterId, Parameter>>>

        expect(actual).toBeArrayWithDeepCloseContents(expected)
    })
})
