import {
    ARC_LEFT,
    ARC_RIGHT,
    BARB_LEFT,
    BARB_RIGHT,
    BOATHOOK_LEFT,
    BOATHOOK_RIGHT,
    SCROLL_LEFT,
    SCROLL_RIGHT,
} from "./elements"
import { Core } from "./types"

const LEFT_SCROLL = [SCROLL_LEFT] as Core
const RIGHT_SCROLL = [SCROLL_RIGHT] as Core
const LEFT_BOATHOOK = [BOATHOOK_LEFT] as Core
const DOUBLE_SCROLL = [...LEFT_SCROLL, ...RIGHT_SCROLL] as Core
const LEFT_SCROLL_AND_BOATHOOK = [...LEFT_SCROLL, ...LEFT_BOATHOOK] as Core
const LEFT_BOATHOOK_RIGHT_SCROLL = [...LEFT_BOATHOOK, ...RIGHT_SCROLL] as Core
const RIGHT_BOATHOOK = [BOATHOOK_RIGHT] as Core
const DOUBLE_LEFT_BOATHOOK = [...LEFT_BOATHOOK, ...LEFT_BOATHOOK] as Core
const LEFT_SCROLL_RIGHT_BOATHOOK = [...LEFT_SCROLL, ...RIGHT_BOATHOOK] as Core
const LEFT_BARB = [BARB_LEFT] as Core
const LEFT_SCROLL_AND_BARB = [...LEFT_SCROLL, ...LEFT_BARB] as Core
const RIGHT_ARC = [ARC_RIGHT] as Core
const LEFT_SCROLL_RIGHT_ARC = [...LEFT_SCROLL, ...RIGHT_ARC] as Core
const RIGHT_BARB = [BARB_RIGHT] as Core
const LEFT_ARC = [ARC_LEFT] as Core
const LEFT_BOATHOOK_RIGHT_ARC = [...LEFT_BOATHOOK, ...RIGHT_ARC] as Core
const LEFT_BARB_RIGHT_BOATHOOK = [...LEFT_BARB, ...RIGHT_BOATHOOK] as Core
const LEFT_ARC_RIGHT_SCROLL = [...LEFT_ARC, ...RIGHT_SCROLL] as Core
const LEFT_BOATHOOK_RIGHT_BARB = [...LEFT_BOATHOOK, ...RIGHT_BARB] as Core
const DOUBLE_LEFT_BARB = [...LEFT_BARB, ...LEFT_BARB] as Core
const LEFT_SCROLL_AND_DOUBLE_LEFT_BARB = [...LEFT_SCROLL, ...DOUBLE_LEFT_BARB] as Core
const LEFT_BARB_RIGHT_ARC = [...LEFT_BARB, ...RIGHT_ARC] as Core
const LEFT_ARC_RIGHT_BOATHOOK = [...LEFT_ARC, ...RIGHT_BOATHOOK] as Core
const DOUBLE_BARB = [...LEFT_BARB, ...RIGHT_BARB] as Core
const LEFT_ARC_AND_BARB = [...LEFT_ARC, ...LEFT_BARB] as Core
const LEFT_SCROLL_AND_DOUBLE_BARB = [...LEFT_SCROLL, ...DOUBLE_BARB] as Core
const RIGHT_BARB_AND_ARC = [...RIGHT_BARB, ...RIGHT_ARC] as Core
const DOUBLE_ARC = [...LEFT_ARC, ...RIGHT_ARC] as Core
const DOUBLE_RIGHT_BARB = [...RIGHT_BARB, ...RIGHT_BARB] as Core
const LEFT_ARC_RIGHT_BARB = [...LEFT_ARC, ...RIGHT_BARB] as Core
const LEFT_SCROLL_DOUBLE_RIGHT_BARB = [...LEFT_SCROLL, ...DOUBLE_RIGHT_BARB] as Core

export {
    LEFT_SCROLL,
    RIGHT_SCROLL,
    LEFT_BOATHOOK,
    DOUBLE_SCROLL,
    LEFT_SCROLL_AND_BOATHOOK,
    LEFT_BOATHOOK_RIGHT_SCROLL,
    RIGHT_BOATHOOK,
    DOUBLE_LEFT_BOATHOOK,
    LEFT_SCROLL_RIGHT_BOATHOOK,
    LEFT_BARB,
    LEFT_SCROLL_AND_BARB,
    RIGHT_ARC,
    LEFT_SCROLL_RIGHT_ARC,
    RIGHT_BARB,
    LEFT_ARC,
    LEFT_BOATHOOK_RIGHT_ARC,
    LEFT_BARB_RIGHT_BOATHOOK,
    LEFT_ARC_RIGHT_SCROLL,
    LEFT_BOATHOOK_RIGHT_BARB,
    DOUBLE_LEFT_BARB,
    LEFT_SCROLL_AND_DOUBLE_LEFT_BARB,
    LEFT_BARB_RIGHT_ARC,
    LEFT_ARC_RIGHT_BOATHOOK,
    DOUBLE_BARB,
    LEFT_ARC_AND_BARB,
    LEFT_SCROLL_AND_DOUBLE_BARB,
    RIGHT_BARB_AND_ARC,
    DOUBLE_ARC,
    DOUBLE_RIGHT_BARB,
    LEFT_ARC_RIGHT_BARB,
    LEFT_SCROLL_DOUBLE_RIGHT_BARB,
}
