import { Apotome, Count, Direction, Id } from "../../general"
import { SymbolLongAscii, SymbolUnicode } from "../io"
import { RevoSymbol, SymbolClass } from "./types"

const REVO_SYMBOLS: RevoSymbol[] = [
    {
        id: 0 as Id<RevoSymbol>,
        symbolClassId: 0 as Id<SymbolClass>,
        ascii: "|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 1 as Id<RevoSymbol>,
        symbolClassId: 1 as Id<SymbolClass>,
        ascii: "`|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 2 as Id<RevoSymbol>,
        symbolClassId: 2 as Id<SymbolClass>,
        ascii: "``|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 3 as Id<RevoSymbol>,
        symbolClassId: 3 as Id<SymbolClass>,
        ascii: ".)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 4 as Id<RevoSymbol>,
        symbolClassId: 4 as Id<SymbolClass>,
        ascii: "'|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 5 as Id<RevoSymbol>,
        symbolClassId: 5 as Id<SymbolClass>,
        ascii: "`'|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 6 as Id<RevoSymbol>,
        symbolClassId: 6 as Id<SymbolClass>,
        ascii: ",)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 7 as Id<RevoSymbol>,
        symbolClassId: 7 as Id<SymbolClass>,
        ascii: ")|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 8 as Id<RevoSymbol>,
        symbolClassId: 8 as Id<SymbolClass>,
        ascii: "`)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 9 as Id<RevoSymbol>,
        symbolClassId: 9 as Id<SymbolClass>,
        ascii: "``)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 10 as Id<RevoSymbol>,
        symbolClassId: 10 as Id<SymbolClass>,
        ascii: ",,|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 11 as Id<RevoSymbol>,
        symbolClassId: 11 as Id<SymbolClass>,
        ascii: ",|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 12 as Id<RevoSymbol>,
        symbolClassId: 12 as Id<SymbolClass>,
        ascii: "|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 13 as Id<RevoSymbol>,
        symbolClassId: 13 as Id<SymbolClass>,
        ascii: "`|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 14 as Id<RevoSymbol>,
        symbolClassId: 14 as Id<SymbolClass>,
        ascii: ".~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 15 as Id<RevoSymbol>,
        symbolClassId: 15 as Id<SymbolClass>,
        ascii: ",'|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 16 as Id<RevoSymbol>,
        symbolClassId: 16 as Id<SymbolClass>,
        ascii: "'|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 17 as Id<RevoSymbol>,
        symbolClassId: 17 as Id<SymbolClass>,
        ascii: ",~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 18 as Id<RevoSymbol>,
        symbolClassId: 18 as Id<SymbolClass>,
        ascii: "~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 19 as Id<RevoSymbol>,
        symbolClassId: 19 as Id<SymbolClass>,
        ascii: ",)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 20 as Id<RevoSymbol>,
        symbolClassId: 20 as Id<SymbolClass>,
        ascii: ")|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 21 as Id<RevoSymbol>,
        symbolClassId: 21 as Id<SymbolClass>,
        ascii: "`)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 22 as Id<RevoSymbol>,
        symbolClassId: 22 as Id<SymbolClass>,
        ascii: "``)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 23 as Id<RevoSymbol>,
        symbolClassId: 23 as Id<SymbolClass>,
        ascii: ",')|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 24 as Id<RevoSymbol>,
        symbolClassId: 24 as Id<SymbolClass>,
        ascii: "')|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 25 as Id<RevoSymbol>,
        symbolClassId: 25 as Id<SymbolClass>,
        ascii: ")~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 26 as Id<RevoSymbol>,
        symbolClassId: 26 as Id<SymbolClass>,
        ascii: ".~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 27 as Id<RevoSymbol>,
        symbolClassId: 27 as Id<SymbolClass>,
        ascii: "`.~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 28 as Id<RevoSymbol>,
        symbolClassId: 28 as Id<SymbolClass>,
        ascii: ",,~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 29 as Id<RevoSymbol>,
        symbolClassId: 29 as Id<SymbolClass>,
        ascii: ",~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 30 as Id<RevoSymbol>,
        symbolClassId: 30 as Id<SymbolClass>,
        ascii: "~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 31 as Id<RevoSymbol>,
        symbolClassId: 31 as Id<SymbolClass>,
        ascii: "`~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 32 as Id<RevoSymbol>,
        symbolClassId: 32 as Id<SymbolClass>,
        ascii: ",,|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 33 as Id<RevoSymbol>,
        symbolClassId: 33 as Id<SymbolClass>,
        ascii: ",|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 34 as Id<RevoSymbol>,
        symbolClassId: 34 as Id<SymbolClass>,
        ascii: "|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 35 as Id<RevoSymbol>,
        symbolClassId: 35 as Id<SymbolClass>,
        ascii: "`|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 36 as Id<RevoSymbol>,
        symbolClassId: 36 as Id<SymbolClass>,
        ascii: "~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 37 as Id<RevoSymbol>,
        symbolClassId: 37 as Id<SymbolClass>,
        ascii: "`~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 38 as Id<RevoSymbol>,
        symbolClassId: 38 as Id<SymbolClass>,
        ascii: "``~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 39 as Id<RevoSymbol>,
        symbolClassId: 39 as Id<SymbolClass>,
        ascii: ",./|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 40 as Id<RevoSymbol>,
        symbolClassId: 40 as Id<SymbolClass>,
        ascii: "./|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 41 as Id<RevoSymbol>,
        symbolClassId: 41 as Id<SymbolClass>,
        ascii: ")|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 42 as Id<RevoSymbol>,
        symbolClassId: 42 as Id<SymbolClass>,
        ascii: ",,/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 43 as Id<RevoSymbol>,
        symbolClassId: 43 as Id<SymbolClass>,
        ascii: ",/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 44 as Id<RevoSymbol>,
        symbolClassId: 44 as Id<SymbolClass>,
        ascii: "/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 45 as Id<RevoSymbol>,
        symbolClassId: 45 as Id<SymbolClass>,
        ascii: "`/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 46 as Id<RevoSymbol>,
        symbolClassId: 46 as Id<SymbolClass>,
        ascii: "``/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 47 as Id<RevoSymbol>,
        symbolClassId: 47 as Id<SymbolClass>,
        ascii: ".)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 48 as Id<RevoSymbol>,
        symbolClassId: 48 as Id<SymbolClass>,
        ascii: "'/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 49 as Id<RevoSymbol>,
        symbolClassId: 49 as Id<SymbolClass>,
        ascii: "`'/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 50 as Id<RevoSymbol>,
        symbolClassId: 50 as Id<SymbolClass>,
        ascii: ",,)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 51 as Id<RevoSymbol>,
        symbolClassId: 51 as Id<SymbolClass>,
        ascii: ",)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 52 as Id<RevoSymbol>,
        symbolClassId: 52 as Id<SymbolClass>,
        ascii: ")/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 53 as Id<RevoSymbol>,
        symbolClassId: 53 as Id<SymbolClass>,
        ascii: ",.|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 54 as Id<RevoSymbol>,
        symbolClassId: 54 as Id<SymbolClass>,
        ascii: ".|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 55 as Id<RevoSymbol>,
        symbolClassId: 55 as Id<SymbolClass>,
        ascii: "`.|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 56 as Id<RevoSymbol>,
        symbolClassId: 56 as Id<SymbolClass>,
        ascii: ",,|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 57 as Id<RevoSymbol>,
        symbolClassId: 57 as Id<SymbolClass>,
        ascii: ",|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 58 as Id<RevoSymbol>,
        symbolClassId: 58 as Id<SymbolClass>,
        ascii: "|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 59 as Id<RevoSymbol>,
        symbolClassId: 59 as Id<SymbolClass>,
        ascii: "`|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 60 as Id<RevoSymbol>,
        symbolClassId: 60 as Id<SymbolClass>,
        ascii: "``|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 61 as Id<RevoSymbol>,
        symbolClassId: 61 as Id<SymbolClass>,
        ascii: ",'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 62 as Id<RevoSymbol>,
        symbolClassId: 62 as Id<SymbolClass>,
        ascii: "'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 63 as Id<RevoSymbol>,
        symbolClassId: 63 as Id<SymbolClass>,
        ascii: "`'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 64 as Id<RevoSymbol>,
        symbolClassId: 64 as Id<SymbolClass>,
        ascii: ",)|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 65 as Id<RevoSymbol>,
        symbolClassId: 65 as Id<SymbolClass>,
        ascii: ")|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 66 as Id<RevoSymbol>,
        symbolClassId: 66 as Id<SymbolClass>,
        ascii: ".(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 67 as Id<RevoSymbol>,
        symbolClassId: 67 as Id<SymbolClass>,
        ascii: "|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 68 as Id<RevoSymbol>,
        symbolClassId: 68 as Id<SymbolClass>,
        ascii: "`|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 69 as Id<RevoSymbol>,
        symbolClassId: 69 as Id<SymbolClass>,
        ascii: ",(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 70 as Id<RevoSymbol>,
        symbolClassId: 70 as Id<SymbolClass>,
        ascii: "(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 71 as Id<RevoSymbol>,
        symbolClassId: 71 as Id<SymbolClass>,
        ascii: "`(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 72 as Id<RevoSymbol>,
        symbolClassId: 72 as Id<SymbolClass>,
        ascii: "``(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 73 as Id<RevoSymbol>,
        symbolClassId: 73 as Id<SymbolClass>,
        ascii: ",'(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 74 as Id<RevoSymbol>,
        symbolClassId: 74 as Id<SymbolClass>,
        ascii: "'(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 75 as Id<RevoSymbol>,
        symbolClassId: 75 as Id<SymbolClass>,
        ascii: ",~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 76 as Id<RevoSymbol>,
        symbolClassId: 76 as Id<SymbolClass>,
        ascii: "~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 77 as Id<RevoSymbol>,
        symbolClassId: 77 as Id<SymbolClass>,
        ascii: "`~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 78 as Id<RevoSymbol>,
        symbolClassId: 78 as Id<SymbolClass>,
        ascii: ",.(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 79 as Id<RevoSymbol>,
        symbolClassId: 79 as Id<SymbolClass>,
        ascii: ".(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 80 as Id<RevoSymbol>,
        symbolClassId: 80 as Id<SymbolClass>,
        ascii: "'~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 81 as Id<RevoSymbol>,
        symbolClassId: 81 as Id<SymbolClass>,
        ascii: "/|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 82 as Id<RevoSymbol>,
        symbolClassId: 82 as Id<SymbolClass>,
        ascii: ",,(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 83 as Id<RevoSymbol>,
        symbolClassId: 83 as Id<SymbolClass>,
        ascii: ",(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 84 as Id<RevoSymbol>,
        symbolClassId: 84 as Id<SymbolClass>,
        ascii: "(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 85 as Id<RevoSymbol>,
        symbolClassId: 85 as Id<SymbolClass>,
        ascii: "`(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 86 as Id<RevoSymbol>,
        symbolClassId: 86 as Id<SymbolClass>,
        ascii: "~|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 87 as Id<RevoSymbol>,
        symbolClassId: 87 as Id<SymbolClass>,
        ascii: ",.//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 88 as Id<RevoSymbol>,
        symbolClassId: 88 as Id<SymbolClass>,
        ascii: ".//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 89 as Id<RevoSymbol>,
        symbolClassId: 89 as Id<SymbolClass>,
        ascii: "`.//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 90 as Id<RevoSymbol>,
        symbolClassId: 90 as Id<SymbolClass>,
        ascii: ",,//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 91 as Id<RevoSymbol>,
        symbolClassId: 91 as Id<SymbolClass>,
        ascii: ",//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 92 as Id<RevoSymbol>,
        symbolClassId: 92 as Id<SymbolClass>,
        ascii: "//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 93 as Id<RevoSymbol>,
        symbolClassId: 93 as Id<SymbolClass>,
        ascii: "`//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 94 as Id<RevoSymbol>,
        symbolClassId: 94 as Id<SymbolClass>,
        ascii: "``//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 95 as Id<RevoSymbol>,
        symbolClassId: 95 as Id<SymbolClass>,
        ascii: ",'//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 96 as Id<RevoSymbol>,
        symbolClassId: 96 as Id<SymbolClass>,
        ascii: "'//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 97 as Id<RevoSymbol>,
        symbolClassId: 97 as Id<SymbolClass>,
        ascii: ",,)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 98 as Id<RevoSymbol>,
        symbolClassId: 98 as Id<SymbolClass>,
        ascii: ",)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 99 as Id<RevoSymbol>,
        symbolClassId: 99 as Id<SymbolClass>,
        ascii: ")//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 100 as Id<RevoSymbol>,
        symbolClassId: 100 as Id<SymbolClass>,
        ascii: "`)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 101 as Id<RevoSymbol>,
        symbolClassId: 101 as Id<SymbolClass>,
        ascii: "``)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 102 as Id<RevoSymbol>,
        symbolClassId: 102 as Id<SymbolClass>,
        ascii: ",,/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 103 as Id<RevoSymbol>,
        symbolClassId: 103 as Id<SymbolClass>,
        ascii: ",/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 104 as Id<RevoSymbol>,
        symbolClassId: 104 as Id<SymbolClass>,
        ascii: "/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 105 as Id<RevoSymbol>,
        symbolClassId: 105 as Id<SymbolClass>,
        ascii: "`/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 106 as Id<RevoSymbol>,
        symbolClassId: 106 as Id<SymbolClass>,
        ascii: "(|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 107 as Id<RevoSymbol>,
        symbolClassId: 107 as Id<SymbolClass>,
        ascii: ",'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 108 as Id<RevoSymbol>,
        symbolClassId: 108 as Id<SymbolClass>,
        ascii: "'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 109 as Id<RevoSymbol>,
        symbolClassId: 109 as Id<SymbolClass>,
        ascii: "`'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 110 as Id<RevoSymbol>,
        symbolClassId: 110 as Id<SymbolClass>,
        ascii: "./|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 111 as Id<RevoSymbol>,
        symbolClassId: 111 as Id<SymbolClass>,
        ascii: "`./|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 112 as Id<RevoSymbol>,
        symbolClassId: 112 as Id<SymbolClass>,
        ascii: ",,/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 113 as Id<RevoSymbol>,
        symbolClassId: 113 as Id<SymbolClass>,
        ascii: ",/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 114 as Id<RevoSymbol>,
        symbolClassId: 114 as Id<SymbolClass>,
        ascii: "/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 115 as Id<RevoSymbol>,
        symbolClassId: 115 as Id<SymbolClass>,
        ascii: "`/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 116 as Id<RevoSymbol>,
        symbolClassId: 116 as Id<SymbolClass>,
        ascii: ",(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 117 as Id<RevoSymbol>,
        symbolClassId: 117 as Id<SymbolClass>,
        ascii: "(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 118 as Id<RevoSymbol>,
        symbolClassId: 118 as Id<SymbolClass>,
        ascii: "`(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 119 as Id<RevoSymbol>,
        symbolClassId: 119 as Id<SymbolClass>,
        ascii: "'/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 120 as Id<RevoSymbol>,
        symbolClassId: 120 as Id<SymbolClass>,
        ascii: "`'/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 121 as Id<RevoSymbol>,
        symbolClassId: 121 as Id<SymbolClass>,
        ascii: ",)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 122 as Id<RevoSymbol>,
        symbolClassId: 122 as Id<SymbolClass>,
        ascii: ")/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 123 as Id<RevoSymbol>,
        symbolClassId: 123 as Id<SymbolClass>,
        ascii: "`)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 124 as Id<RevoSymbol>,
        symbolClassId: 124 as Id<SymbolClass>,
        ascii: "``)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 125 as Id<RevoSymbol>,
        symbolClassId: 125 as Id<SymbolClass>,
        ascii: ",.(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 126 as Id<RevoSymbol>,
        symbolClassId: 126 as Id<SymbolClass>,
        ascii: ".(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 127 as Id<RevoSymbol>,
        symbolClassId: 127 as Id<SymbolClass>,
        ascii: ",|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 128 as Id<RevoSymbol>,
        symbolClassId: 128 as Id<SymbolClass>,
        ascii: "|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 129 as Id<RevoSymbol>,
        symbolClassId: 129 as Id<SymbolClass>,
        ascii: "`|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 130 as Id<RevoSymbol>,
        symbolClassId: 130 as Id<SymbolClass>,
        ascii: ",(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 131 as Id<RevoSymbol>,
        symbolClassId: 131 as Id<SymbolClass>,
        ascii: "(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 132 as Id<RevoSymbol>,
        symbolClassId: 132 as Id<SymbolClass>,
        ascii: "`(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 133 as Id<RevoSymbol>,
        symbolClassId: 133 as Id<SymbolClass>,
        ascii: "``(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 134 as Id<RevoSymbol>,
        symbolClassId: 134 as Id<SymbolClass>,
        ascii: ",'(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 135 as Id<RevoSymbol>,
        symbolClassId: 135 as Id<SymbolClass>,
        ascii: "'(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 136 as Id<RevoSymbol>,
        symbolClassId: 136 as Id<SymbolClass>,
        ascii: ",.(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 137 as Id<RevoSymbol>,
        symbolClassId: 137 as Id<SymbolClass>,
        ascii: ".(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 138 as Id<RevoSymbol>,
        symbolClassId: 138 as Id<SymbolClass>,
        ascii: "`.(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 139 as Id<RevoSymbol>,
        symbolClassId: 139 as Id<SymbolClass>,
        ascii: "|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 140 as Id<RevoSymbol>,
        symbolClassId: 140 as Id<SymbolClass>,
        ascii: ",(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 141 as Id<RevoSymbol>,
        symbolClassId: 141 as Id<SymbolClass>,
        ascii: "(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 142 as Id<RevoSymbol>,
        symbolClassId: 142 as Id<SymbolClass>,
        ascii: "`(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 143 as Id<RevoSymbol>,
        symbolClassId: 143 as Id<SymbolClass>,
        ascii: "``(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 144 as Id<RevoSymbol>,
        symbolClassId: 144 as Id<SymbolClass>,
        ascii: ",,)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 145 as Id<RevoSymbol>,
        symbolClassId: 145 as Id<SymbolClass>,
        ascii: ",)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 146 as Id<RevoSymbol>,
        symbolClassId: 146 as Id<SymbolClass>,
        ascii: ")|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 147 as Id<RevoSymbol>,
        symbolClassId: 147 as Id<SymbolClass>,
        ascii: "`)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    {
        id: 148 as Id<RevoSymbol>,
        symbolClassId: 148 as Id<SymbolClass>,
        ascii: "``)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        direction: Direction.SUPER,
        apotomeCount: 0 as Count<Apotome>,
    },
    // TODO: finish adding subs, ± apotome count versions (which will have their own ids but recurring symbolClassIds
]

export {
    REVO_SYMBOLS,
}
