import { Id } from "../../general"
import { SymbolLongAscii } from "../io"
import { SagittalComma, SymbolClass, SymbolSubset } from "./types"

const SYMBOL_CLASSES: SymbolClass[] = [
    {
        id: 0 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 0 as Id<SagittalComma>,
        elements: [] as SymbolLongAscii[],
    },
    {
        id: 1 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 1 as Id<SagittalComma>,
        elements: ["`|"] as SymbolLongAscii[],
    },
    {
        id: 2 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 2 as Id<SagittalComma>,
        elements: ["``|"] as SymbolLongAscii[],
    },
    {
        id: 3 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 3 as Id<SagittalComma>,
        elements: [".|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 4 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 4 as Id<SagittalComma>,
        elements: ["'|"] as SymbolLongAscii[],
    },
    {
        id: 5 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 5 as Id<SagittalComma>,
        elements: ["`|", "'|"] as SymbolLongAscii[],
    },
    {
        id: 6 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 6 as Id<SagittalComma>,
        elements: [",|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 7 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 7 as Id<SagittalComma>,
        elements: [")|"] as SymbolLongAscii[],
    },
    {
        id: 8 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 8 as Id<SagittalComma>,
        elements: ["`|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 9 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 9 as Id<SagittalComma>,
        elements: ["``|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 10 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 10 as Id<SagittalComma>,
        elements: [",,|", "|("] as SymbolLongAscii[],
    },
    {
        id: 11 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 11 as Id<SagittalComma>,
        elements: [",|", "|("] as SymbolLongAscii[],
    },
    {
        id: 12 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 12 as Id<SagittalComma>,
        elements: ["|("] as SymbolLongAscii[],
    },
    {
        id: 13 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 13 as Id<SagittalComma>,
        elements: ["`|", "|("] as SymbolLongAscii[],
    },
    {
        id: 14 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 14 as Id<SagittalComma>,
        elements: [".|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 15 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 15 as Id<SagittalComma>,
        elements: [",|", "'|", "|("] as SymbolLongAscii[],
    },
    {
        id: 16 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 16 as Id<SagittalComma>,
        elements: ["'|", "|("] as SymbolLongAscii[],
    },
    {
        id: 17 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 17 as Id<SagittalComma>,
        elements: [",|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 18 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 18 as Id<SagittalComma>,
        elements: ["~|"] as SymbolLongAscii[],
    },
    {
        id: 19 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 19 as Id<SagittalComma>,
        elements: [",|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 20 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.ATHENIAN,
        primaryCommaId: 20 as Id<SagittalComma>,
        elements: [")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 21 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 21 as Id<SagittalComma>,
        elements: ["`|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 22 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 22 as Id<SagittalComma>,
        elements: ["``|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 23 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 23 as Id<SagittalComma>,
        elements: [",|", "'|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 24 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 24 as Id<SagittalComma>,
        elements: ["'|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 25 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 25 as Id<SagittalComma>,
        elements: [")|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 26 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 26 as Id<SagittalComma>,
        elements: [".|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 27 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 27 as Id<SagittalComma>,
        elements: ["`|", ".|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 28 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 28 as Id<SagittalComma>,
        elements: [",,|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 29 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 29 as Id<SagittalComma>,
        elements: [",|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 30 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.ATHENIAN,
        primaryCommaId: 30 as Id<SagittalComma>,
        elements: ["~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 31 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 31 as Id<SagittalComma>,
        elements: ["`|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 32 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 32 as Id<SagittalComma>,
        elements: [",,|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 33 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 33 as Id<SagittalComma>,
        elements: [",|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 34 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 34 as Id<SagittalComma>,
        elements: ["|~"] as SymbolLongAscii[],
    },
    {
        id: 35 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 35 as Id<SagittalComma>,
        elements: ["`|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 36 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 36 as Id<SagittalComma>,
        elements: ["~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 37 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 37 as Id<SagittalComma>,
        elements: ["`|", "~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 38 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 38 as Id<SagittalComma>,
        elements: ["``|", "~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 39 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 39 as Id<SagittalComma>,
        elements: [",|", ".|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 40 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 40 as Id<SagittalComma>,
        elements: [".|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 41 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 41 as Id<SagittalComma>,
        elements: [")|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 42 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 42 as Id<SagittalComma>,
        elements: [",,|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 43 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 43 as Id<SagittalComma>,
        elements: [",|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 44 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 44 as Id<SagittalComma>,
        elements: ["/|"] as SymbolLongAscii[],
    },
    {
        id: 45 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 45 as Id<SagittalComma>,
        elements: ["`|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 46 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 46 as Id<SagittalComma>,
        elements: ["``|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 47 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 47 as Id<SagittalComma>,
        elements: [".|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 48 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 48 as Id<SagittalComma>,
        elements: ["'|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 49 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 49 as Id<SagittalComma>,
        elements: ["`|", "'|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 50 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 50 as Id<SagittalComma>,
        elements: [",,|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 51 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 51 as Id<SagittalComma>,
        elements: [",|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 52 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 52 as Id<SagittalComma>,
        elements: [")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 53 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 53 as Id<SagittalComma>,
        elements: [",|", ".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 54 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 54 as Id<SagittalComma>,
        elements: [".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 55 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 55 as Id<SagittalComma>,
        elements: ["`|", ".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 56 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 56 as Id<SagittalComma>,
        elements: [",,|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 57 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 57 as Id<SagittalComma>,
        elements: [",|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 58 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 58 as Id<SagittalComma>,
        elements: ["|)"] as SymbolLongAscii[],
    },
    {
        id: 59 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 59 as Id<SagittalComma>,
        elements: ["`|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 60 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 60 as Id<SagittalComma>,
        elements: ["``|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 61 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 61 as Id<SagittalComma>,
        elements: [",|", "'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 62 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 62 as Id<SagittalComma>,
        elements: ["'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 63 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 63 as Id<SagittalComma>,
        elements: ["`|", "'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 64 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 64 as Id<SagittalComma>,
        elements: [",|", ")|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 65 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 65 as Id<SagittalComma>,
        elements: [")|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 66 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 66 as Id<SagittalComma>,
        elements: [".|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 67 as Id<SymbolClass>,
        // Exceptional. All other Athenian symbols already introduced at Medium precision.
        smallestSymbolSubset: SymbolSubset.ATHENIAN,
        primaryCommaId: 67 as Id<SagittalComma>,
        elements: ["|\\"] as SymbolLongAscii[],
    },
    {
        id: 68 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 68 as Id<SagittalComma>,
        elements: ["`|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 69 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 69 as Id<SagittalComma>,
        elements: [",|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 70 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.ATHENIAN,
        primaryCommaId: 70 as Id<SagittalComma>,
        elements: ["(|"] as SymbolLongAscii[],
    },
    {
        id: 71 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 71 as Id<SagittalComma>,
        elements: ["`|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 72 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 72 as Id<SagittalComma>,
        elements: ["``|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 73 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 73 as Id<SagittalComma>,
        elements: [",|", "'|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 74 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 74 as Id<SagittalComma>,
        elements: ["'|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 75 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 75 as Id<SagittalComma>,
        elements: [",|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 76 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 76 as Id<SagittalComma>,
        elements: ["~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 77 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 77 as Id<SagittalComma>,
        elements: ["`|", "~|", "|)"] as SymbolLongAscii[],
    },
    // Missing ID 78 as an artifact from the removal of the forum topic re: a consistent 37-prime-limit
    // http://forum.sagittal.org/viewtopic.php?f=4&t=448
    // TODO: I'd really like to go through and update the spreadsheet calculator, Everything Sagittal,
    //  and this code base to close this missing gap, this missing "key" / symbol class ID of 78
    {
        id: 79 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 79 as Id<SagittalComma>,
        elements: [",|", ".|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 80 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 80 as Id<SagittalComma>,
        elements: [".|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 81 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 81 as Id<SagittalComma>,
        elements: ["'|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 82 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 82 as Id<SagittalComma>,
        elements: ["/|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 83 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 83 as Id<SagittalComma>,
        elements: [",,|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 84 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 84 as Id<SagittalComma>,
        elements: [",|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 85 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.ATHENIAN,
        primaryCommaId: 85 as Id<SagittalComma>,
        elements: ["(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 86 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 86 as Id<SagittalComma>,
        elements: ["`|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 87 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 87 as Id<SagittalComma>,
        elements: ["~|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 88 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 88 as Id<SagittalComma>,
        elements: [",|", ".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 89 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 89 as Id<SagittalComma>,
        elements: [".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 90 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 90 as Id<SagittalComma>,
        elements: ["`|", ".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 91 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 91 as Id<SagittalComma>,
        elements: [",,|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 92 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 92 as Id<SagittalComma>,
        elements: [",|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 93 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 93 as Id<SagittalComma>,
        elements: ["/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 94 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 94 as Id<SagittalComma>,
        elements: ["`|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 95 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 95 as Id<SagittalComma>,
        elements: ["``|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 96 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 96 as Id<SagittalComma>,
        elements: [",|", "'|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 97 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 97 as Id<SagittalComma>,
        elements: ["'|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 98 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 98 as Id<SagittalComma>,
        elements: [",,|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 99 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 99 as Id<SagittalComma>,
        elements: [",|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 100 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 100 as Id<SagittalComma>,
        elements: [")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 101 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 101 as Id<SagittalComma>,
        elements: ["`|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 102 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 102 as Id<SagittalComma>,
        elements: ["``|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 103 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 103 as Id<SagittalComma>,
        elements: [",,|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 104 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 104 as Id<SagittalComma>,
        elements: [",|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 105 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 105 as Id<SagittalComma>,
        elements: ["/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 106 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 106 as Id<SagittalComma>,
        elements: ["`|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 107 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 107 as Id<SagittalComma>,
        elements: ["(|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 108 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 108 as Id<SagittalComma>,
        elements: [",|", "'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 109 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 109 as Id<SagittalComma>,
        elements: ["'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 110 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 110 as Id<SagittalComma>,
        elements: ["`|", "'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 111 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 111 as Id<SagittalComma>,
        elements: [".|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 112 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 112 as Id<SagittalComma>,
        elements: ["`|", ".|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 113 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 113 as Id<SagittalComma>,
        elements: [",,|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 114 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 114 as Id<SagittalComma>,
        elements: [",|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 115 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 115 as Id<SagittalComma>,
        elements: ["/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 116 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 116 as Id<SagittalComma>,
        elements: ["`|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 117 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 117 as Id<SagittalComma>,
        elements: [",|", "(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 118 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 118 as Id<SagittalComma>,
        elements: ["(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 119 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 119 as Id<SagittalComma>,
        elements: ["`|", "(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 120 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 120 as Id<SagittalComma>,
        elements: ["'|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 121 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 121 as Id<SagittalComma>,
        elements: ["`|", "'|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 122 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 122 as Id<SagittalComma>,
        elements: [",|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 123 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 123 as Id<SagittalComma>,
        elements: [")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 124 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 124 as Id<SagittalComma>,
        elements: ["`|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 125 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 125 as Id<SagittalComma>,
        elements: ["``|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 126 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 126 as Id<SagittalComma>,
        elements: [",|", ".|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 127 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 127 as Id<SagittalComma>,
        elements: [".|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 128 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 128 as Id<SagittalComma>,
        elements: [",|", "|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 129 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 129 as Id<SagittalComma>,
        elements: ["|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 130 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 130 as Id<SagittalComma>,
        elements: ["`|", "|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 131 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 131 as Id<SagittalComma>,
        elements: [",|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 132 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 132 as Id<SagittalComma>,
        elements: ["(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 133 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 133 as Id<SagittalComma>,
        elements: ["`|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 134 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 134 as Id<SagittalComma>,
        elements: ["``|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 135 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 135 as Id<SagittalComma>,
        elements: [",|", "'|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 136 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 136 as Id<SagittalComma>,
        elements: ["'|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 137 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 137 as Id<SagittalComma>,
        elements: [",|", ".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 138 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.HERCULEAN,
        primaryCommaId: 138 as Id<SagittalComma>,
        elements: [".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 139 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 139 as Id<SagittalComma>,
        elements: ["`|", ".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 140 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 140 as Id<SagittalComma>,
        elements: ["|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 141 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 141 as Id<SagittalComma>,
        elements: [",|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 142 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.SPARTAN,
        primaryCommaId: 142 as Id<SagittalComma>,
        elements: ["(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 143 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 143 as Id<SagittalComma>,
        elements: ["`|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 144 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 144 as Id<SagittalComma>,
        elements: ["``|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 145 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 145 as Id<SagittalComma>,
        elements: [",,|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 146 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 146 as Id<SagittalComma>,
        elements: [",|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 147 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.PROMETHEAN,
        primaryCommaId: 147 as Id<SagittalComma>,
        elements: [")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 148 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 148 as Id<SagittalComma>,
        elements: ["`|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 149 as Id<SymbolClass>,
        smallestSymbolSubset: SymbolSubset.OLYMPIAN,
        primaryCommaId: 149 as Id<SagittalComma>,
        elements: ["``|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
]

export {
    SYMBOL_CLASSES,
}
