import { Cents, Id, Integer, Rank } from "../../../../../../../src/general"
import { Bound } from "../../../../../../../src/sagittal/notations/ji"
import { AnalyzedBound } from "../../../../../../../src/scripts/bound/analyzeBound"
import { AnalyzedEvent } from "../../../../../../../src/scripts/bound/analyzedHistory"
import { formatBound } from "../../../../../../../src/scripts/bound/io"
import { analyzedBoundFixture, boundFixture } from "../../../../../../helpers/src/scripts/bound/fixtures"

describe("computeFormattedBound", () => {
    it("returns a string which is a multi-line, properly indented rendition of the analyzed bound, as well as identifying information for the bound", () => {
        const bound = {
            ...boundFixture,
            cents: 5.44763529181809 as Cents,
            id: 10 as Id<Bound>,
        }
        const analyzedBound: AnalyzedBound = {
            ...analyzedBoundFixture,
            bestRank: 2 as Rank<AnalyzedEvent, Integer>,
        }

        const actual = formatBound(analyzedBound, { bound })

        const expected = [
            `{`,
            `    "extremeLevelLesserBoundedSymbol": ",,|(",`,
            `    "extremeLevelGreaterBoundedSymbol": ",|(",`,
            `    "cents": 5.44763529181809,`,
            `    "boundedSymbols": {`,
            `        "id": 10,`,
            `        "extreme": [`,
            `            {`,
            `                "id": 10,`,
            `                "distance": 0.20389718131741752,`,
            `                "inaDistance": 0.417891900562867,`,
            `                "ascii": ",,|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 10,`,
            `                "elements": [`,
            `                    ",,|",`,
            `                    "|("`,
            `                ],`,
            `                "analyzedPrimaryComma": {`,
            `                    "id": 10,`,
            `                    "monzo": [`,
            `                        5,`,
            `                        -3,`,
            `                        0,`,
            `                        0,`,
            `                        1,`,
            `                        -1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        352,`,
            `                        351`,
            `                    ],`,
            `                    "cents": 4.925277999283972,`,
            `                    "limit": 13,`,
            `                    "apotomeSlope": -3.3032673101806025,`,
            `                    "twoThreeFreeClass": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            1`,
            `                        ]`,
            `                    },`,
            `                    "twoThreeFreeSopfr": 24,`,
            `                    "n2d3p9": 34.425925925925924,`,
            `                    "name": "11/13k"`,
            `                }`,
            `            },`,
            `            {`,
            `                "id": 11,`,
            `                "distance": 0.3184601112166945,`,
            `                "inaDistance": 0.6526912254006633,`,
            `                "ascii": ",|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 11,`,
            `                "elements": [`,
            `                    ",|",`,
            `                    "|("`,
            `                ],`,
            `                "analyzedPrimaryComma": {`,
            `                    "id": 11,`,
            `                    "monzo": [`,
            `                        -11,`,
            `                        6,`,
            `                        0,`,
            `                        0,`,
            `                        -1,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        22599,`,
            `                        22528`,
            `                    ],`,
            `                    "cents": 5.447635291818084,`,
            `                    "limit": 31,`,
            `                    "apotomeSlope": 5.664569248266845,`,
            `                    "twoThreeFreeClass": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            1`,
            `                        ]`,
            `                    },`,
            `                    "twoThreeFreeSopfr": 42,`,
            `                    "n2d3p9": 195.75925925925924,`,
            `                    "name": "31/11k"`,
            `                }`,
            `            }`,
            `        ],`,
            `        "insane": [`,
            `            {`,
            `                "id": 10,`,
            `                "distance": 0.20389718131741752,`,
            `                "inaDistance": 1.4509637234135597,`,
            `                "ascii": ",,|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 10,`,
            `                "elements": [`,
            `                    ",,|",`,
            `                    "|("`,
            `                ],`,
            `                "analyzedPrimaryComma": {`,
            `                    "id": 10,`,
            `                    "monzo": [`,
            `                        5,`,
            `                        -3,`,
            `                        0,`,
            `                        0,`,
            `                        1,`,
            `                        -1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        352,`,
            `                        351`,
            `                    ],`,
            `                    "cents": 4.925277999283972,`,
            `                    "limit": 13,`,
            `                    "apotomeSlope": -3.3032673101806025,`,
            `                    "twoThreeFreeClass": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            1`,
            `                        ]`,
            `                    },`,
            `                    "twoThreeFreeSopfr": 24,`,
            `                    "n2d3p9": 34.425925925925924,`,
            `                    "name": "11/13k"`,
            `                }`,
            `            },`,
            `            {`,
            `                "id": 11,`,
            `                "distance": 0.3184601112166945,`,
            `                "inaDistance": 2.2662111645885687,`,
            `                "ascii": ",|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 11,`,
            `                "elements": [`,
            `                    ",|",`,
            `                    "|("`,
            `                ],`,
            `                "analyzedPrimaryComma": {`,
            `                    "id": 11,`,
            `                    "monzo": [`,
            `                        -11,`,
            `                        6,`,
            `                        0,`,
            `                        0,`,
            `                        -1,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        1`,
            `                    ],`,
            `                    "ratio": [`,
            `                        22599,`,
            `                        22528`,
            `                    ],`,
            `                    "cents": 5.447635291818084,`,
            `                    "limit": 31,`,
            `                    "apotomeSlope": 5.664569248266845,`,
            `                    "twoThreeFreeClass": {`,
            `                        "monzo": [`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            -1,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            0,`,
            `                            1`,
            `                        ]`,
            `                    },`,
            `                    "twoThreeFreeSopfr": 42,`,
            `                    "n2d3p9": 195.75925925925924,`,
            `                    "name": "31/11k"`,
            `                }`,
            `            }`,
            `        ]`,
            `    },`,
            `    "lesserBoundedMina": 10,`,
            `    "greaterBoundedMina": 11`,
            `}`,
            `{`,
            `    "bestPossibleHistory": {`,
            `        "events": [],`,
            `        "cents": 0,`,
            `        "rank": 0,`,
            `        "score": 0,`,
            `        "totalDistance": 0,`,
            `        "exact": false,`,
            `        "totalInaDistance": 0,`,
            `        "possible": false,`,
            `        "tinaError": 0,`,
            `        "initialPositionTinaDistance": 0`,
            `    },`,
            `    "bestRank": 2,`,
            `    "initialPosition": 0,`,
            `    "initialPositionTinaDistance": 0,`,
            `    "bestPossibleHistoryTotalDistance": 0,`,
            `    "bestPossibleHistoryTotalInaDistance": 0,`,
            `    "consolidatedHistories": {},`,
            `    "possibleHistoryCount": 0`,
            `}`,
        ].join("\n")

        expect(actual).toEqual(expected)
    })
})
