import { Cents, Id, Integer, Rank } from "../../../../../../../src/general"
import { Bound } from "../../../../../../../src/sagittal/notations/ji"
import { AnalyzedBound } from "../../../../../../../src/scripts/bound/analyzeBound"
import { AnalyzedEvent } from "../../../../../../../src/scripts/bound/analyzedHistory"
import { formatBound } from "../../../../../../../src/scripts/bound/io"
import { boundFixture } from "../../../../../../helpers/src/scripts/bound/fixtures"

describe("computeFormattedBound", () => {
    it("returns a string which is a multi-line, properly indented rendition of the analyzed bound, as well as identifying information for the bound", () => {
        const bound = {
            ...boundFixture,
            cents: 5.44763529181809 as Cents,
            id: 10 as Id<Bound>,
        }
        const analyzedBound: AnalyzedBound = {
            bestRank: 2 as Rank<AnalyzedEvent, Integer>,
        } as AnalyzedBound

        const actual = formatBound(analyzedBound, { bound })

        const expected = [
            `{`,
            `    "extremeLevelLesserBoundedSymbol": ",,|(",`,
            `    "extremeLevelGreaterBoundedSymbol": ",|(",`,
            `    "cents": 5.44763529181809,`,
            `    "boundedSymbols": {`,
            `        "id": 10,`,
            `        "extreme": [`,
            `            {`,
            `                "id": 10,`,
            `                "distance": 0.20389718131742995,`,
            `                "inaDistance": 0.4178919005628925,`,
            `                "ascii": ",,|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 10,`,
            `                "elements": [`,
            `                    ",,|",`,
            `                    "|("`,
            `                ],`,
            `                "primaryComma": {`,
            `                    "id": 10,`,
            `                    "apotomeSlope": -3.303,`,
            `                    "fiveRoughSopfr": 24,`,
            `                    "limit": 13,`,
            `                    "ratio": [`,
            `                        352,`,
            `                        351`,
            `                    ],`,
            `                    "monzo": [`,
            `                        5,`,
            `                        -3,`,
            `                        0,`,
            `                        0,`,
            `                        1,`,
            `                        -1`,
            `                    ],`,
            `                    "cents": 4.92527799928397,`,
            `                    "name": "11/13k",`,
            `                    "n2d3p9": 34.425925925925924`,
            `                }`,
            `            },`,
            `            {`,
            `                "id": 11,`,
            `                "distance": 0.31846011121669004,`,
            `                "inaDistance": 0.6526912254006542,`,
            `                "ascii": ",|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 11,`,
            `                "elements": [`,
            `                    ",|",`,
            `                    "|("`,
            `                ],`,
            `                "primaryComma": {`,
            `                    "id": 11,`,
            `                    "apotomeSlope": 5.665,`,
            `                    "fiveRoughSopfr": 42,`,
            `                    "limit": 31,`,
            `                    "ratio": [`,
            `                        22599,`,
            `                        22528`,
            `                    ],`,
            `                    "monzo": [`,
            `                        -11,`,
            `                        6,`,
            `                        0,`,
            `                        0,`,
            `                        -1,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        1`,
            `                    ],`,
            `                    "cents": 5.44763529181809,`,
            `                    "name": "31/11k",`,
            `                    "n2d3p9": 195.75925925925924`,
            `                }`,
            `            }`,
            `        ],`,
            `        "insane": [`,
            `            {`,
            `                "id": 10,`,
            `                "distance": 0.20389718131742995,`,
            `                "inaDistance": 1.450963723413648,`,
            `                "ascii": ",,|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 10,`,
            `                "elements": [`,
            `                    ",,|",`,
            `                    "|("`,
            `                ],`,
            `                "primaryComma": {`,
            `                    "id": 10,`,
            `                    "apotomeSlope": -3.303,`,
            `                    "fiveRoughSopfr": 24,`,
            `                    "limit": 13,`,
            `                    "ratio": [`,
            `                        352,`,
            `                        351`,
            `                    ],`,
            `                    "monzo": [`,
            `                        5,`,
            `                        -3,`,
            `                        0,`,
            `                        0,`,
            `                        1,`,
            `                        -1`,
            `                    ],`,
            `                    "cents": 4.92527799928397,`,
            `                    "name": "11/13k",`,
            `                    "n2d3p9": 34.425925925925924`,
            `                }`,
            `            },`,
            `            {`,
            `                "id": 11,`,
            `                "distance": 0.31846011121669004,`,
            `                "inaDistance": 2.266211164588537,`,
            `                "ascii": ",|(",`,
            `                "unicode": "",`,
            `                "introducingLevel": "extreme",`,
            `                "smallestJiSymbolSubset": "olympian",`,
            `                "mina": 11,`,
            `                "elements": [`,
            `                    ",|",`,
            `                    "|("`,
            `                ],`,
            `                "primaryComma": {`,
            `                    "id": 11,`,
            `                    "apotomeSlope": 5.665,`,
            `                    "fiveRoughSopfr": 42,`,
            `                    "limit": 31,`,
            `                    "ratio": [`,
            `                        22599,`,
            `                        22528`,
            `                    ],`,
            `                    "monzo": [`,
            `                        -11,`,
            `                        6,`,
            `                        0,`,
            `                        0,`,
            `                        -1,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        0,`,
            `                        1`,
            `                    ],`,
            `                    "cents": 5.44763529181809,`,
            `                    "name": "31/11k",`,
            `                    "n2d3p9": 195.75925925925924`,
            `                }`,
            `            }`,
            `        ]`,
            `    },`,
            `    "lesserBoundedMina": 10,`,
            `    "greaterBoundedMina": 11`,
            `}`,
            `{`,
            `    "bestRank": 2`,
            `}`,
        ].join("\n")

        expect(actual).toEqual(expected)
    })
})
