import { Filename, Monzo } from "../../general"
import {
    DEFAULT_MAX_ABSOLUTE_3_EXPONENT,
    DEFAULT_MAX_ABSOLUTE_APOTOME_SLOPE,
    DEFAULT_MAX_CENTS,
    DEFAULT_MIN_CENTS,
    DEFAULT_PITCH_SCRIPT_GROUP_MAX_N2D3P9,
    DEFAULT_SORT_KEY,
} from "../../sagittal"

const PITCH_SCRIPT_GROUP = "pitch" as Filename

const INITIAL_PITCH_SCRIPT_GROUP_SETTINGS = {
    minCents: DEFAULT_MIN_CENTS,
    maxCents: DEFAULT_MAX_CENTS,
    maxAbsolute3Exponent: DEFAULT_MAX_ABSOLUTE_3_EXPONENT,
    maxAbsoluteApotomeSlope: DEFAULT_MAX_ABSOLUTE_APOTOME_SLOPE,
    maxN2D3P9: DEFAULT_PITCH_SCRIPT_GROUP_MAX_N2D3P9,
    sortKey: DEFAULT_SORT_KEY,
    commaNameOptions: {},
}

const TWO_THREE_FREE_MONZO_BASE = [0, 0] as Monzo<{ rough: 5 }>

export {
    PITCH_SCRIPT_GROUP,
    INITIAL_PITCH_SCRIPT_GROUP_SETTINGS,
    TWO_THREE_FREE_MONZO_BASE,
}
