import { Id } from "../../../general"
import { SymbolLongAscii, SymbolUnicode } from "../../io"
import { SagittalComma, SymbolSubset } from "../types"
import { JiSymbol, Level, Mina } from "./types"

// TODO: - I wonder if the philosophy should be this:
//  in the implementation, have the absolute minimum amount of info
//  and have things like this exist as tests (could use JiSymbolWithPrimaryComma type)
//  that might solve the dilemma of the "Analyzed<>" parameterized type
//  and some of the rational/not-rational stuff too
//  if this was literally just an id and monzo. everything else could be calculated
//  there are questions of performance, I suppose
//  but also of page load time...
//  yes and perhaps in such a test the comma information would be regrouped with the symbol information, 
//  so it'd be a quick reference
//  This here is perhaps not truly "symbols", because a symbol should be something which contains 
//  - ascii, unicode, elements, symbolSubset, isMultishaft
//  (and smallestJiSymbolSubset should just be a thing you ask of it, a separate list of a sorted subset of subsets)
//  (there'd be a method which would get you the mixed versions of ascii and unicode from the pure)
//  and it would include tons of stuff from the SMuFL Map, like SMuFL class name and description
//  and heraldic and graphical glyph description
//  like its Sagispeak (just the spelling, all else could be calculated from that)
//  before you go through with this, review all the stuff about elements vs symbols though
//  so are these JiSagittals here? 

const JI_SYMBOLS: JiSymbol[] = [
    {
        id: 0 as Id<JiSymbol>,
        ascii: "|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 0 as Mina,
        primaryCommaId: 0 as Id<SagittalComma>,
        elements: [] as SymbolLongAscii[],
    },
    {
        id: 1 as Id<JiSymbol>,
        ascii: "`|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 1 as Mina,
        primaryCommaId: 1 as Id<SagittalComma>,
        elements: ["`|"] as SymbolLongAscii[],
    },
    {
        id: 2 as Id<JiSymbol>,
        ascii: "``|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 2 as Mina,
        primaryCommaId: 2 as Id<SagittalComma>,
        elements: ["``|"] as SymbolLongAscii[],
    },
    {
        id: 3 as Id<JiSymbol>,
        ascii: ".)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 3 as Mina,
        primaryCommaId: 3 as Id<SagittalComma>,
        elements: [".|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 4 as Id<JiSymbol>,
        ascii: "'|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 4 as Mina,
        primaryCommaId: 4 as Id<SagittalComma>,
        elements: ["'|"] as SymbolLongAscii[],
    },
    {
        id: 5 as Id<JiSymbol>,
        ascii: "`'|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 5 as Mina,
        primaryCommaId: 5 as Id<SagittalComma>,
        elements: ["`|", "'|"] as SymbolLongAscii[],
    },
    {
        id: 6 as Id<JiSymbol>,
        ascii: ",)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 6 as Mina,
        primaryCommaId: 6 as Id<SagittalComma>,
        elements: [",|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 7 as Id<JiSymbol>,
        ascii: ")|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 7 as Mina,
        primaryCommaId: 7 as Id<SagittalComma>,
        elements: [")|"] as SymbolLongAscii[],
    },
    {
        id: 8 as Id<JiSymbol>,
        ascii: "`)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 8 as Mina,
        primaryCommaId: 8 as Id<SagittalComma>,
        elements: ["`|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 9 as Id<JiSymbol>,
        ascii: "``)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 9 as Mina,
        primaryCommaId: 9 as Id<SagittalComma>,
        elements: ["``|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 10 as Id<JiSymbol>,
        ascii: ",,|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 10 as Mina,
        primaryCommaId: 10 as Id<SagittalComma>,
        elements: [",,|", "|("] as SymbolLongAscii[],
    },
    {
        id: 11 as Id<JiSymbol>,
        ascii: ",|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 11 as Mina,
        primaryCommaId: 11 as Id<SagittalComma>,
        elements: [",|", "|("] as SymbolLongAscii[],
    },
    {
        id: 12 as Id<JiSymbol>,
        ascii: "|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 12 as Mina,
        primaryCommaId: 12 as Id<SagittalComma>,
        elements: ["|("] as SymbolLongAscii[],
    },
    {
        id: 13 as Id<JiSymbol>,
        ascii: "`|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 13 as Mina,
        primaryCommaId: 13 as Id<SagittalComma>,
        elements: ["`|", "|("] as SymbolLongAscii[],
    },
    {
        id: 14 as Id<JiSymbol>,
        ascii: ".~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 14 as Mina,
        primaryCommaId: 14 as Id<SagittalComma>,
        elements: [".|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 15 as Id<JiSymbol>,
        ascii: ",'|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 15 as Mina,
        primaryCommaId: 15 as Id<SagittalComma>,
        elements: [",|", "'|", "|("] as SymbolLongAscii[],
    },
    {
        id: 16 as Id<JiSymbol>,
        ascii: "'|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 16 as Mina,
        primaryCommaId: 16 as Id<SagittalComma>,
        elements: ["'|", "|("] as SymbolLongAscii[],
    },
    {
        id: 17 as Id<JiSymbol>,
        ascii: ",~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 17 as Mina,
        primaryCommaId: 17 as Id<SagittalComma>,
        elements: [",|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 18 as Id<JiSymbol>,
        ascii: "~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 18 as Mina,
        primaryCommaId: 18 as Id<SagittalComma>,
        elements: ["~|"] as SymbolLongAscii[],
    },
    {
        id: 19 as Id<JiSymbol>,
        ascii: ",)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 19 as Mina,
        primaryCommaId: 19 as Id<SagittalComma>,
        elements: [",|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 20 as Id<JiSymbol>,
        ascii: ")|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.ATHENIAN,
        mina: 20 as Mina,
        primaryCommaId: 20 as Id<SagittalComma>,
        elements: [")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 21 as Id<JiSymbol>,
        ascii: "`)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 21 as Mina,
        primaryCommaId: 21 as Id<SagittalComma>,
        elements: ["`|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 22 as Id<JiSymbol>,
        ascii: "``)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 22 as Mina,
        primaryCommaId: 22 as Id<SagittalComma>,
        elements: ["``|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 23 as Id<JiSymbol>,
        ascii: ",')|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 23 as Mina,
        primaryCommaId: 23 as Id<SagittalComma>,
        elements: [",|", "'|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 24 as Id<JiSymbol>,
        ascii: "')|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 24 as Mina,
        primaryCommaId: 24 as Id<SagittalComma>,
        elements: ["'|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 25 as Id<JiSymbol>,
        ascii: ")~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 25 as Mina,
        primaryCommaId: 25 as Id<SagittalComma>,
        elements: [")|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 26 as Id<JiSymbol>,
        ascii: ".~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 26 as Mina,
        primaryCommaId: 26 as Id<SagittalComma>,
        elements: [".|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 27 as Id<JiSymbol>,
        ascii: "`.~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 27 as Mina,
        primaryCommaId: 27 as Id<SagittalComma>,
        elements: ["`|", ".|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 28 as Id<JiSymbol>,
        ascii: ",,~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 28 as Mina,
        primaryCommaId: 28 as Id<SagittalComma>,
        elements: [",,|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 29 as Id<JiSymbol>,
        ascii: ",~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 29 as Mina,
        primaryCommaId: 29 as Id<SagittalComma>,
        elements: [",|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 30 as Id<JiSymbol>,
        ascii: "~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.ATHENIAN,
        mina: 30 as Mina,
        primaryCommaId: 30 as Id<SagittalComma>,
        elements: ["~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 31 as Id<JiSymbol>,
        ascii: "`~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 31 as Mina,
        primaryCommaId: 31 as Id<SagittalComma>,
        elements: ["`|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 32 as Id<JiSymbol>,
        ascii: ",,|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 32 as Mina,
        primaryCommaId: 32 as Id<SagittalComma>,
        elements: [",,|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 33 as Id<JiSymbol>,
        ascii: ",|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 33 as Mina,
        primaryCommaId: 33 as Id<SagittalComma>,
        elements: [",|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 34 as Id<JiSymbol>,
        ascii: "|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 34 as Mina,
        primaryCommaId: 34 as Id<SagittalComma>,
        elements: ["|~"] as SymbolLongAscii[],
    },
    {
        id: 35 as Id<JiSymbol>,
        ascii: "`|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 35 as Mina,
        primaryCommaId: 35 as Id<SagittalComma>,
        elements: ["`|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 36 as Id<JiSymbol>,
        ascii: "~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 36 as Mina,
        primaryCommaId: 36 as Id<SagittalComma>,
        elements: ["~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 37 as Id<JiSymbol>,
        ascii: "`~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 37 as Mina,
        primaryCommaId: 37 as Id<SagittalComma>,
        elements: ["`|", "~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 38 as Id<JiSymbol>,
        ascii: "``~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 38 as Mina,
        primaryCommaId: 38 as Id<SagittalComma>,
        elements: ["``|", "~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 39 as Id<JiSymbol>,
        ascii: ",./|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 39 as Mina,
        primaryCommaId: 39 as Id<SagittalComma>,
        elements: [",|", ".|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 40 as Id<JiSymbol>,
        ascii: "./|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 40 as Mina,
        primaryCommaId: 40 as Id<SagittalComma>,
        elements: [".|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 41 as Id<JiSymbol>,
        ascii: ")|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 41 as Mina,
        primaryCommaId: 41 as Id<SagittalComma>,
        elements: [")|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 42 as Id<JiSymbol>,
        ascii: ",,/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 42 as Mina,
        primaryCommaId: 42 as Id<SagittalComma>,
        elements: [",,|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 43 as Id<JiSymbol>,
        ascii: ",/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 43 as Mina,
        primaryCommaId: 43 as Id<SagittalComma>,
        elements: [",|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 44 as Id<JiSymbol>,
        ascii: "/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 44 as Mina,
        primaryCommaId: 44 as Id<SagittalComma>,
        elements: ["/|"] as SymbolLongAscii[],
    },
    {
        id: 45 as Id<JiSymbol>,
        ascii: "`/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 45 as Mina,
        primaryCommaId: 45 as Id<SagittalComma>,
        elements: ["`|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 46 as Id<JiSymbol>,
        ascii: "``/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 46 as Mina,
        primaryCommaId: 46 as Id<SagittalComma>,
        elements: ["``|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 47 as Id<JiSymbol>,
        ascii: ".)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 47 as Mina,
        primaryCommaId: 47 as Id<SagittalComma>,
        elements: [".|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 48 as Id<JiSymbol>,
        ascii: "'/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 48 as Mina,
        primaryCommaId: 48 as Id<SagittalComma>,
        elements: ["'|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 49 as Id<JiSymbol>,
        ascii: "`'/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 49 as Mina,
        primaryCommaId: 49 as Id<SagittalComma>,
        elements: ["`|", "'|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 50 as Id<JiSymbol>,
        ascii: ",,)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 49.56756901073 as Mina,
        primaryCommaId: 50 as Id<SagittalComma>,
        elements: [",,|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 51 as Id<JiSymbol>,
        ascii: ",)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 50 as Mina,
        primaryCommaId: 51 as Id<SagittalComma>,
        elements: [",|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 52 as Id<JiSymbol>,
        ascii: ")/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 51 as Mina,
        primaryCommaId: 52 as Id<SagittalComma>,
        elements: [")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 53 as Id<JiSymbol>,
        ascii: ",.|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 51.458648572106 as Mina,
        primaryCommaId: 53 as Id<SagittalComma>,
        elements: [",|", ".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 54 as Id<JiSymbol>,
        ascii: ".|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 52 as Mina,
        primaryCommaId: 54 as Id<SagittalComma>,
        elements: [".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 55 as Id<JiSymbol>,
        ascii: "`.|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 53 as Mina,
        primaryCommaId: 55 as Id<SagittalComma>,
        elements: ["`|", ".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 56 as Id<JiSymbol>,
        ascii: ",,|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 54 as Mina,
        primaryCommaId: 56 as Id<SagittalComma>,
        elements: [",,|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 57 as Id<JiSymbol>,
        ascii: ",|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 55 as Mina,
        primaryCommaId: 57 as Id<SagittalComma>,
        elements: [",|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 58 as Id<JiSymbol>,
        ascii: "|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 56 as Mina,
        primaryCommaId: 58 as Id<SagittalComma>,
        elements: ["|)"] as SymbolLongAscii[],
    },
    {
        id: 59 as Id<JiSymbol>,
        ascii: "`|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 57 as Mina,
        primaryCommaId: 59 as Id<SagittalComma>,
        elements: ["`|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 60 as Id<JiSymbol>,
        ascii: "``|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 58 as Mina,
        primaryCommaId: 60 as Id<SagittalComma>,
        elements: ["``|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 61 as Id<JiSymbol>,
        ascii: ",'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 59 as Mina,
        primaryCommaId: 61 as Id<SagittalComma>,
        elements: [",|", "'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 62 as Id<JiSymbol>,
        ascii: "'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 60 as Mina,
        primaryCommaId: 62 as Id<SagittalComma>,
        elements: ["'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 63 as Id<JiSymbol>,
        ascii: "`'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 61 as Mina,
        primaryCommaId: 63 as Id<SagittalComma>,
        elements: ["`|", "'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 64 as Id<JiSymbol>,
        ascii: ",)|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 62 as Mina,
        primaryCommaId: 64 as Id<SagittalComma>,
        elements: [",|", ")|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 65 as Id<JiSymbol>,
        ascii: ")|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 63 as Mina,
        primaryCommaId: 65 as Id<SagittalComma>,
        elements: [")|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 66 as Id<JiSymbol>,
        ascii: ".(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 64 as Mina,
        primaryCommaId: 66 as Id<SagittalComma>,
        elements: [".|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 67 as Id<JiSymbol>,
        ascii: "|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH, // Exceptional. All other Athenian symbols already introduced at Medium precision.
        smallestJiSymbolSubset: SymbolSubset.ATHENIAN,
        mina: 65 as Mina,
        primaryCommaId: 67 as Id<SagittalComma>,
        elements: ["|\\"] as SymbolLongAscii[],
    },
    {
        id: 68 as Id<JiSymbol>,
        ascii: "`|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 66 as Mina,
        primaryCommaId: 68 as Id<SagittalComma>,
        elements: ["`|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 69 as Id<JiSymbol>,
        ascii: ",(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 67 as Mina,
        primaryCommaId: 69 as Id<SagittalComma>,
        elements: [",|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 70 as Id<JiSymbol>,
        ascii: "(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.ATHENIAN,
        mina: 68 as Mina,
        primaryCommaId: 70 as Id<SagittalComma>,
        elements: ["(|"] as SymbolLongAscii[],
    },
    {
        id: 71 as Id<JiSymbol>,
        ascii: "`(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 69 as Mina,
        primaryCommaId: 71 as Id<SagittalComma>,
        elements: ["`|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 72 as Id<JiSymbol>,
        ascii: "``(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 70 as Mina,
        primaryCommaId: 72 as Id<SagittalComma>,
        elements: ["``|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 73 as Id<JiSymbol>,
        ascii: ",'(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 71 as Mina,
        primaryCommaId: 73 as Id<SagittalComma>,
        elements: [",|", "'|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 74 as Id<JiSymbol>,
        ascii: "'(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 72 as Mina,
        primaryCommaId: 74 as Id<SagittalComma>,
        elements: ["'|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 75 as Id<JiSymbol>,
        ascii: ",~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 72.4048681076285 as Mina,
        primaryCommaId: 75 as Id<SagittalComma>,
        elements: [",|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 76 as Id<JiSymbol>,
        ascii: "~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 73 as Mina,
        primaryCommaId: 76 as Id<SagittalComma>,
        elements: ["~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 77 as Id<JiSymbol>,
        ascii: "`~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 74 as Mina,
        primaryCommaId: 77 as Id<SagittalComma>,
        elements: ["`|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 79 as Id<JiSymbol>,
        ascii: ",.(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 75 as Mina,
        primaryCommaId: 79 as Id<SagittalComma>,
        elements: [",|", ".|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 80 as Id<JiSymbol>,
        ascii: ".(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 76 as Mina,
        primaryCommaId: 80 as Id<SagittalComma>,
        elements: [".|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 81 as Id<JiSymbol>,
        ascii: "'~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 77 as Mina,
        primaryCommaId: 81 as Id<SagittalComma>,
        elements: ["'|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 82 as Id<JiSymbol>,
        ascii: "/|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 78 as Mina,
        primaryCommaId: 82 as Id<SagittalComma>,
        elements: ["/|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 83 as Id<JiSymbol>,
        ascii: ",,(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 78.3901455452392 as Mina,
        primaryCommaId: 83 as Id<SagittalComma>,
        elements: [",,|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 84 as Id<JiSymbol>,
        ascii: ",(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 79 as Mina,
        primaryCommaId: 84 as Id<SagittalComma>,
        elements: [",|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 85 as Id<JiSymbol>,
        ascii: "(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.ATHENIAN,
        mina: 80 as Mina,
        primaryCommaId: 85 as Id<SagittalComma>,
        elements: ["(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 86 as Id<JiSymbol>,
        ascii: "`(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 81 as Mina,
        primaryCommaId: 86 as Id<SagittalComma>,
        elements: ["`|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 87 as Id<JiSymbol>,
        ascii: "~|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 82 as Mina,
        primaryCommaId: 87 as Id<SagittalComma>,
        elements: ["~|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 88 as Id<JiSymbol>,
        ascii: ",.//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 83 as Mina,
        primaryCommaId: 88 as Id<SagittalComma>,
        elements: [",|", ".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 89 as Id<JiSymbol>,
        ascii: ".//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 84 as Mina,
        primaryCommaId: 89 as Id<SagittalComma>,
        elements: [".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 90 as Id<JiSymbol>,
        ascii: "`.//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 85 as Mina,
        primaryCommaId: 90 as Id<SagittalComma>,
        elements: ["`|", ".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 91 as Id<JiSymbol>,
        ascii: ",,//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 86 as Mina,
        primaryCommaId: 91 as Id<SagittalComma>,
        elements: [",,|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 92 as Id<JiSymbol>,
        ascii: ",//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 87 as Mina,
        primaryCommaId: 92 as Id<SagittalComma>,
        elements: [",|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 93 as Id<JiSymbol>,
        ascii: "//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 88 as Mina,
        primaryCommaId: 93 as Id<SagittalComma>,
        elements: ["/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 94 as Id<JiSymbol>,
        ascii: "`//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 89 as Mina,
        primaryCommaId: 94 as Id<SagittalComma>,
        elements: ["`|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 95 as Id<JiSymbol>,
        ascii: "``//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 90 as Mina,
        primaryCommaId: 95 as Id<SagittalComma>,
        elements: ["``|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 96 as Id<JiSymbol>,
        ascii: ",'//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 91 as Mina,
        primaryCommaId: 96 as Id<SagittalComma>,
        elements: [",|", "'|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 97 as Id<JiSymbol>,
        ascii: "'//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 92 as Mina,
        primaryCommaId: 97 as Id<SagittalComma>,
        elements: ["'|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 98 as Id<JiSymbol>,
        ascii: ",,)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 93 as Mina,
        primaryCommaId: 98 as Id<SagittalComma>,
        elements: [",,|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 99 as Id<JiSymbol>,
        ascii: ",)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 94 as Mina,
        primaryCommaId: 99 as Id<SagittalComma>,
        elements: [",|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 100 as Id<JiSymbol>,
        ascii: ")//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 95 as Mina,
        primaryCommaId: 100 as Id<SagittalComma>,
        elements: [")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 101 as Id<JiSymbol>,
        ascii: "`)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 96 as Mina,
        primaryCommaId: 101 as Id<SagittalComma>,
        elements: ["`|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 102 as Id<JiSymbol>,
        ascii: "``)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 97 as Mina,
        primaryCommaId: 102 as Id<SagittalComma>,
        elements: ["``|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 103 as Id<JiSymbol>,
        ascii: ",,/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 98 as Mina,
        primaryCommaId: 103 as Id<SagittalComma>,
        elements: [",,|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 104 as Id<JiSymbol>,
        ascii: ",/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 99 as Mina,
        primaryCommaId: 104 as Id<SagittalComma>,
        elements: [",|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 105 as Id<JiSymbol>,
        ascii: "/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 100 as Mina,
        primaryCommaId: 105 as Id<SagittalComma>,
        elements: ["/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 106 as Id<JiSymbol>,
        ascii: "`/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 101 as Mina,
        primaryCommaId: 106 as Id<SagittalComma>,
        elements: ["`|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 107 as Id<JiSymbol>,
        ascii: "(|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 102 as Mina,
        primaryCommaId: 107 as Id<SagittalComma>,
        elements: ["(|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 108 as Id<JiSymbol>,
        ascii: ",'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 103 as Mina,
        primaryCommaId: 108 as Id<SagittalComma>,
        elements: [",|", "'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 109 as Id<JiSymbol>,
        ascii: "'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 104 as Mina,
        primaryCommaId: 109 as Id<SagittalComma>,
        elements: ["'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 110 as Id<JiSymbol>,
        ascii: "`'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 105 as Mina,
        primaryCommaId: 110 as Id<SagittalComma>,
        elements: ["`|", "'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 111 as Id<JiSymbol>,
        ascii: "./|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 105.57202549664 as Mina,
        primaryCommaId: 111 as Id<SagittalComma>,
        elements: [".|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 112 as Id<JiSymbol>,
        ascii: "`./|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 106 as Mina,
        primaryCommaId: 112 as Id<SagittalComma>,
        elements: ["`|", ".|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 113 as Id<JiSymbol>,
        ascii: ",,/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 107 as Mina,
        primaryCommaId: 113 as Id<SagittalComma>,
        elements: [",,|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 114 as Id<JiSymbol>,
        ascii: ",/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 108 as Mina,
        primaryCommaId: 114 as Id<SagittalComma>,
        elements: [",|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 115 as Id<JiSymbol>,
        ascii: "/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 109 as Mina,
        primaryCommaId: 115 as Id<SagittalComma>,
        elements: ["/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 116 as Id<JiSymbol>,
        ascii: "`/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 110 as Mina,
        primaryCommaId: 116 as Id<SagittalComma>,
        elements: ["`|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 117 as Id<JiSymbol>,
        ascii: ",(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 111 as Mina,
        primaryCommaId: 117 as Id<SagittalComma>,
        elements: [",|", "(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 118 as Id<JiSymbol>,
        ascii: "(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 112 as Mina,
        primaryCommaId: 118 as Id<SagittalComma>,
        elements: ["(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 119 as Id<JiSymbol>,
        ascii: "`(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 113 as Mina,
        primaryCommaId: 119 as Id<SagittalComma>,
        elements: ["`|", "(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 120 as Id<JiSymbol>,
        ascii: "'/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 113.451709907417 as Mina,
        primaryCommaId: 120 as Id<SagittalComma>,
        elements: ["'|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 121 as Id<JiSymbol>,
        ascii: "`'/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 114 as Mina,
        primaryCommaId: 121 as Id<SagittalComma>,
        elements: ["`|", "'|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 122 as Id<JiSymbol>,
        ascii: ",)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 115 as Mina,
        primaryCommaId: 122 as Id<SagittalComma>,
        elements: [",|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 123 as Id<JiSymbol>,
        ascii: ")/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 116 as Mina,
        primaryCommaId: 123 as Id<SagittalComma>,
        elements: [")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 124 as Id<JiSymbol>,
        ascii: "`)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 117 as Mina,
        primaryCommaId: 124 as Id<SagittalComma>,
        elements: ["`|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 125 as Id<JiSymbol>,
        ascii: "``)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 118 as Mina,
        primaryCommaId: 125 as Id<SagittalComma>,
        elements: ["``|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 126 as Id<JiSymbol>,
        ascii: ",.(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 119 as Mina,
        primaryCommaId: 126 as Id<SagittalComma>,
        elements: [",|", ".|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 127 as Id<JiSymbol>,
        ascii: ".(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 120 as Mina,
        primaryCommaId: 127 as Id<SagittalComma>,
        elements: [".|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 128 as Id<JiSymbol>,
        ascii: ",|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 120.700329647587 as Mina,
        primaryCommaId: 128 as Id<SagittalComma>,
        elements: [",|", "|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 129 as Id<JiSymbol>,
        ascii: "|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 121 as Mina,
        primaryCommaId: 129 as Id<SagittalComma>,
        elements: ["|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 130 as Id<JiSymbol>,
        ascii: "`|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 122 as Mina,
        primaryCommaId: 130 as Id<SagittalComma>,
        elements: ["`|", "|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 131 as Id<JiSymbol>,
        ascii: ",(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 123 as Mina,
        primaryCommaId: 131 as Id<SagittalComma>,
        elements: [",|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 132 as Id<JiSymbol>,
        ascii: "(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 124 as Mina,
        primaryCommaId: 132 as Id<SagittalComma>,
        elements: ["(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 133 as Id<JiSymbol>,
        ascii: "`(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 125 as Mina,
        primaryCommaId: 133 as Id<SagittalComma>,
        elements: ["`|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 134 as Id<JiSymbol>,
        ascii: "``(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 126 as Mina,
        primaryCommaId: 134 as Id<SagittalComma>,
        elements: ["``|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 135 as Id<JiSymbol>,
        ascii: ",'(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 127 as Mina,
        primaryCommaId: 135 as Id<SagittalComma>,
        elements: [",|", "'|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 136 as Id<JiSymbol>,
        ascii: "'(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 128 as Mina,
        primaryCommaId: 136 as Id<SagittalComma>,
        elements: ["'|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 137 as Id<JiSymbol>,
        ascii: ",.(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 128.580014058364 as Mina,
        primaryCommaId: 137 as Id<SagittalComma>,
        elements: [",|", ".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 138 as Id<JiSymbol>,
        ascii: ".(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        smallestJiSymbolSubset: SymbolSubset.HERCULEAN,
        mina: 129 as Mina,
        primaryCommaId: 138 as Id<SagittalComma>,
        elements: [".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 139 as Id<JiSymbol>,
        ascii: "`.(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 130 as Mina,
        primaryCommaId: 139 as Id<SagittalComma>,
        elements: ["`|", ".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 140 as Id<JiSymbol>,
        ascii: "|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 131 as Mina,
        primaryCommaId: 140 as Id<SagittalComma>,
        elements: ["|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 141 as Id<JiSymbol>,
        ascii: ",(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 132 as Mina,
        primaryCommaId: 141 as Id<SagittalComma>,
        elements: [",|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 142 as Id<JiSymbol>,
        ascii: "(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        smallestJiSymbolSubset: SymbolSubset.SPARTAN,
        mina: 133 as Mina,
        primaryCommaId: 142 as Id<SagittalComma>,
        elements: ["(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 143 as Id<JiSymbol>,
        ascii: "`(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 134 as Mina,
        primaryCommaId: 143 as Id<SagittalComma>,
        elements: ["`|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 144 as Id<JiSymbol>,
        ascii: "``(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 135 as Mina,
        primaryCommaId: 144 as Id<SagittalComma>,
        elements: ["``|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 145 as Id<JiSymbol>,
        ascii: ",,)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 136 as Mina,
        primaryCommaId: 145 as Id<SagittalComma>,
        elements: [",,|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 146 as Id<JiSymbol>,
        ascii: ",)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 137 as Mina,
        primaryCommaId: 146 as Id<SagittalComma>,
        elements: [",|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 147 as Id<JiSymbol>,
        ascii: ")|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        smallestJiSymbolSubset: SymbolSubset.PROMETHEAN,
        mina: 138 as Mina,
        primaryCommaId: 147 as Id<SagittalComma>,
        elements: [")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 148 as Id<JiSymbol>,
        ascii: "`)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 139 as Mina,
        primaryCommaId: 148 as Id<SagittalComma>,
        elements: ["`|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 149 as Id<JiSymbol>,
        ascii: "``)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        smallestJiSymbolSubset: SymbolSubset.OLYMPIAN,
        mina: 140 as Mina,
        primaryCommaId: 149 as Id<SagittalComma>,
        elements: ["``|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
]

export {
    JI_SYMBOLS,
}
