import {FlaccoId} from "../../accidental"
import {BoundClassId} from "../../bound"
import {CommaClassId} from "../../ji"
import {Notation} from "../types"

const MEDIUM_NOTATION: Notation = {
    commaClassIds: [                    // Total 11
        CommaClassId._1_u,
        CommaClassId._5_7_k,
        CommaClassId._7_11_k,
        CommaClassId._17_C,
        CommaClassId._1_5_C,
        CommaClassId._1_7_C,
        CommaClassId._7_11_C,
        CommaClassId._5_11_S,
        CommaClassId._1_25_S,
        CommaClassId._1_35_M,
        CommaClassId._11_M,
    ] as CommaClassId[],
    boundClassIds: [                    // Total 11
        BoundClassId.MINA_5,
        BoundClassId.MINA_16,
        BoundClassId.MINA_27,
        BoundClassId.MINA_38,
        BoundClassId.MINA_50,
        BoundClassId.MINA_61,
        BoundClassId.MINA_72,
        BoundClassId.MINA_82,
        BoundClassId.MINA_92,
        BoundClassId.MINA_105,
        BoundClassId.MINA_116,
    ] as BoundClassId[],
    flaccoIds: [                        // Extra 2, total 13
        FlaccoId.NULL,
        FlaccoId.RIGHT_SCROLL,
        FlaccoId.DOUBLE_SCROLL,
        FlaccoId.BOATHOOK_AND_SCROLL,
        FlaccoId.LEFT_BARB,
        FlaccoId.RIGHT_ARC,
        FlaccoId.LEFT_ARC,
        FlaccoId.ARC_AND_SCROLL,
        FlaccoId.DOUBLE_LEFT_BARB,
        FlaccoId.BARB_AND_ARC,
        FlaccoId.DOUBLE_BARB,
        FlaccoId.DOUBLE_ARC,
        FlaccoId.ARC_AND_BARB,
    ] as FlaccoId[],
}

const HIGH_NOTATION: Notation = {
    commaClassIds: [                    // Total 27
        CommaClassId._1_u,
        CommaClassId._19_s,
        CommaClassId._5_7_k,
        CommaClassId._1_17_k,
        CommaClassId._7_11_k,
        CommaClassId._1_143_C,
        CommaClassId._17_C,
        CommaClassId._23_C,
        CommaClassId._11_49_C,
        CommaClassId._1_19_C,
        CommaClassId._1_5_C,
        CommaClassId._19_5_C,
        CommaClassId._1_7_C,
        CommaClassId._19_7_C,
        CommaClassId._55_C,
        CommaClassId._7_11_C,
        CommaClassId._49_S,
        CommaClassId._23_5_S,
        CommaClassId._5_11_S,
        CommaClassId._23_S,
        CommaClassId._1_25_S,
        CommaClassId._13_5_M,
        CommaClassId._1_35_M,
        CommaClassId._11_19_M,
        CommaClassId._11_M,
        CommaClassId._1_49_M,
        CommaClassId._5_49_M,
    ] as CommaClassId[],
    boundClassIds: [                    // Total 27
        BoundClassId.MINA_2,
        BoundClassId.MINA_9,
        BoundClassId.MINA_13,
        BoundClassId.MINA_18,
        BoundClassId.MINA_22,
        BoundClassId.MINA_27,
        BoundClassId.MINA_31,
        BoundClassId.MINA_35,
        BoundClassId.MINA_38,
        BoundClassId.MINA_41,
        BoundClassId.MINA_46,
        BoundClassId.MINA_53,
        BoundClassId.MINA_58,
        BoundClassId.MINA_63,
        BoundClassId.MINA_66,
        BoundClassId.MINA_70,
        BoundClassId.MINA_76,
        BoundClassId.MINA_78,
        BoundClassId.MINA_81,
        BoundClassId.MINA_85,
        BoundClassId.MINA_92,
        BoundClassId.MINA_97,
        BoundClassId.MINA_101,
        BoundClassId.MINA_106,
        BoundClassId.MINA_110,
        BoundClassId.MINA_114,
        BoundClassId.MINA_116,
    ] as BoundClassId[],
    flaccoIds: [                        // Extra 5, total 32
        FlaccoId.NULL,
        FlaccoId.LEFT_SCROLL,
        FlaccoId.RIGHT_SCROLL,
        FlaccoId.LEFT_BOATHOOK,
        FlaccoId.DOUBLE_SCROLL,
        FlaccoId.LEFT_SCROLL_AND_BOATHOOK,
        FlaccoId.BOATHOOK_AND_SCROLL,
        FlaccoId.RIGHT_BOATHOOK,
        FlaccoId.DOUBLE_LEFT_BOATHOOK,
        FlaccoId.SCROLL_AND_BOATHOOK,
        FlaccoId.LEFT_BARB,
        FlaccoId.LEFT_SCROLL_AND_BARB,
        FlaccoId.RIGHT_ARC,
        FlaccoId.SCROLL_AND_ARC,
        FlaccoId.RIGHT_BARB,
        FlaccoId.LEFT_ARC,
        FlaccoId.BOATHOOK_AND_ARC,
        FlaccoId.BARB_AND_BOATHOOK,
        FlaccoId.ARC_AND_SCROLL,
        FlaccoId.BOATHOOK_AND_BARB,
        FlaccoId.DOUBLE_LEFT_BARB,
        FlaccoId.LEFT_SCROLL_DOUBLE_LEFT_BARB,
        FlaccoId.BARB_AND_ARC,
        FlaccoId.ARC_AND_BOATHOOK,
        FlaccoId.DOUBLE_BARB,
        FlaccoId.LEFT_ARC_AND_BARB,
        FlaccoId.LEFT_SCROLL_AND_DOUBLE_BARB,
        FlaccoId.RIGHT_BARB_AND_ARC,
        FlaccoId.DOUBLE_ARC,
        FlaccoId.DOUBLE_RIGHT_BARB,
        FlaccoId.ARC_AND_BARB,
        FlaccoId.LEFT_SCROLL_DOUBLE_RIGHT_BARB,
    ] as FlaccoId[],
}

const ULTRA_NOTATION: Notation = {
    commaClassIds: [                    // Total 47
        CommaClassId._1_u,
        CommaClassId._19_5_n,
        CommaClassId._5_s,
        CommaClassId._19_s,
        CommaClassId._5_7_k,
        CommaClassId._1_85_k,
        CommaClassId._25_7_k,
        CommaClassId._1_17_k,
        CommaClassId._7_11_k,
        CommaClassId._35_11_k,
        CommaClassId._1_143_C,
        CommaClassId._17_5_C,
        CommaClassId._17_C,
        CommaClassId._23_C,
        CommaClassId._11_49_C,
        CommaClassId._1_25_C,
        CommaClassId._1_19_C,
        CommaClassId._1_5_C,
        CommaClassId._19_25_C,
        CommaClassId._1_C,
        CommaClassId._19_5_C,
        CommaClassId._1_35_C,
        CommaClassId._1_7_C,
        CommaClassId._5_7_C,
        CommaClassId._19_7_C,
        CommaClassId._7_55_C,
        CommaClassId._55_C,
        CommaClassId._7_11_C,
        CommaClassId._25_49_S,
        CommaClassId._49_S,
        CommaClassId._1_11_S,
        CommaClassId._245_S,
        CommaClassId._23_5_S,
        CommaClassId._5_11_S,
        CommaClassId._23_S,
        CommaClassId._1_125_S,
        CommaClassId._1_25_S,
        CommaClassId._13_19_S,
        CommaClassId._13_5_M,
        CommaClassId._1_35_M,
        CommaClassId._11_19_M,
        CommaClassId._1_7_M,
        CommaClassId._11_5_M,
        CommaClassId._11_M,
        CommaClassId._1_49_M,
        CommaClassId._55_M,
        CommaClassId._5_49_M,
    ] as CommaClassId[],
    boundClassIds: [                    // Total 47
        BoundClassId.MINA_2,
        BoundClassId.MINA_3,
        BoundClassId.MINA_5,
        BoundClassId.MINA_9,
        BoundClassId.MINA_13,
        BoundClassId.MINA_14,
        BoundClassId.MINA_16,
        BoundClassId.MINA_18,
        BoundClassId.MINA_22,
        BoundClassId.MINA_24,
        BoundClassId.MINA_25,
        BoundClassId.MINA_27,
        BoundClassId.MINA_31,
        BoundClassId.MINA_35,
        BoundClassId.MINA_38,
        BoundClassId.MINA_40,
        BoundClassId.MINA_41,
        BoundClassId.MINA_46,
        BoundClassId.MINA_47,
        BoundClassId.MINA_49,
        BoundClassId.MINA_51,
        BoundClassId.MINA_53,
        BoundClassId.MINA_58,
        BoundClassId.MINA_61,
        BoundClassId.MINA_63,
        BoundClassId.MINA_64,
        BoundClassId.MINA_66,
        BoundClassId.MINA_70,
        BoundClassId.MINA_72,
        BoundClassId.MINA_74,
        BoundClassId.MINA_76,
        BoundClassId.MINA_77,
        BoundClassId.MINA_78,
        BoundClassId.MINA_81,
        BoundClassId.MINA_82,
        BoundClassId.MINA_85,
        BoundClassId.MINA_90,
        BoundClassId.MINA_92,
        BoundClassId.MINA_97,
        BoundClassId.MINA_101,
        BoundClassId.MINA_102,
        BoundClassId.MINA_105,
        BoundClassId.MINA_106,
        BoundClassId.MINA_110,
        BoundClassId.MINA_113,
        BoundClassId.MINA_114,
        BoundClassId.MINA_116,
    ] as BoundClassId[],
    flaccoIds: [                        // Extra 8, total 55
        FlaccoId.NULL,
        FlaccoId.TICK_AGAINST_LEFT_SCROLL,
        FlaccoId.TICK,
        FlaccoId.LEFT_SCROLL,
        FlaccoId.RIGHT_SCROLL,
        FlaccoId.TICK_AGAINST_LEFT_BOATHOOK,
        FlaccoId.TICK_WITH_RIGHT_SCROLL,
        FlaccoId.LEFT_BOATHOOK,
        FlaccoId.DOUBLE_SCROLL,
        FlaccoId.TICK_WITH_DOUBLE_SCROLL,
        FlaccoId.LEFT_SCROLL_AND_BOATHOOK,
        FlaccoId.TICK_AGAINST_BOATHOOK_AND_SCROLL,
        FlaccoId.BOATHOOK_AND_SCROLL,
        FlaccoId.RIGHT_BOATHOOK,
        FlaccoId.DOUBLE_LEFT_BOATHOOK,
        FlaccoId.TICK_AGAINST_LEFT_BARB,
        FlaccoId.SCROLL_AND_BOATHOOK,
        FlaccoId.LEFT_BARB,
        FlaccoId.TICK_AGAINST_LEFT_SCROLL_AND_BARB,
        FlaccoId.TICK_WITH_LEFT_BARB,
        FlaccoId.LEFT_SCROLL_AND_BARB,
        FlaccoId.TICK_AGAINST_RIGHT_ARC,
        FlaccoId.RIGHT_ARC,
        FlaccoId.TICK_WITH_RIGHT_ARC,
        FlaccoId.SCROLL_AND_ARC,
        FlaccoId.TICK_AGAINST_LEFT_ARC,
        FlaccoId.RIGHT_BARB,
        FlaccoId.LEFT_ARC,
        FlaccoId.TICK_WITH_LEFT_ARC,
        FlaccoId.BOATHOOK_AND_ARC,
        FlaccoId.TICK_AGAINST_ARC_AND_SCROLL,
        FlaccoId.TICK_WITH_BOATHOOK_AND_ARC,
        FlaccoId.BARB_AND_BOATHOOK,
        FlaccoId.ARC_AND_SCROLL,
        FlaccoId.BOATHOOK_AND_BARB,
        FlaccoId.TICK_AGAINST_DOUBLE_LEFT_BARB,
        FlaccoId.DOUBLE_LEFT_BARB,
        FlaccoId.TICK_WITH_DOUBLE_LEFT_BARB,
        FlaccoId.LEFT_SCROLL_DOUBLE_LEFT_BARB,
        FlaccoId.BARB_AND_ARC,
        FlaccoId.ARC_AND_BOATHOOK,
        FlaccoId.TICK_WITH_BARB_AND_ARC,
        FlaccoId.TICK_AGAINST_DOUBLE_BARB,
        FlaccoId.DOUBLE_BARB,
        FlaccoId.LEFT_ARC_AND_BARB,
        FlaccoId.TICK_WITH_DOUBLE_BARB,
        FlaccoId.LEFT_SCROLL_AND_DOUBLE_BARB,
        FlaccoId.TICK_AGAINST_DOUBLE_ARC,
        FlaccoId.RIGHT_BARB_AND_ARC,
        FlaccoId.DOUBLE_ARC,
        FlaccoId.TICK_WITH_DOUBLE_ARC,
        FlaccoId.TICK_AGAINST_ARC_AND_BARB,
        FlaccoId.DOUBLE_RIGHT_BARB,
        FlaccoId.ARC_AND_BARB,
        FlaccoId.LEFT_SCROLL_DOUBLE_RIGHT_BARB,
    ] as FlaccoId[],
}

const EXTREME_NOTATION: Notation = {
    commaClassIds: Object.values(CommaClassId),     // Total 123
    boundClassIds: Object.values(BoundClassId),     // Total 123
    flaccoIds: Object.values(FlaccoId),             // Extra 26, total 149
}

export {
    MEDIUM_NOTATION,
    HIGH_NOTATION,
    ULTRA_NOTATION,
    EXTREME_NOTATION,
}
