import { SYMBOL_CLASSES } from "../symbolClasses"
import { JiNotationSymbolClass, JiNotationSymbolClassMetadata, Mina } from "./types"

// TODO: this might now be more just like EXTREME_NOTATION_MINA_NAMES
//  ...btw, do we really have ina names for the other notation levels?
//  and there could be a test for these
const JI_NOTATION_SYMBOL_CLASS_METADATA: JiNotationSymbolClassMetadata[] = [
    { mina: 0 as Mina },
    { mina: 1 as Mina },
    { mina: 2 as Mina },
    { mina: 3 as Mina },
    { mina: 4 as Mina },
    { mina: 5 as Mina },
    { mina: 6 as Mina },
    { mina: 7 as Mina },
    { mina: 8 as Mina },
    { mina: 9 as Mina },
    { mina: 10 as Mina },
    { mina: 11 as Mina },
    { mina: 12 as Mina },
    { mina: 13 as Mina },
    { mina: 14 as Mina },
    { mina: 15 as Mina },
    { mina: 16 as Mina },
    { mina: 17 as Mina },
    { mina: 18 as Mina },
    { mina: 19 as Mina },
    { mina: 20 as Mina },
    { mina: 21 as Mina },
    { mina: 22 as Mina },
    { mina: 23 as Mina },
    { mina: 24 as Mina },
    { mina: 25 as Mina },
    { mina: 26 as Mina },
    { mina: 27 as Mina },
    { mina: 28 as Mina },
    { mina: 29 as Mina },
    { mina: 30 as Mina },
    { mina: 31 as Mina },
    { mina: 32 as Mina },
    { mina: 33 as Mina },
    { mina: 34 as Mina },
    { mina: 35 as Mina },
    { mina: 36 as Mina },
    { mina: 37 as Mina },
    { mina: 38 as Mina },
    { mina: 39 as Mina },
    { mina: 40 as Mina },
    { mina: 41 as Mina },
    { mina: 42 as Mina },
    { mina: 43 as Mina },
    { mina: 44 as Mina },
    { mina: 45 as Mina },
    { mina: 46 as Mina },
    { mina: 47 as Mina },
    { mina: 48 as Mina },
    { mina: 49 as Mina },
    { mina: 49.56756901073 as Mina },
    { mina: 50 as Mina },
    { mina: 51 as Mina },
    { mina: 51.458648572106 as Mina },
    { mina: 52 as Mina },
    { mina: 53 as Mina },
    { mina: 54 as Mina },
    { mina: 55 as Mina },
    { mina: 56 as Mina },
    { mina: 57 as Mina },
    { mina: 58 as Mina },
    { mina: 59 as Mina },
    { mina: 60 as Mina },
    { mina: 61 as Mina },
    { mina: 62 as Mina },
    { mina: 63 as Mina },
    { mina: 64 as Mina },
    { mina: 65 as Mina },
    { mina: 66 as Mina },
    { mina: 67 as Mina },
    { mina: 68 as Mina },
    { mina: 69 as Mina },
    { mina: 70 as Mina },
    { mina: 71 as Mina },
    { mina: 72 as Mina },
    { mina: 72.4048681076285 as Mina },
    { mina: 73 as Mina },
    { mina: 74 as Mina },
    { mina: 75 as Mina },
    { mina: 76 as Mina },
    { mina: 77 as Mina },
    { mina: 78 as Mina },
    { mina: 78.3901455452392 as Mina },
    { mina: 79 as Mina },
    { mina: 80 as Mina },
    { mina: 81 as Mina },
    { mina: 82 as Mina },
    { mina: 83 as Mina },
    { mina: 84 as Mina },
    { mina: 85 as Mina },
    { mina: 86 as Mina },
    { mina: 87 as Mina },
    { mina: 88 as Mina },
    { mina: 89 as Mina },
    { mina: 90 as Mina },
    { mina: 91 as Mina },
    { mina: 92 as Mina },
    { mina: 93 as Mina },
    { mina: 94 as Mina },
    { mina: 95 as Mina },
    { mina: 96 as Mina },
    { mina: 97 as Mina },
    { mina: 98 as Mina },
    { mina: 99 as Mina },
    { mina: 100 as Mina },
    { mina: 101 as Mina },
    { mina: 102 as Mina },
    { mina: 103 as Mina },
    { mina: 104 as Mina },
    { mina: 105 as Mina },
    { mina: 105.57202549664 as Mina },
    { mina: 106 as Mina },
    { mina: 107 as Mina },
    { mina: 108 as Mina },
    { mina: 109 as Mina },
    { mina: 110 as Mina },
    { mina: 111 as Mina },
    { mina: 112 as Mina },
    { mina: 113 as Mina },
    { mina: 113.451709907417 as Mina },
    { mina: 114 as Mina },
    { mina: 115 as Mina },
    { mina: 116 as Mina },
    { mina: 117 as Mina },
    { mina: 118 as Mina },
    { mina: 119 as Mina },
    { mina: 120 as Mina },
    { mina: 120.700329647587 as Mina },
    { mina: 121 as Mina },
    { mina: 122 as Mina },
    { mina: 123 as Mina },
    { mina: 124 as Mina },
    { mina: 125 as Mina },
    { mina: 126 as Mina },
    { mina: 127 as Mina },
    { mina: 128 as Mina },
    { mina: 128.580014058364 as Mina },
    { mina: 129 as Mina },
    { mina: 130 as Mina },
    { mina: 131 as Mina },
    { mina: 132 as Mina },
    { mina: 133 as Mina },
    { mina: 134 as Mina },
    { mina: 135 as Mina },
    { mina: 136 as Mina },
    { mina: 137 as Mina },
    { mina: 138 as Mina },
    { mina: 139 as Mina },
    { mina: 140 as Mina },
]

const JI_NOTATION_SYMBOL_CLASSES: JiNotationSymbolClass[] = JI_NOTATION_SYMBOL_CLASS_METADATA
    .map((jiNotationSymbolClassMetadata: JiNotationSymbolClassMetadata, index: number): JiNotationSymbolClass => {
        return { ...jiNotationSymbolClassMetadata, ...SYMBOL_CLASSES[ index ] }
    })

export {
    JI_NOTATION_SYMBOL_CLASSES,
}
