import { Comma, halfScamon, THREE_PRIME_INDEX } from "../general"
import { Ascii, Smiley, Unicode } from "./io"
import { SagittalSymbol } from "./notations"

const APOTOME = { monzo: [-11, 7] } as Comma //   2187/2048         113.6850060577¢

const HALF_APOTOME = halfScamon(APOTOME)     // √(2187/2048)         56.8425030289¢

const APOTOME_3_EXPONENT = APOTOME.monzo![ THREE_PRIME_INDEX ]

const PARENTHETICAL_CONVENTIONAL_NATURAL_ASCII = "(|//|)" as Ascii
const PARENTHETICAL_CONVENTIONAL_NATURAL_UNICODE = "(♮)" as Unicode
const PARENTHETICAL_CONVENTIONAL_NATURAL_SMILEY = "(:h:)" as Smiley
const PARENTHETICAL_CONVENTIONAL_NATURAL_SYMBOL = PARENTHETICAL_CONVENTIONAL_NATURAL_ASCII as string as SagittalSymbol
const CONVENTIONAL_SHARP_ASCII = "#" as Ascii
const CONVENTIONAL_SHARP_UNICODE = "" as Unicode
const CONVENTIONAL_FLAT_ASCII = "b" as Ascii
const CONVENTIONAL_FLAT_UNICODE = "" as Unicode
const CONVENTIONAL_DOUBLE_SHARP_ASCII = "x" as Ascii
const CONVENTIONAL_DOUBLE_SHARP_UNICODE = "" as Unicode
const CONVENTIONAL_DOUBLE_FLAT_ASCII = "bb" as Ascii
const CONVENTIONAL_DOUBLE_FLAT_UNICODE = "" as Unicode

const ANY_ACCENT_CHAR = /[`,'.]/
const ANY_FLAG_CHAR = /[~()/\\]/

export {
    APOTOME,
    APOTOME_3_EXPONENT,
    HALF_APOTOME,
    PARENTHETICAL_CONVENTIONAL_NATURAL_ASCII,
    PARENTHETICAL_CONVENTIONAL_NATURAL_UNICODE,
    PARENTHETICAL_CONVENTIONAL_NATURAL_SMILEY,
    PARENTHETICAL_CONVENTIONAL_NATURAL_SYMBOL,
    CONVENTIONAL_SHARP_UNICODE,
    CONVENTIONAL_DOUBLE_SHARP_UNICODE,
    CONVENTIONAL_DOUBLE_FLAT_UNICODE,
    CONVENTIONAL_FLAT_UNICODE,
    CONVENTIONAL_DOUBLE_FLAT_ASCII,
    CONVENTIONAL_DOUBLE_SHARP_ASCII,
    CONVENTIONAL_FLAT_ASCII,
    CONVENTIONAL_SHARP_ASCII,
    ANY_ACCENT_CHAR,
    ANY_FLAG_CHAR,
}
