import {Io} from "../../../../../src/general/io"
import {onlyRunInCi} from "../../../../helpers/onlyRunInCi"
import {runScriptAndGetConsoleOutput} from "../../../../helpers/src/scripts/runScriptAndGetConsoleOutput"

describe("analyze-ji-pitches", (): void => {
    it("takes in the list of JI pitches in the input file and outputs a table of their analyses", (): void => {
        onlyRunInCi()

        const script = "npm run analyze-ji-pitches -- --table-format forum" as Io

        const actual = runScriptAndGetConsoleOutput(script)

        const expected = [
            "[table]",
            "[tr][th][pre]     [/pre][/th][th][pre]             [/pre][/th][th][pre]        [/pre][/th][th][pre]     [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre] [/pre][/th][th][pre]               [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]2,3-free[/pre][/th][th][pre]2,3-free[/pre][/th][th][pre]2,3-free[/pre][/th][th][pre]2,3-free[/pre][/th][th][pre]2,3-free[/pre][/th][/tr]",
            "[tr][th][pre]comma[/pre][/th][th][pre]             [/pre][/th][th][pre]        [/pre][/th][th][pre]monzo[/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre] [/pre][/th][th][pre]               [/pre][/th][th][pre]apotome[/pre][/th][th][pre]       [/pre][/th][th][pre]       [/pre][/th][th][pre]prime   [/pre][/th][th][pre]class   [/pre][/th][th][pre]class   [/pre][/th][th][pre]class   [/pre][/th][th][pre]class   [/pre][/th][/tr]",
            "[tr][th][pre]class[/pre][/th][th][pre]name         [/pre][/th][th][pre]quotient[/pre][/th][th][pre]     [/pre][/th][th][pre]  2    [/pre][/th][th][pre]  3    [/pre][/th][th][pre]  5    [/pre][/th][th][pre]  7    [/pre][/th][th][pre] 11    [/pre][/th][th][pre] 13    [/pre][/th][th][pre] 17    [/pre][/th][th][pre] 19    [/pre][/th][th][pre] 23    [/pre][/th][th][pre] 29    [/pre][/th][th][pre] 31    [/pre][/th][th][pre] 37    [/pre][/th][th][pre] [/pre][/th][th][pre]cents          [/pre][/th][th][pre]slope  [/pre][/th][th][pre]AAS    [/pre][/th][th][pre]ATE    [/pre][/th][th][pre]limit   [/pre][/th][th][pre]name    [/pre][/th][th][pre]CoPFR   [/pre][/th][th][pre]SoPFR   [/pre][/th][th][pre]N2D3P9  [/pre][/th][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]77/(5⋅37)n   [/pre][/td][td][pre][/pre][latex]\\frac{1515591}{1515520}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre]-13    [/pre][/td][td][pre]  9    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         0.081¢[/pre][/td][td][pre]  8.995[/pre][/td][td][pre]  8.995[/pre][/td][td][pre]  9    [/pre][/td][td][pre] 37     [/pre][/td][td][pre][/pre][latex]\\{\\frac{185}{77}\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  4     [/pre][/td][td][pre] 60     [/pre][/td][td][pre]1626.744[/pre][/td][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]7²⋅11⋅19/5n  [/pre][/td][td][pre][/pre][latex]\\frac{10241}{10240}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre]-11    [/pre][/td][td][pre]  0    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]  2    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         0.169¢[/pre][/td][td][pre] -0.010[/pre][/td][td][pre]  0.010[/pre][/td][td][pre]  0    [/pre][/td][td][pre] 19     [/pre][/td][td][pre][/pre][latex]\\{\\frac{10241}{5}\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  5     [/pre][/td][td][pre] 49     [/pre][/td][td][pre]2252.072[/pre][/td][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]1/(7³⋅17)n   [/pre][/td][td][pre][/pre][latex]\\frac{5832}{5831}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre]  3    [/pre][/td][td][pre]  6    [/pre][/td][td][pre]  0    [/pre][/td][td][pre] -3    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         0.297¢[/pre][/td][td][pre]  5.982[/pre][/td][td][pre]  5.982[/pre][/td][td][pre]  6    [/pre][/td][td][pre] 17     [/pre][/td][td][pre][/pre][latex]\\{5831\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  4     [/pre][/td][td][pre] 38     [/pre][/td][td][pre]688.382 [/pre][/td][/tr]",
            "[tr][td][pre][/pre]:`::|:[pre][/pre][/td][td][pre]1/(5⋅7⋅13)n  [/pre][/td][td][pre][/pre][latex]\\frac{4096}{4095}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre] 12    [/pre][/td][td][pre] -2    [/pre][/td][td][pre] -1    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]  0    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         0.423¢[/pre][/td][td][pre] -2.026[/pre][/td][td][pre]  2.026[/pre][/td][td][pre]  2    [/pre][/td][td][pre] 13     [/pre][/td][td][pre][/pre][latex]\\{455\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  3     [/pre][/td][td][pre] 25     [/pre][/td][td][pre] 82.153 [/pre][/td][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]5²⋅11²/7n    [/pre][/td][td][pre][/pre][latex]\\frac{3025}{3024}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre] -4    [/pre][/td][td][pre] -3    [/pre][/td][td][pre]  2    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]  2    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         0.572¢[/pre][/td][td][pre] -3.035[/pre][/td][td][pre]  3.035[/pre][/td][td][pre]  3    [/pre][/td][td][pre] 11     [/pre][/td][td][pre][/pre][latex]\\{\\frac{3025}{7}\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  5     [/pre][/td][td][pre] 39     [/pre][/td][td][pre]539.178 [/pre][/td][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]7⁴/25n       [/pre][/td][td][pre][/pre][latex]\\frac{2401}{2400}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre] -5    [/pre][/td][td][pre] -1    [/pre][/td][td][pre] -2    [/pre][/td][td][pre]  4    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         0.721¢[/pre][/td][td][pre] -1.044[/pre][/td][td][pre]  1.044[/pre][/td][td][pre]  1    [/pre][/td][td][pre]  7     [/pre][/td][td][pre][/pre][latex]\\{\\frac{2401}{25}\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  6     [/pre][/td][td][pre] 38     [/pre][/td][td][pre]324.209 [/pre][/td][/tr]",
            "[tr][td][pre][/pre]:``::|:[pre][/pre][/td][td][pre]65/77n       [/pre][/td][td][pre][/pre][latex]\\frac{2080}{2079}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre]  5    [/pre][/td][td][pre] -3    [/pre][/td][td][pre]  1    [/pre][/td][td][pre] -1    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         0.833¢[/pre][/td][td][pre] -3.051[/pre][/td][td][pre]  3.051[/pre][/td][td][pre]  3    [/pre][/td][td][pre] 13     [/pre][/td][td][pre][/pre][latex]\\{\\frac{77}{65}\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  4     [/pre][/td][td][pre] 36     [/pre][/td][td][pre]200.818 [/pre][/td][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]7/(5²⋅17)n   [/pre][/td][td][pre][/pre][latex]\\frac{1701}{1700}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre] -2    [/pre][/td][td][pre]  5    [/pre][/td][td][pre] -2    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  0    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         1.018¢[/pre][/td][td][pre]  4.937[/pre][/td][td][pre]  4.937[/pre][/td][td][pre]  5    [/pre][/td][td][pre] 17     [/pre][/td][td][pre][/pre][latex]\\{\\frac{425}{7}\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  4     [/pre][/td][td][pre] 34     [/pre][/td][td][pre]234.144 [/pre][/td][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]11⋅17/(5²⋅7)n[/pre][/td][td][pre][/pre][latex]\\frac{382976}{382725}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre] 11    [/pre][/td][td][pre] -7    [/pre][/td][td][pre] -2    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]  0    [/pre][/td][td][pre]  1    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         1.135¢[/pre][/td][td][pre] -7.070[/pre][/td][td][pre]  7.070[/pre][/td][td][pre]  7    [/pre][/td][td][pre] 17     [/pre][/td][td][pre][/pre][latex]\\{\\frac{187}{175}\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  5     [/pre][/td][td][pre] 45     [/pre][/td][td][pre]572.351 [/pre][/td][/tr]",
            "[tr][td][pre]     [/pre][/td][td][pre]1/(7²⋅11)n   [/pre][/td][td][pre][/pre][latex]\\frac{131072}{130977}[/latex][pre][/pre][/td][td][pre]    [[/pre][/td][td][pre] 17    [/pre][/td][td][pre] -5    [/pre][/td][td][pre]  0    [/pre][/td][td][pre] -2    [/pre][/td][td][pre] -1    [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]       [/pre][/td][td][pre]⟩[/pre][/td][td][pre]         1.255¢[/pre][/td][td][pre] -5.077[/pre][/td][td][pre]  5.077[/pre][/td][td][pre]  5    [/pre][/td][td][pre] 11     [/pre][/td][td][pre][/pre][latex]\\{539\\}_{\\scriptsize{2,3}}[/latex][pre][/pre][/td][td][pre]  3     [/pre][/td][td][pre] 25     [/pre][/td][td][pre] 82.347 [/pre][/td][/tr]",
            "[/table]",
            "",
        ] as Io[]
        expect(actual).toEqual(expected)
    })
})
