import {Aim, Ascii, Compatible, CoreName, CORES, Smiley, Unicode} from "../../../../../../src/sagittal/accidental"
import {Accent} from "../../../../../../src/sagittal/accidental/flacco"
import {Core} from "../../../../../../src/sagittal/accidental/symbol"
import {
    computeAccentGlyphExpectation,
    computeCompatibleGlyphExpectation,
    computeCoreGlyphExpectation,
} from "../../../../../helpers/src/sagittal/accidental/glyphExpectation"
import {GlyphExpectation} from "../../../../../helpers/src/sagittal/accidental/types"

describe("glyphs", (): void => {
    it("has the correct core glyphs and computes their IO correctly", (): void => {
        const cores = Object.entries(CORES) as Array<[CoreName, Core]>
        const coreGlyphExpectations = cores
            .map((core: [CoreName, Core]): GlyphExpectation => computeCoreGlyphExpectation(core))

        const expected: Array<GlyphExpectation> = [
            {
                name: CoreName.RIGHT_SCROLL_UP,
                unicode: "" as Unicode,
                ascii: "|(" as Ascii,
                smiley: ":|(:" as Smiley,
            },
            {
                name: CoreName.RIGHT_SCROLL_DOWN,
                unicode: "" as Unicode,
                ascii: "!(" as Ascii,
                smiley: ":!(:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_UP,
                unicode: "" as Unicode,
                ascii: "/|" as Ascii,
                smiley: ":/|:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!" as Ascii,
                smiley: ":\\!:" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_UP,
                unicode: "" as Unicode,
                ascii: "|)" as Ascii,
                smiley: ":|):" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_DOWN,
                unicode: "" as Unicode,
                ascii: "!)" as Ascii,
                smiley: ":!):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_UP,
                unicode: "" as Unicode,
                ascii: "//|" as Ascii,
                smiley: ":/ /|:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "\\\\!" as Ascii,
                smiley: ":\\ \\!:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_UP,
                unicode: "" as Unicode,
                ascii: "/|)" as Ascii,
                smiley: ":/|):" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!)" as Ascii,
                smiley: ":\\!):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_UP,
                unicode: "" as Unicode,
                ascii: "/|\\" as Ascii,
                smiley: ":/|\\:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!/" as Ascii,
                smiley: ":\\!/:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_ARC_UP,
                unicode: "" as Unicode,
                ascii: "(|)" as Ascii,
                smiley: ":(|):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_ARC_DOWN,
                unicode: "" as Unicode,
                ascii: "(!)" as Ascii,
                smiley: ":(!):" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BARB_UP,
                unicode: "" as Unicode,
                ascii: "(|\\" as Ascii,
                smiley: ":(|\\:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "(!/" as Ascii,
                smiley: ":(!/:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: ")||(" as Ascii,
                smiley: ":)||(:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!(" as Ascii,
                smiley: ":)!!(:" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "||)" as Ascii,
                smiley: ":||):" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!)" as Ascii,
                smiley: ":!!):" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "||\\" as Ascii,
                smiley: ":||\\:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!/" as Ascii,
                smiley: ":!!/:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "/||)" as Ascii,
                smiley: ":/||):" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!)" as Ascii,
                smiley: ":\\!!):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "/||\\" as Ascii,
                smiley: ":/||\\:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!/" as Ascii,
                smiley: ":\\!!/:" as Smiley,
            },
            {
                name: CoreName.RIGHT_SCROLL_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "|||(" as Ascii,
                smiley: ":|||(:" as Smiley,
            },
            {
                name: CoreName.RIGHT_SCROLL_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!!(" as Ascii,
                smiley: ":!!!(:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "/|||" as Ascii,
                smiley: ":/|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!!" as Ascii,
                smiley: ":\\!!!:" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "|||)" as Ascii,
                smiley: ":|||):" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!!)" as Ascii,
                smiley: ":!!!):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "//|||" as Ascii,
                smiley: ":/ /|||:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\\\!!!" as Ascii,
                smiley: ":\\ \\!!!:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "/|||)" as Ascii,
                smiley: ":/|||):" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!!)" as Ascii,
                smiley: ":\\!!!):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "/|||\\" as Ascii,
                smiley: ":/|||\\:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!!/" as Ascii,
                smiley: ":\\!!!/:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_ARC_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "(|||)" as Ascii,
                smiley: ":(|||):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_ARC_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!!)" as Ascii,
                smiley: ":(!!!):" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "(|||\\" as Ascii,
                smiley: ":(|||\\:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!!/" as Ascii,
                smiley: ":(!!!/:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_EX_UP,
                unicode: "" as Unicode,
                ascii: ")X(" as Ascii,
                smiley: ":)X(:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_EX_DOWN,
                unicode: "" as Unicode,
                ascii: ")Y(" as Ascii,
                smiley: ":)Y(:" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_EX_UP,
                unicode: "" as Unicode,
                ascii: "X)" as Ascii,
                smiley: ":X):" as Smiley,
            },
            {
                name: CoreName.RIGHT_ARC_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "Y)" as Ascii,
                smiley: ":Y):" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_EX_UP,
                unicode: "" as Unicode,
                ascii: "X\\" as Ascii,
                smiley: ":X\\:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "Y/" as Ascii,
                smiley: ":Y/:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_EX_UP,
                unicode: "" as Unicode,
                ascii: "/X)" as Ascii,
                smiley: ":/X):" as Smiley,
            },
            {
                name: CoreName.BARB_AND_ARC_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "\\Y)" as Ascii,
                smiley: ":\\Y):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_EX_UP,
                unicode: "" as Unicode,
                ascii: "/X\\" as Ascii,
                smiley: ":/X\\:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_BARB_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "\\Y/" as Ascii,
                smiley: ":\\Y/:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_UP,
                unicode: "" as Unicode,
                ascii: ")|(" as Ascii,
                smiley: ":)|(:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_DOWN,
                unicode: "" as Unicode,
                ascii: ")!(" as Ascii,
                smiley: ":)!(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_UP,
                unicode: "" as Unicode,
                ascii: "~|(" as Ascii,
                smiley: ":~|(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_DOWN,
                unicode: "" as Unicode,
                ascii: "~!(" as Ascii,
                smiley: ":~!(:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_UP,
                unicode: "" as Unicode,
                ascii: "|\\" as Ascii,
                smiley: ":|\\:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "!/" as Ascii,
                smiley: ":!/:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_UP,
                unicode: "" as Unicode,
                ascii: "(|" as Ascii,
                smiley: ":(|:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_DOWN,
                unicode: "" as Unicode,
                ascii: "(!" as Ascii,
                smiley: ":(!:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_UP,
                unicode: "" as Unicode,
                ascii: "(|(" as Ascii,
                smiley: ":(|(:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_DOWN,
                unicode: "" as Unicode,
                ascii: "(!(" as Ascii,
                smiley: ":(!(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "~||(" as Ascii,
                smiley: ":~||(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~!!(" as Ascii,
                smiley: ":~!!(:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: ")||~" as Ascii,
                smiley: ":)||~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!~" as Ascii,
                smiley: ":)!!~:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "/||" as Ascii,
                smiley: ":/||:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!" as Ascii,
                smiley: ":\\!!:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "(||(" as Ascii,
                smiley: ":(||(:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!(" as Ascii,
                smiley: ":(!!(:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "//||" as Ascii,
                smiley: ":/ /||:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\\\!!" as Ascii,
                smiley: ":\\ \\!!:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")|||(" as Ascii,
                smiley: ":)|||(:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_SCROLL_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!!(" as Ascii,
                smiley: ":)!!!(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "~|||(" as Ascii,
                smiley: ":~|||(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~!!!(" as Ascii,
                smiley: ":~!!!(:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "|||\\" as Ascii,
                smiley: ":|||\\:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!!/" as Ascii,
                smiley: ":!!!/:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "(|||" as Ascii,
                smiley: ":(|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!!" as Ascii,
                smiley: ":(!!!:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "(|||(" as Ascii,
                smiley: ":(|||(:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!!(" as Ascii,
                smiley: ":(!!!(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_EX_UP,
                unicode: "" as Unicode,
                ascii: "~X(" as Ascii,
                smiley: ":~X(:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_SCROLL_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "~Y(" as Ascii,
                smiley: ":~Y(:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_EX_UP,
                unicode: "" as Unicode,
                ascii: ")X~" as Ascii,
                smiley: ":)X~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_EX_DOWN,
                unicode: "" as Unicode,
                ascii: ")Y~" as Ascii,
                smiley: ":)Y~:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_EX_UP,
                unicode: "" as Unicode,
                ascii: "/X" as Ascii,
                smiley: ":/X:" as Smiley,
            },
            {
                name: CoreName.LEFT_BARB_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "\\Y" as Ascii,
                smiley: ":\\Y:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_EX_UP,
                unicode: "" as Unicode,
                ascii: "(X(" as Ascii,
                smiley: ":(X(:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_SCROLL_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "(Y(" as Ascii,
                smiley: ":(Y(:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_EX_UP,
                unicode: "" as Unicode,
                ascii: "//X" as Ascii,
                smiley: ":/ /X:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BARB_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "\\\\Y" as Ascii,
                smiley: ":\\ \\Y:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_UP,
                unicode: "" as Unicode,
                ascii: "|~" as Ascii,
                smiley: ":|~:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_DOWN,
                unicode: "" as Unicode,
                ascii: "!~" as Ascii,
                smiley: ":!~:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_UP,
                unicode: "" as Unicode,
                ascii: ")/|" as Ascii,
                smiley: ":)/|:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\!" as Ascii,
                smiley: ":)\\!:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_UP,
                unicode: "" as Unicode,
                ascii: "/|~" as Ascii,
                smiley: ":/|~:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!~" as Ascii,
                smiley: ":\\!~:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "||~" as Ascii,
                smiley: ":||~:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!~" as Ascii,
                smiley: ":!!~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: ")||)" as Ascii,
                smiley: ":)||):" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!)" as Ascii,
                smiley: ":)!!):" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "/||~" as Ascii,
                smiley: ":/||~:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!~" as Ascii,
                smiley: ":\\!!~:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "|||~" as Ascii,
                smiley: ":|||~:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!!~" as Ascii,
                smiley: ":!!!~:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")/|||" as Ascii,
                smiley: ":)/|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\!!!" as Ascii,
                smiley: ":)\\!!!:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "/|||~" as Ascii,
                smiley: ":/|||~:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "\\!!!~" as Ascii,
                smiley: ":\\!!!~:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_EX_UP,
                unicode: "" as Unicode,
                ascii: "X~" as Ascii,
                smiley: ":X~:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BOATHOOK_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "Y~" as Ascii,
                smiley: ":Y~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_EX_UP,
                unicode: "" as Unicode,
                ascii: ")X)" as Ascii,
                smiley: ":)X):" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_EX_DOWN,
                unicode: "" as Unicode,
                ascii: ")Y)" as Ascii,
                smiley: ":)Y):" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_EX_UP,
                unicode: "" as Unicode,
                ascii: "/X~" as Ascii,
                smiley: ":/X~:" as Smiley,
            },
            {
                name: CoreName.BARB_AND_BOATHOOK_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "\\Y~" as Ascii,
                smiley: ":\\Y~:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_UP,
                unicode: "" as Unicode,
                ascii: ")|" as Ascii,
                smiley: ":)|:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOWN,
                unicode: "" as Unicode,
                ascii: ")!" as Ascii,
                smiley: ":)!:" as Smiley,
            },
            {
                name: CoreName.LEFT_BOATHOOK_UP,
                unicode: "" as Unicode,
                ascii: "~|" as Ascii,
                smiley: ":~|:" as Smiley,
            },
            {
                name: CoreName.LEFT_BOATHOOK_DOWN,
                unicode: "" as Unicode,
                ascii: "~!" as Ascii,
                smiley: ":~!:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_UP,
                unicode: "" as Unicode,
                ascii: ")~|" as Ascii,
                smiley: ":)~|:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_DOWN,
                unicode: "" as Unicode,
                ascii: ")~!" as Ascii,
                smiley: ":)~!:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_UP,
                unicode: "" as Unicode,
                ascii: "~~|" as Ascii,
                smiley: ":~~|:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_DOWN,
                unicode: "" as Unicode,
                ascii: "~~!" as Ascii,
                smiley: ":~~!:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_UP,
                unicode: "" as Unicode,
                ascii: ")|~" as Ascii,
                smiley: ":)|~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_DOWN,
                unicode: "" as Unicode,
                ascii: ")!~" as Ascii,
                smiley: ":)!~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_UP,
                unicode: "" as Unicode,
                ascii: ")|)" as Ascii,
                smiley: ":)|):" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_DOWN,
                unicode: "" as Unicode,
                ascii: ")!)" as Ascii,
                smiley: ":)!):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_UP,
                unicode: "" as Unicode,
                ascii: "~|)" as Ascii,
                smiley: ":~|):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_DOWN,
                unicode: "" as Unicode,
                ascii: "~!)" as Ascii,
                smiley: ":~!):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_UP,
                unicode: "" as Unicode,
                ascii: "~|\\" as Ascii,
                smiley: ":~|\\:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "~!/" as Ascii,
                smiley: ":~!/:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_UP,
                unicode: "" as Unicode,
                ascii: ")//|" as Ascii,
                smiley: ":)/ /|:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\\\!" as Ascii,
                smiley: ":)\\ \\!:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_UP,
                unicode: "" as Unicode,
                ascii: "(|~" as Ascii,
                smiley: ":(|~:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_DOWN,
                unicode: "" as Unicode,
                ascii: "(!~" as Ascii,
                smiley: ":(!~:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_AND_BARB_UP,
                unicode: "" as Unicode,
                ascii: "(/|" as Ascii,
                smiley: ":(/|:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_AND_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "(\\!" as Ascii,
                smiley: ":(\\!:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_DOUBLE_BARB_UP,
                unicode: "" as Unicode,
                ascii: ")/|\\" as Ascii,
                smiley: ":)/|\\:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_DOUBLE_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\!/" as Ascii,
                smiley: ":)\\!/:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_AND_ARC_UP,
                unicode: "" as Unicode,
                ascii: "|\\)" as Ascii,
                smiley: ":|\\):" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_AND_ARC_DOWN,
                unicode: "" as Unicode,
                ascii: "!/)" as Ascii,
                smiley: ":!/):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_RIGHT_BARB_UP,
                unicode: "" as Unicode,
                ascii: "|\\\\" as Ascii,
                smiley: ":|\\ \\:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_RIGHT_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: "!//" as Ascii,
                smiley: ":!/ /:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_UP,
                unicode: "" as Unicode,
                ascii: ")|\\\\" as Ascii,
                smiley: ":)|\\ \\:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_DOWN,
                unicode: "" as Unicode,
                ascii: ")!//" as Ascii,
                smiley: ":)!/ /:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: ")~||" as Ascii,
                smiley: ":)~||:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")~!!" as Ascii,
                smiley: ":)~!!:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "~~||" as Ascii,
                smiley: ":~~||:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~~!!" as Ascii,
                smiley: ":~~!!:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: ")/||" as Ascii,
                smiley: ":)/||:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\!!" as Ascii,
                smiley: ":)\\!!:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "(||" as Ascii,
                smiley: ":(||:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!" as Ascii,
                smiley: ":(!!:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "~||)" as Ascii,
                smiley: ":~||):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~!!)" as Ascii,
                smiley: ":~!!):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "~||\\" as Ascii,
                smiley: ":~||\\:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~!!/" as Ascii,
                smiley: ":~!!/:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: ")//||" as Ascii,
                smiley: ":)/ /||:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\\\!!" as Ascii,
                smiley: ":)\\ \\!!:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_DOUBLE_UP,
                unicode: "" as Unicode,
                ascii: "(||~" as Ascii,
                smiley: ":(||~:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_DOUBLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!~" as Ascii,
                smiley: ":(!!~:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")|||" as Ascii,
                smiley: ":)|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!!" as Ascii,
                smiley: ":)!!!:" as Smiley,
            },
            {
                name: CoreName.LEFT_BOATHOOK_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "~|||" as Ascii,
                smiley: ":~|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_BOATHOOK_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~!!!" as Ascii,
                smiley: ":~!!!:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")~|||" as Ascii,
                smiley: ":)~|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")~!!!" as Ascii,
                smiley: ":)~!!!:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "~~|||" as Ascii,
                smiley: ":~~|||:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~~!!!" as Ascii,
                smiley: ":~~!!!:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")|||~" as Ascii,
                smiley: ":)|||~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_BOATHOOK_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!!~" as Ascii,
                smiley: ":)!!!~:" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")|||)" as Ascii,
                smiley: ":)|||):" as Smiley,
            },
            {
                name: CoreName.SCROLL_AND_ARC_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!!)" as Ascii,
                smiley: ":)!!!):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "~|||)" as Ascii,
                smiley: ":~|||):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~!!!)" as Ascii,
                smiley: ":~!!!):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "~|||\\" as Ascii,
                smiley: ":~|||\\:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "~!!!/" as Ascii,
                smiley: ":~!!!/:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")//|||" as Ascii,
                smiley: ":)/ /|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\\\!!!" as Ascii,
                smiley: ":)\\ \\!!!:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "(|||~" as Ascii,
                smiley: ":(|||~:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(!!!~" as Ascii,
                smiley: ":(!!!~:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_AND_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "(/|||" as Ascii,
                smiley: ":(/|||:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_AND_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "(\\!!!" as Ascii,
                smiley: ":(\\!!!:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")/|||\\" as Ascii,
                smiley: ":)/|||\\:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\!!!/" as Ascii,
                smiley: ":)\\!!!/:" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_AND_ARC_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "|||\\)" as Ascii,
                smiley: ":|||\\):" as Smiley,
            },
            {
                name: CoreName.RIGHT_BARB_AND_ARC_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!!/)" as Ascii,
                smiley: ":!!!/):" as Smiley,
            },
            {
                name: CoreName.DOUBLE_RIGHT_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: "|||\\\\" as Ascii,
                smiley: ":|||\\ \\:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_RIGHT_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: "!!!//" as Ascii,
                smiley: ":!!!/ /:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_TRIPLE_UP,
                unicode: "" as Unicode,
                ascii: ")|||\\\\" as Ascii,
                smiley: ":)|||\\ \\:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_TRIPLE_DOWN,
                unicode: "" as Unicode,
                ascii: ")!!!//" as Ascii,
                smiley: ":)!!!/ /:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_EX_UP,
                unicode: "" as Unicode,
                ascii: ")~X" as Ascii,
                smiley: ":)~X:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BOATHOOK_EX_DOWN,
                unicode: "" as Unicode,
                ascii: ")~Y" as Ascii,
                smiley: ":)~Y:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_EX_UP,
                unicode: "" as Unicode,
                ascii: "~~X" as Ascii,
                smiley: ":~~X:" as Smiley,
            },
            {
                name: CoreName.DOUBLE_LEFT_BOATHOOK_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "~~Y" as Ascii,
                smiley: ":~~Y:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_EX_UP,
                unicode: "" as Unicode,
                ascii: ")/X" as Ascii,
                smiley: ":)/X:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_AND_BARB_EX_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\Y" as Ascii,
                smiley: ":)\\Y:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_EX_UP,
                unicode: "" as Unicode,
                ascii: "(X" as Ascii,
                smiley: ":(X:" as Smiley,
            },
            {
                name: CoreName.LEFT_ARC_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "(Y" as Ascii,
                smiley: ":(Y:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_EX_UP,
                unicode: "" as Unicode,
                ascii: "~X)" as Ascii,
                smiley: ":~X):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_ARC_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "~Y)" as Ascii,
                smiley: ":~Y):" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_EX_UP,
                unicode: "" as Unicode,
                ascii: "~X\\" as Ascii,
                smiley: ":~X\\:" as Smiley,
            },
            {
                name: CoreName.BOATHOOK_AND_BARB_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "~Y/" as Ascii,
                smiley: ":~Y/:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_EX_UP,
                unicode: "" as Unicode,
                ascii: ")//X" as Ascii,
                smiley: ":)/ /X:" as Smiley,
            },
            {
                name: CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_EX_DOWN,
                unicode: "" as Unicode,
                ascii: ")\\\\Y" as Ascii,
                smiley: ":)\\ \\Y:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_EX_UP,
                unicode: "" as Unicode,
                ascii: "(X~" as Ascii,
                smiley: ":(X~:" as Smiley,
            },
            {
                name: CoreName.ARC_AND_BOATHOOK_EX_DOWN,
                unicode: "" as Unicode,
                ascii: "(Y~" as Ascii,
                smiley: ":(Y~:" as Smiley,
            },
            {
                name: CoreName.BARE_SHAFT_UP,
                unicode: "" as Unicode,
                ascii: "|" as Ascii,
                smiley: ":|:" as Smiley,
            },
            {
                name: CoreName.BARE_SHAFT_DOWN,
                unicode: "" as Unicode,
                ascii: "!" as Ascii,
                smiley: ":!:" as Smiley,
            },
        ]
        expect(coreGlyphExpectations).toEqual(expected)
    })

    it("has the correct accent glyphs and computes their IO correctly (assuming aim is up, since it's redundant to check both aims)", (): void => {
        const accents = Object.values(Accent) as Accent[]
        const accentGlyphExpectations = accents
            .map((accent: Accent): GlyphExpectation => computeAccentGlyphExpectation(accent, Aim.UP))

        const expected: Array<GlyphExpectation> = [
            {
                name: Accent.TICK_WITH,
                unicode: "" as Unicode,
                ascii: "'" as Ascii,
                smiley: ":':" as Smiley,
            },
            {
                name: Accent.TICK_AGAINST,
                unicode: "" as Unicode,
                ascii: "." as Ascii,
                smiley: ":.:" as Smiley,
            },
            {
                name: Accent.WING_WITH,
                unicode: "" as Unicode,
                ascii: "`" as Ascii,
                smiley: ":`:" as Smiley,
            },
            {
                name: Accent.WING_AGAINST,
                unicode: "" as Unicode,
                ascii: "," as Ascii,
                smiley: ":,:" as Smiley,
            },
            {
                name: Accent.BIRD_WITH,
                unicode: "" as Unicode,
                ascii: "``" as Ascii,
                smiley: ":``:" as Smiley,
            },
            {
                name: Accent.BIRD_AGAINST,
                unicode: "" as Unicode,
                ascii: ",," as Ascii,
                smiley: ":,,:" as Smiley,
            },
        ]
        expect(accentGlyphExpectations).toEqual(expected)
    })

    it("has the correct Sagittal-compatible glyphs and computes their IO correctly", (): void => {
        const compatibles = Object.values(Compatible) as Compatible[]
        const compatibleGlyphExpectations = compatibles
            .map((compatible: Compatible): GlyphExpectation => computeCompatibleGlyphExpectation(compatible))

        const expected: GlyphExpectation[] = [
            {
                name: Compatible.STEIN_SEMISHARP,
                unicode: "" as Unicode,
                ascii: ">" as Ascii,
                smiley: ":>:" as Smiley,
            },
            {
                name: Compatible.STEIN_SEMIFLAT,
                unicode: "" as Unicode,
                ascii: "<" as Ascii,
                smiley: ":<:" as Smiley,
            },
            {
                name: Compatible.STEIN_SESQUISHARP,
                unicode: "" as Unicode,
                ascii: ">#" as Ascii,
                smiley: ":>#:" as Smiley,
            },
            {
                name: Compatible.ZIMMERMANN_SESQUIFLAT,
                unicode: "" as Unicode,
                ascii: "<b" as Ascii,
                smiley: ":<b:" as Smiley,
            },
            {
                name: Compatible.WILSON_PLUS,
                unicode: "" as Unicode,
                ascii: "+" as Ascii,
                smiley: ":+:" as Smiley,
            },
            {
                name: Compatible.WILSON_MINUS,
                unicode: "" as Unicode,
                ascii: "-" as Ascii,
                smiley: ":-:" as Smiley,
            },
            {
                name: Compatible.NATURAL,
                unicode: "" as Unicode,
                ascii: "|//|" as Ascii,
                smiley: ":h:" as Smiley,
            },
            {
                name: Compatible.SHARP,
                unicode: "" as Unicode,
                ascii: "#" as Ascii,
                smiley: ":#:" as Smiley,
            },
            {
                name: Compatible.FLAT,
                unicode: "" as Unicode,
                ascii: "b" as Ascii,
                smiley: ":b:" as Smiley,
            },
            {
                name: Compatible.DOUBLE_SHARP,
                unicode: "" as Unicode,
                ascii: "x" as Ascii,
                smiley: ":x:" as Smiley,
            },
            {
                name: Compatible.DOUBLE_FLAT,
                unicode: "" as Unicode,
                ascii: "bb" as Ascii,
                smiley: ":bb:" as Smiley,
            },
        ]
        expect(compatibleGlyphExpectations).toEqual(expected)
    })
})
