import {Cents, Comma, computePitchFromCents, Scamon} from "../../../../../src/general"
import {computeSizeCategory} from "../../../../../src/sagittal/ji/name/sizeCategory"

describe("computeSizeCategory", (): void => {
    it("returns the correct size category for the pitch size", (): void => {
        expect(computeSizeCategory(computePitchFromCents(0 as Cents) as Scamon as Comma)).toBe("u")
        expect(computeSizeCategory(computePitchFromCents(1 as Cents) as Scamon as Comma)).toBe("n")
        expect(computeSizeCategory(computePitchFromCents(2 as Cents) as Scamon as Comma)).toBe("s")
        expect(computeSizeCategory(computePitchFromCents(10 as Cents) as Scamon as Comma)).toBe("k")
        expect(computeSizeCategory(computePitchFromCents(20 as Cents) as Scamon as Comma)).toBe("C")
        expect(computeSizeCategory(computePitchFromCents(40 as Cents) as Scamon as Comma)).toBe("S")
        expect(computeSizeCategory(computePitchFromCents(50 as Cents) as Scamon as Comma)).toBe("M")
        expect(computeSizeCategory(computePitchFromCents(60 as Cents) as Scamon as Comma)).toBe("L")
        expect(computeSizeCategory(computePitchFromCents(80 as Cents) as Scamon as Comma)).toBe("SS")
        expect(computeSizeCategory(computePitchFromCents(100 as Cents) as Scamon as Comma)).toBe("MS")
        expect(computeSizeCategory(computePitchFromCents(110 as Cents) as Scamon as Comma)).toBe("LS")
        expect(computeSizeCategory(computePitchFromCents(115 as Cents) as Scamon as Comma)).toBe("A")
        expect(computeSizeCategory(computePitchFromCents(117 as Cents) as Scamon as Comma)).toBe("s+A")
        expect(computeSizeCategory(computePitchFromCents(120 as Cents) as Scamon as Comma)).toBe("k+A")
        expect(computeSizeCategory(computePitchFromCents(135 as Cents) as Scamon as Comma)).toBe("C+A")
        expect(computeSizeCategory(computePitchFromCents(155 as Cents) as Scamon as Comma)).toBe("S+A")
        expect(computeSizeCategory(computePitchFromCents(165 as Cents) as Scamon as Comma)).toBe("M+A")
        expect(computeSizeCategory(computePitchFromCents(175 as Cents) as Scamon as Comma)).toBe("L+A")
        expect(computeSizeCategory(computePitchFromCents(190 as Cents) as Scamon as Comma)).toBe("SS+A")
        expect(computeSizeCategory(computePitchFromCents(200 as Cents) as Scamon as Comma)).toBe("MS+A")
        expect(computeSizeCategory(computePitchFromCents(220 as Cents) as Scamon as Comma)).toBe("LS+A")
        expect(computeSizeCategory(computePitchFromCents(227 as Cents) as Scamon as Comma)).toBe("A+A")
    })

    it("works when not abbreviated", (): void => {
        expect(computeSizeCategory(computePitchFromCents(0 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("unison")
        expect(computeSizeCategory(computePitchFromCents(1 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("schismina")
        expect(computeSizeCategory(computePitchFromCents(2 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("schisma")
        expect(computeSizeCategory(computePitchFromCents(10 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("kleisma")
        expect(computeSizeCategory(computePitchFromCents(20 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Comma")
        expect(computeSizeCategory(computePitchFromCents(40 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Small-Diesis")
        expect(computeSizeCategory(computePitchFromCents(50 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Medium-Diesis")
        expect(computeSizeCategory(computePitchFromCents(60 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Large-Diesis")
        expect(computeSizeCategory(computePitchFromCents(80 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Small-Semitone")
        expect(computeSizeCategory(computePitchFromCents(100 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Medium-Semitone")
        expect(computeSizeCategory(computePitchFromCents(110 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Large-Semitone")
        expect(computeSizeCategory(computePitchFromCents(115 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Apotome")
        expect(computeSizeCategory(computePitchFromCents(117 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("schisma-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(120 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("kleisma-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(135 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Comma-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(155 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Small-Diesis-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(165 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Medium-Diesis-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(175 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Large-Diesis-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(190 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Small-Semitone-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(200 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Medium-Semitone-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(220 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("Large-Semitone-plus-Apotome")
        expect(computeSizeCategory(computePitchFromCents(227 as Cents) as Scamon as Comma, {abbreviated: false}))
            .toBe("double-Apotome")
    })

    it("throws an error if the size category of an pitch which is too big is requested", (): void => {
        expect((): void => {
            computeSizeCategory(computePitchFromCents(230 as Cents) as Scamon as Comma)
        }).toThrowError("230.000¢ is beyond the maximum size category's bounds.")
    })
})
