import { Integer } from "../math"

const ACCURACY_THRESHOLD = 6 as Integer

const ARRAY_EXTENSION_BASE: unknown[] = []
const OBJECT_EXTENSION_BASE: Object = {}

const ZERO_ONE_INDEX_DIFF = 1

const MAX_JAVASCRIPT_INTEGER_VALUE = 9007199254740991

export {
    ARRAY_EXTENSION_BASE,
    OBJECT_EXTENSION_BASE,
    ACCURACY_THRESHOLD,
    ZERO_ONE_INDEX_DIFF,
    MAX_JAVASCRIPT_INTEGER_VALUE,
}
