import {Flag} from "../flacco"
import {Aim, Core, CoreName, Shafts} from "./types"

const CORES: Record<CoreName, Core> = {
    [CoreName.RIGHT_SCROLL_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        right: [Flag.SCROLL],
    },
    [CoreName.RIGHT_SCROLL_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        right: [Flag.SCROLL],
    },
    [CoreName.LEFT_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
    },
    [CoreName.LEFT_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
    },
    [CoreName.RIGHT_ARC_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        right: [Flag.ARC],
    },
    [CoreName.RIGHT_ARC_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_LEFT_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.DOUBLE_LEFT_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.BARB_AND_ARC_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.BARB_AND_ARC_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_ARC_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_ARC_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.ARC],
    },
    [CoreName.ARC_AND_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.BARB],
    },
    [CoreName.ARC_AND_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_SCROLL_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.DOUBLE_SCROLL_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.RIGHT_ARC_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        right: [Flag.ARC],
    },
    [CoreName.RIGHT_ARC_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        right: [Flag.ARC],
    },
    [CoreName.RIGHT_BARB_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        right: [Flag.BARB],
    },
    [CoreName.RIGHT_BARB_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        right: [Flag.BARB],
    },
    [CoreName.BARB_AND_ARC_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.BARB_AND_ARC_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_BARB_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_BARB_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.RIGHT_SCROLL_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        right: [Flag.SCROLL],
    },
    [CoreName.RIGHT_SCROLL_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        right: [Flag.SCROLL],
    },
    [CoreName.LEFT_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
    },
    [CoreName.LEFT_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
    },
    [CoreName.RIGHT_ARC_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        right: [Flag.ARC],
    },
    [CoreName.RIGHT_ARC_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_LEFT_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.DOUBLE_LEFT_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.BARB_AND_ARC_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.BARB_AND_ARC_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_ARC_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_ARC_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.ARC],
    },
    [CoreName.ARC_AND_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.BARB],
    },
    [CoreName.ARC_AND_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_SCROLL_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.DOUBLE_SCROLL_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.RIGHT_ARC_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        right: [Flag.ARC],
    },
    [CoreName.RIGHT_ARC_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        right: [Flag.ARC],
    },
    [CoreName.RIGHT_BARB_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        right: [Flag.BARB],
    },
    [CoreName.RIGHT_BARB_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        right: [Flag.BARB],
    },
    [CoreName.BARB_AND_ARC_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.BARB_AND_ARC_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BARB],
        right: [Flag.ARC],
    },
    [CoreName.DOUBLE_BARB_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_BARB_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.DOUBLE_SCROLL_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.DOUBLE_SCROLL_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.RIGHT_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        right: [Flag.BARB],
    },
    [CoreName.RIGHT_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        right: [Flag.BARB],
    },
    [CoreName.LEFT_ARC_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
    },
    [CoreName.LEFT_ARC_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
    },
    [CoreName.ARC_AND_SCROLL_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.ARC_AND_SCROLL_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.SCROLL_AND_BOATHOOK_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_BOATHOOK_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_BARB_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
    },
    [CoreName.LEFT_BARB_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
    },
    [CoreName.ARC_AND_SCROLL_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.ARC_AND_SCROLL_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.DOUBLE_LEFT_BARB_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.DOUBLE_LEFT_BARB_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.DOUBLE_SCROLL_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.DOUBLE_SCROLL_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.RIGHT_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        right: [Flag.BARB],
    },
    [CoreName.RIGHT_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        right: [Flag.BARB],
    },
    [CoreName.LEFT_ARC_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
    },
    [CoreName.LEFT_ARC_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
    },
    [CoreName.ARC_AND_SCROLL_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.ARC_AND_SCROLL_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.BOATHOOK_AND_SCROLL_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK],
        right: [Flag.SCROLL],
    },
    [CoreName.SCROLL_AND_BOATHOOK_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_BOATHOOK_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_BARB_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BARB],
    },
    [CoreName.LEFT_BARB_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BARB],
    },
    [CoreName.ARC_AND_SCROLL_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.ARC_AND_SCROLL_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.ARC],
        right: [Flag.SCROLL],
    },
    [CoreName.DOUBLE_LEFT_BARB_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.DOUBLE_LEFT_BARB_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BARB, Flag.BARB],
    },
    [CoreName.RIGHT_BOATHOOK_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        right: [Flag.BOATHOOK],
    },
    [CoreName.RIGHT_BOATHOOK_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.BARB_AND_BOATHOOK_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.BARB_AND_BOATHOOK_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.RIGHT_BOATHOOK_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        right: [Flag.BOATHOOK],
    },
    [CoreName.RIGHT_BOATHOOK_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_ARC_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.SCROLL_AND_ARC_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.BARB_AND_BOATHOOK_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.BARB_AND_BOATHOOK_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.RIGHT_BOATHOOK_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        right: [Flag.BOATHOOK],
    },
    [CoreName.RIGHT_BOATHOOK_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.BARB_AND_BOATHOOK_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.BARB_AND_BOATHOOK_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.RIGHT_BOATHOOK_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        right: [Flag.BOATHOOK],
    },
    [CoreName.RIGHT_BOATHOOK_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_ARC_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.SCROLL_AND_ARC_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.BARB_AND_BOATHOOK_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.BARB_AND_BOATHOOK_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BARB],
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
    },
    [CoreName.LEFT_SCROLL_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
    },
    [CoreName.LEFT_BOATHOOK_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_BOATHOOK_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_BOATHOOK_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_BOATHOOK_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_ARC_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.SCROLL_AND_ARC_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.BOATHOOK_AND_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.ARC_AND_BOATHOOK_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.ARC_AND_BOATHOOK_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_ARC_AND_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC, Flag.BARB],
    },
    [CoreName.LEFT_ARC_AND_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.ARC, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_DOUBLE_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_DOUBLE_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL, Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.RIGHT_BARB_AND_ARC_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        right: [Flag.BARB, Flag.ARC],
    },
    [CoreName.RIGHT_BARB_AND_ARC_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        right: [Flag.BARB, Flag.ARC],
    },
    [CoreName.DOUBLE_RIGHT_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.DOUBLE_RIGHT_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
        left: [Flag.SCROLL],
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.LEFT_ARC_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.ARC],
    },
    [CoreName.LEFT_ARC_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_BARB_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.BOATHOOK_AND_BARB_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.ARC_AND_BOATHOOK_DOUBLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.DOUBLE,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.ARC_AND_BOATHOOK_DOUBLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.DOUBLE,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
    },
    [CoreName.LEFT_SCROLL_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
    },
    [CoreName.LEFT_BOATHOOK_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_BOATHOOK_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_BOATHOOK_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_BOATHOOK_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.BOATHOOK],
    },
    [CoreName.SCROLL_AND_ARC_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.SCROLL_AND_ARC_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.BOATHOOK_AND_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.ARC_AND_BOATHOOK_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.ARC_AND_BOATHOOK_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.LEFT_ARC_AND_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC, Flag.BARB],
    },
    [CoreName.LEFT_ARC_AND_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.ARC, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL, Flag.BARB],
        right: [Flag.BARB],
    },
    [CoreName.RIGHT_BARB_AND_ARC_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        right: [Flag.BARB, Flag.ARC],
    },
    [CoreName.RIGHT_BARB_AND_ARC_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        right: [Flag.BARB, Flag.ARC],
    },
    [CoreName.DOUBLE_RIGHT_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.DOUBLE_RIGHT_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_TRIPLE_UP]: {
        aim: Aim.UP,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_RIGHT_BARB_TRIPLE_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.TRIPLE,
        left: [Flag.SCROLL],
        right: [Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BOATHOOK_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.SCROLL, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.DOUBLE_LEFT_BOATHOOK_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK, Flag.BOATHOOK],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_AND_BARB_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.SCROLL, Flag.BARB],
    },
    [CoreName.LEFT_ARC_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.ARC],
    },
    [CoreName.LEFT_ARC_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_ARC_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK],
        right: [Flag.ARC],
    },
    [CoreName.BOATHOOK_AND_BARB_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.BOATHOOK_AND_BARB_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.BOATHOOK],
        right: [Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.LEFT_SCROLL_DOUBLE_LEFT_BARB_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.SCROLL, Flag.BARB, Flag.BARB],
    },
    [CoreName.ARC_AND_BOATHOOK_EX_UP]: {
        aim: Aim.UP,
        shafts: Shafts.EX,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.ARC_AND_BOATHOOK_EX_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.EX,
        left: [Flag.ARC],
        right: [Flag.BOATHOOK],
    },
    [CoreName.BARE_SHAFT_UP]: {
        aim: Aim.UP,
        shafts: Shafts.SINGLE,
    },
    [CoreName.BARE_SHAFT_DOWN]: {
        aim: Aim.DOWN,
        shafts: Shafts.SINGLE,
    },
}

export {
    CORES,
}
