const SYMBOLS = [
    {
        id: 0,
        ascii: "|",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 0,
        primaryComma: {
            monzo: [],
            position: 0.0000000000000,
        },
        elements: [],
    },
    {
        id: 1,
        ascii: "`|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 1,
        primaryComma: {
            monzo: [12, -2, -1, -1, 0, -1],
            position: 0.42271616595482,
        },
        elements: ["`|"],
    },
    {
        id: 2,
        ascii: "``|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 2,
        primaryComma: {
            monzo: [5, -3, 1, -1, -1, 1],
            position: 0.83252420410159,
        },
        elements: ["``|"],
    },
    {
        id: 3,
        ascii: ".)|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 3,
        primaryComma: {
            monzo: [6, -5, -1, 0, 0, 0, 0, 1],
            position: 1.4242979405308,
        },
        elements: [".|", ")|"],
    },
    {
        id: 4,
        ascii: "'|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 4,
        primaryComma: {
            monzo: [-15, 8, 1],
            position: 1.95372078793416,
        },
        elements: ["'|"],
    },
    {
        id: 5,
        ascii: "`'|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 5,
        primaryComma: {
            monzo: [-3, 6, 0, -1, 0, -1],
            position: 2.37643695388898,
        },
        elements: ["`|", "'|"],
    },
    {
        id: 6,
        ascii: ",)|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 6,
        primaryComma: {
            monzo: [-8, 10, -4, -1, 0, 0, 0, 1],
            position: 2.98226285771248,
        },
        elements: [",|", ")|"],
    },
    {
        id: 7,
        ascii: ")|",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 7,
        primaryComma: {
            monzo: [-9, 3, 0, 0, 0, 0, 0, 1],
            position: 3.37801872846485,
        },
        elements: [")|"],
    },
    {
        id: 8,
        ascii: "`)|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 8,
        primaryComma: {
            monzo: [-3, 2, -1, 2, -1],
            position: 3.93015843943305,
        },
        elements: ["`|", ")|"],
    },
    {
        id: 9,
        ascii: "``)|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 9,
        primaryComma: {
            monzo: [-7, -1, 1, 1, 1],
            position: 4.50256183332916,
        },
        elements: ["``|", ")|"],
    },
    {
        id: 10,
        ascii: ",,|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 10,
        primaryComma: {
            monzo: [5, -3, 0, 0, 1, -1],
            position: 4.92527799928397,
        },
        elements: [",,|", "|("],
    },
    {
        id: 11,
        ascii: ",|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 11,
        primaryComma: {
            monzo: [-11, 6, 0, 0, -1, 0, 0, 0, 0, 0, 1],
            position: 5.44763529181809,
        },
        elements: [",|", "|("],
    },
    {
        id: 12,
        ascii: "|(",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 12,
        primaryComma: {
            monzo: [10, -6, 1, -1],
            position: 5.7578022033852,
        },
        elements: ["|("],
    },
    {
        id: 13,
        ascii: "`|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 13,
        primaryComma: {
            monzo: [5, -7, -1, 3],
            position: 6.47899948482794,
        },
        elements: ["`|", "|("],
    },
    {
        id: 14,
        ascii: ".~|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 14,
        primaryComma: {
            monzo: [8, -1, -1, 0, 0, 0, -1],
            position: 6.77587576937045,
        },
        elements: [".|", "~|"],
    },
    {
        id: 15,
        ascii: ",'|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 15,
        primaryComma: {
            monzo: [-4, 9, -2, -2],
            position: 7.31576712056731,
        },
        elements: [",|", "'|", "|("],
    },
    {
        id: 16,
        ascii: "'|(",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 16,
        primaryComma: {
            monzo: [-5, 2, 2, -1],
            position: 7.71152299131971,
        },
        elements: ["'|", "|("],
    },
    {
        id: 17,
        ascii: ",~|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 17,
        primaryComma: {
            monzo: [-10, 1, 0, 3],
            position: 8.43272027276221,
        },
        elements: [",|", "~|"],
    },
    {
        id: 18,
        ascii: "~|",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 18,
        primaryComma: {
            monzo: [-7, 7, 0, 0, 0, 0, -1],
            position: 8.72959655730475,
        },
        elements: ["~|"],
    },
    {
        id: 19,
        ascii: ",)|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 19,
        primaryComma: {
            monzo: [-17, 2, 0, 0, 4],
            position: 9.18177118980167,
        },
        elements: [",|", ")|", "|("],
    },
    {
        id: 20,
        ascii: ")|(",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 20,
        primaryComma: {
            monzo: [7, -4, 0, 1, -1],
            position: 9.6879606428187,
        },
        elements: [")|", "|("],
    },
    {
        id: 21,
        ascii: "`)|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 21,
        primaryComma: {
            monzo: [3, -7, 2, 0, 1],
            position: 10.2603640367144,
        },
        elements: ["`|", ")|", "|("],
    },
    {
        id: 22,
        ascii: "``)|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 22,
        primaryComma: {
            monzo: [-13, 7, 0, 2, 0, -1],
            position: 10.8091572266510,
        },
        elements: ["``|", ")|", "|("],
    },
    {
        id: 23,
        ascii: ",')|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 23,
        primaryComma: {
            monzo: [21, -5, -2, -3],
            position: 11.1198485360183,
        },
        elements: [",|", "'|", ")|", "|("],
    },
    {
        id: 24,
        ascii: "')|(",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 24,
        primaryComma: {
            monzo: [-8, 4, 1, 1, -1],
            position: 11.6416814307528,
        },
        elements: ["'|", ")|", "|("],
    },
    {
        id: 25,
        ascii: ")~|",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 25,
        primaryComma: {
            monzo: [4, 2, 0, 0, -1, -1],
            position: 12.0643975967077,
        },
        elements: [")|", "~|"],
    },
    {
        id: 26,
        ascii: ".~|(",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 26,
        primaryComma: {
            monzo: [3, -3, -1, 0, 0, 0, 1],
            position: 12.7766930394100,
        },
        elements: [".|", "~|", "|("],
    },
    {
        id: 27,
        ascii: "`.~|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 27,
        primaryComma: {
            monzo: [9, -5, 0, 0, 1, 0, 0, 0, -1],
            position: 13.2685907694041,
        },
        elements: ["`|", ".|", "~|", "|("],
    },
    {
        id: 28,
        ascii: ",,~|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 28,
        primaryComma: {
            monzo: [1, 2, -3, 1],
            position: 13.7947666053953,
        },
        elements: [",,|", "~|", "|("],
    },
    {
        id: 29,
        ascii: ",~|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 29,
        primaryComma: {
            monzo: [0, -5, 1, 2],
            position: 14.1905224761475,
        },
        elements: [",|", "~|", "|("],
    },
    {
        id: 30,
        ascii: "~|(",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 30,
        primaryComma: {
            monzo: [-12, 5, 0, 0, 0, 0, 1],
            position: 14.7304138273444,
        },
        elements: ["~|", "|("],
    },
    {
        id: 31,
        ascii: "`~|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 31,
        primaryComma: {
            monzo: [2, -4, 0, -1, 1, 1],
            position: 15.1996942033926,
        },
        elements: ["`|", "~|", "|("],
    },
    {
        id: 32,
        ascii: ",,|~",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 32,
        primaryComma: {
            monzo: [-14, 10, -2, 1],
            position: 15.7484873933296,
        },
        elements: [",,|", "|~"],
    },
    {
        id: 33,
        ascii: ",|~",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 33,
        primaryComma: {
            monzo: [-15, 3, 2, 2],
            position: 16.1442432640817,
        },
        elements: [",|", "|~"],
    },
    {
        id: 34,
        ascii: "|~",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 34,
        primaryComma: {
            monzo: [5, -6, 0, 0, 0, 0, 0, 0, 1],
            position: 16.5443420760908,
        },
        elements: ["|~"],
    },
    {
        id: 35,
        ascii: "`|~",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 35,
        primaryComma: {
            monzo: [9, -1, 0, 0, 0, -2],
            position: 16.9896755959915,
        },
        elements: ["`|", "|~"],
    },
    {
        id: 36,
        ascii: "~~|",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 36,
        primaryComma: {
            monzo: [-1, 2, 0, -2, 1],
            position: 17.5761311572815,
        },
        elements: ["~|", "~|"],
    },
    {
        id: 37,
        ascii: "`~~|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 37,
        primaryComma: {
            monzo: [-8, 6, 0, 0, 1, 0, 0, 0, 0, 0, -1],
            position: 18.0123750928310,
        },
        elements: ["`|", "~|", "~|"],
    },
    {
        id: 38,
        ascii: "``~~|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 38,
        primaryComma: {
            monzo: [13, -9, 0, -1, 0, 0, 1],
            position: 18.5344952427957,
        },
        elements: ["``|", "~|", "~|"],
    },
    {
        id: 39,
        ascii: ",./|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 39,
        primaryComma: {
            monzo: [-1, -2, -1, 1, 0, 1],
            position: 19.1298526428258,
        },
        elements: [",|", ".|", "/|"],
    },
    {
        id: 40,
        ascii: "./|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 40,
        primaryComma: {
            monzo: [11, -4, -2],
            position: 19.5525688087807,
        },
        elements: [".|", "/|"],
    },
    {
        id: 41,
        ascii: ")|~",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 41,
        primaryComma: {
            monzo: [-10, 9, 0, 0, 0, 0, 0, -1],
            position: 20.0819916561843,
        },
        elements: [")|", "|~"],
    },
    {
        id: 42,
        ascii: ",,/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 42,
        primaryComma: {
            monzo: [8, 0, 0, 0, -1, 0, 0, 0, -1],
            position: 20.4077103668277,
        },
        elements: [",,|", "/|"],
    },
    {
        id: 43,
        ascii: ",/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 43,
        primaryComma: {
            monzo: [-16, 6, 0, 1, 0, 1],
            position: 21.0835734307600,
        },
        elements: [",|", "/|"],
    },
    {
        id: 44,
        ascii: "/|",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 44,
        primaryComma: {
            monzo: [-4, 4, -1],
            position: 21.5062895967148,
        },
        elements: ["/|"],
    },
    {
        id: 45,
        ascii: "`/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 45,
        primaryComma: {
            monzo: [-5, -3, 3, 1],
            position: 21.9020454674670,
        },
        elements: ["`|", "/|"],
    },
    {
        id: 46,
        ascii: "``/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 46,
        primaryComma: {
            monzo: [7, -5, 2, 0, 0, -1],
            position: 22.3247616334221,
        },
        elements: ["``|", "/|"],
    },
    {
        id: 47,
        ascii: ".)/|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 47,
        primaryComma: {
            monzo: [2, -1, -2, 0, 0, 0, 0, 1],
            position: 22.9305875372457,
        },
        elements: [".|", ")|", "/|"],
    },
    {
        id: 48,
        ascii: "'/|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 48,
        primaryComma: {
            monzo: [-19, 12],
            position: 23.4600103846490,
        },
        elements: ["'|", "/|"],
    },
    {
        id: 49,
        ascii: "`'/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 49,
        primaryComma: {
            monzo: [-20, 5, 4, 1],
            position: 23.8557662554013,
        },
        elements: ["`|", "'|", "/|"],
    },
    {
        id: 50,
        ascii: ",,)/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 49.56756901073000,
        primaryComma: {
            monzo: [4, -5, -1, 1, 1],
            position: 24.0551306421097,
        },
        elements: [",,|", ")|", "/|"],
    },
    {
        id: 51,
        ascii: ",)/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 50,
        primaryComma: {
            monzo: [-8, 3, 3, 0, 0, -1],
            position: 24.2784824213563,
        },
        elements: [",|", ")|", "/|"],
    },
    {
        id: 52,
        ascii: ")/|",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 51,
        primaryComma: {
            monzo: [-13, 7, -1, 0, 0, 0, 0, 1],
            position: 24.8843083251798,
        },
        elements: [")|", "/|"],
    },
    {
        id: 53,
        ascii: ",.|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 51.45864857210600,
        primaryComma: {
            monzo: [9, -8, 0, 0, 0, 1],
            position: 24.8876548462113,
        },
        elements: [",|", ".|", "|)"],
    },
    {
        id: 54,
        ascii: ".|)",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 52,
        primaryComma: {
            monzo: [21, -10, -1, -1],
            position: 25.3103710121659,
        },
        elements: [".|", "|)"],
    },
    {
        id: 55,
        ascii: "`.|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 53,
        primaryComma: {
            monzo: [-11, 3, 0, 1, 1],
            position: 26.0088514300439,
        },
        elements: ["`|", ".|", "|)"],
    },
    {
        id: 56,
        ascii: ",,|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 54,
        primaryComma: {
            monzo: [1, 1, -1, 0, 1, -1],
            position: 26.4315675959986,
        },
        elements: [",,|", "|)"],
    },
    {
        id: 57,
        ascii: ",|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 55,
        primaryComma: {
            monzo: [-6, 0, 1, 0, 0, 1],
            position: 26.8413756341454,
        },
        elements: [",|", "|)"],
    },
    {
        id: 58,
        ascii: "|)",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 56,
        primaryComma: {
            monzo: [6, -2, 0, -1],
            position: 27.2640918001001,
        },
        elements: ["|)"],
    },
    {
        id: 59,
        ascii: "`|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 57,
        primaryComma: {
            monzo: [5, -9, 4],
            position: 27.6598476708525,
        },
        elements: ["`|", "|)"],
    },
    {
        id: 60,
        ascii: "``|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 58,
        primaryComma: {
            monzo: [-14, 9, 0, 0, 1, -1],
            position: 28.3852883839327,
        },
        elements: ["``|", "|)"],
    },
    {
        id: 61,
        ascii: ",'|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 59,
        primaryComma: {
            monzo: [-21, 8, 2, 0, 0, 1],
            position: 28.7950964220796,
        },
        elements: [",|", "'|", "|)"],
    },
    {
        id: 62,
        ascii: "'|)",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 60,
        primaryComma: {
            monzo: [-9, 6, 1, -1],
            position: 29.2178125880342,
        },
        elements: ["'|", "|)"],
    },
    {
        id: 63,
        ascii: "`'|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 61,
        primaryComma: {
            monzo: [-10, -1, 5],
            position: 29.6135684587868,
        },
        elements: ["`|", "'|", "|)"],
    },
    {
        id: 64,
        ascii: ",)|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 62,
        primaryComma: {
            monzo: [5, -5, 1, 0, -1, 0, 1],
            position: 30.1761766735484,
        },
        elements: [",|", ")|", "|)"],
    },
    {
        id: 65,
        ascii: ")|)",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 63,
        primaryComma: {
            monzo: [-3, 1, 0, -1, 0, 0, 0, 1],
            position: 30.6421105285650,
        },
        elements: [")|", "|)"],
    },
    {
        id: 66,
        ascii: ".(|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 64,
        primaryComma: {
            monzo: [3, 0, -1, 1, -1],
            position: 31.1942502395332,
        },
        elements: [".|", "(|"],
    },
    {
        id: 67,
        ascii: "|\\",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 65,
        primaryComma: {
            monzo: [-1, -3, 1, 0, 1],
            position: 31.7666536334294,
        },
        elements: ["|\\"],
    },
    {
        id: 68,
        ascii: "`|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 66,
        primaryComma: {
            monzo: [11, -5, 0, -1, 1, -1],
            position: 32.1893697993842,
        },
        elements: ["`|", "|\\"],
    },
    {
        id: 69,
        ascii: ",(|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 67,
        primaryComma: {
            monzo: [-4, 1, 3, 0, 0, 0, 0, 0, -1],
            position: 32.6217951914765,
        },
        elements: [",|", "(|"],
    },
    {
        id: 70,
        ascii: "(|",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 68,
        primaryComma: {
            monzo: [-12, 8, 0, 1, -1],
            position: 33.1479710274675,
        },
        elements: ["(|"],
    },
    {
        id: 71,
        ascii: "`(|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 69,
        primaryComma: {
            monzo: [2, -1, 0, 0, 0, 1, -1],
            position: 33.6172514035158,
        },
        elements: ["`|", "(|"],
    },
    {
        id: 72,
        ascii: "``(|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 70,
        primaryComma: {
            monzo: [-1, 1, -2, 0, 0, 0, 1],
            position: 34.2829826361251,
        },
        elements: ["``|", "(|"],
    },
    {
        id: 73,
        ascii: ",'(|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 71,
        primaryComma: {
            monzo: [2, 2, 0, 1, 0, -1, 0, -1],
            position: 34.6952302982867,
        },
        elements: [",|", "'|", "(|"],
    },
    {
        id: 74,
        ascii: "'(|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 72,
        primaryComma: {
            monzo: [1, 0, 2, -2],
            position: 34.9756147914198,
        },
        elements: ["'|", "(|"],
    },
    {
        id: 75,
        ascii: ",~|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 72.40486810762850,
        primaryComma: {
            monzo: [3, -5, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            position: 35.2605681373132,
        },
        elements: [",|", "~|", "|)"],
    },
    {
        id: 76,
        ascii: "~|)",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 73,
        primaryComma: {
            monzo: [-4, -1, 0, 2],
            position: 35.6968120728623,
        },
        elements: ["~|", "|)"],
    },
    {
        id: 77,
        ascii: "`~|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 74,
        primaryComma: {
            monzo: [-16, 9, -1, 0, 0, 0, 1],
            position: 36.2367034240592,
        },
        elements: ["`|", "~|", "|)"],
    },
    {
        id: 79,
        ascii: ",.(|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 75,
        primaryComma: {
            monzo: [-10, 7, 0, 0, 1, 0, 0, 0, -1],
            position: 36.7286011540533,
        },
        elements: [",|", ".|", "(|", "|("],
    },
    {
        id: 80,
        ascii: ".(|(",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 76,
        primaryComma: {
            monzo: [13, -6, 0, 0, -1],
            position: 36.9520524429189,
        },
        elements: [".|", "(|", "|("],
    },
    {
        id: 81,
        ascii: "'~|)",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 77,
        primaryComma: {
            monzo: [-19, 7, 1, 2],
            position: 37.6505328607966,
        },
        elements: ["'|", "~|", "|)"],
    },
    {
        id: 82,
        ascii: "/|~",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 78,
        primaryComma: {
            monzo: [1, -2, -1, 0, 0, 0, 0, 0, 1],
            position: 38.0506316728057,
        },
        elements: ["/|", "|~"],
    },
    {
        id: 83,
        ascii: ",,(|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 78.39014554523920,
        primaryComma: {
            monzo: [-7, 5, 0, 1, 0, -1],
            position: 38.0732490267513,
        },
        elements: [",,|", "(|", "|("],
    },
    {
        id: 84,
        ascii: ",(|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 79,
        primaryComma: {
            monzo: [7, -4, 0, 0, 1, 0, -1],
            position: 38.5425294027997,
        },
        elements: [",|", "(|", "|("],
    },
    {
        id: 85,
        ascii: "(|(",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 80,
        primaryComma: {
            monzo: [-2, 2, 1, 0, -1],
            position: 38.9057732308529,
        },
        elements: ["(|", "|("],
    },
    {
        id: 86,
        ascii: "`(|(",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 81,
        primaryComma: {
            monzo: [10, 0, 0, -1, -1, -1],
            position: 39.3284893968078,
        },
        elements: ["`|", "(|", "|("],
    },
    {
        id: 87,
        ascii: "~|\\",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 82,
        primaryComma: {
            monzo: [-14, 6, 0, 0, 0, 0, 0, 0, 1],
            position: 40.0043524607400,
        },
        elements: ["~|", "|\\"],
    },
    {
        id: 88,
        ascii: ",.//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 83,
        primaryComma: {
            monzo: [-5, 2, -2, 1, 0, 1],
            position: 40.6361422395406,
        },
        elements: [",|", ".|", "/|", "/|"],
    },
    {
        id: 89,
        ascii: ".//|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 84,
        primaryComma: {
            monzo: [7, 0, -3],
            position: 41.0588584054956,
        },
        elements: [".|", "/|", "/|"],
    },
    {
        id: 90,
        ascii: "`.//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 85,
        primaryComma: {
            monzo: [6, -7, 1, 1],
            position: 41.4546142762478,
        },
        elements: ["`|", ".|", "/|", "/|"],
    },
    {
        id: 91,
        ascii: ",,//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 86,
        primaryComma: {
            monzo: [-6, 3, 0, -1, 0, 0, 1],
            position: 41.9945056274446,
        },
        elements: [",,|", "/|", "/|"],
    },
    {
        id: 92,
        ascii: ",//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 87,
        primaryComma: {
            monzo: [-20, 10, -1, 1, 0, 1],
            position: 42.5898630274750,
        },
        elements: [",|", "/|", "/|"],
    },
    {
        id: 93,
        ascii: "//|",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 88,
        primaryComma: {
            monzo: [-8, 8, -2],
            position: 43.0125791934297,
        },
        elements: ["/|", "/|"],
    },
    {
        id: 94,
        ascii: "`//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 89,
        primaryComma: {
            monzo: [-9, 1, 2, 1],
            position: 43.4083350641820,
        },
        elements: ["`|", "/|", "/|"],
    },
    {
        id: 95,
        ascii: "``//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 90,
        primaryComma: {
            monzo: [3, -1, 1, 0, 0, -1],
            position: 43.8310512301367,
        },
        elements: ["``|", "/|", "/|"],
    },
    {
        id: 96,
        ascii: ",'//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 91,
        primaryComma: {
            monzo: [-11, 6, 0, 2, 0, 0, -1],
            position: 44.4264086301669,
        },
        elements: [",|", "'|", "/|", "/|"],
    },
    {
        id: 97,
        ascii: "'//|",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 92,
        primaryComma: {
            monzo: [-1, 1, 0, 0, 0, 1, 0, -1],
            position: 44.9696465023956,
        },
        elements: ["'|", "/|", "/|"],
    },
    {
        id: 98,
        ascii: ",,)//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 93,
        primaryComma: {
            monzo: [0, -1, -2, 1, 1],
            position: 45.5614202388245,
        },
        elements: [",,|", ")|", "/|", "/|"],
    },
    {
        id: 99,
        ascii: ",)//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 94,
        primaryComma: {
            monzo: [-12, 7, 2, 0, 0, -1],
            position: 45.7847720180709,
        },
        elements: [",|", ")|", "/|", "/|"],
    },
    {
        id: 100,
        ascii: ")//|",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 95,
        primaryComma: {
            monzo: [5, -4, -1, 0, 0, 1],
            position: 46.3939444429262,
        },
        elements: [")|", "/|", "/|"],
    },
    {
        id: 101,
        ascii: "`)//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 96,
        primaryComma: {
            monzo: [17, -6, -2, -1],
            position: 46.8166606088810,
        },
        elements: ["`|", ")|", "/|", "/|"],
    },
    {
        id: 102,
        ascii: "``)//|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 97,
        primaryComma: {
            monzo: [-2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            position: 47.4340370239647,
        },
        elements: ["``|", ")|", "/|", "/|"],
    },
    {
        id: 103,
        ascii: ",,/|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 98,
        primaryComma: {
            monzo: [-3, 5, -2, 0, 1, -1],
            position: 47.9378571927136,
        },
        elements: [",,|", "/|", "|)"],
    },
    {
        id: 104,
        ascii: ",/|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 99,
        primaryComma: {
            monzo: [-10, 4, 0, 0, 0, 1],
            position: 48.3476652308603,
        },
        elements: [",|", "/|", "|)"],
    },
    {
        id: 105,
        ascii: "/|)",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 100,
        primaryComma: {
            monzo: [2, 2, -1, -1],
            position: 48.7703813968149,
        },
        elements: ["/|", "|)"],
    },
    {
        id: 106,
        ascii: "`/|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 101,
        primaryComma: {
            monzo: [1, -5, 3],
            position: 49.1661372675673,
        },
        elements: ["`|", "/|", "|)"],
    },
    {
        id: 107,
        ascii: "(|~",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 102,
        primaryComma: {
            monzo: [4, -2, 0, 0, 1, 0, 0, -1],
            position: 49.8949245016792,
        },
        elements: ["(|", "|~"],
    },
    {
        id: 108,
        ascii: ",'/|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 103,
        primaryComma: {
            monzo: [-25, 12, 1, 0, 0, 1],
            position: 50.3013860187944,
        },
        elements: [",|", "'|", "/|", "|)"],
    },
    {
        id: 109,
        ascii: "'/|)",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 104,
        primaryComma: {
            monzo: [-13, 10, 0, -1],
            position: 50.7241021847494,
        },
        elements: ["'|", "/|", "|)"],
    },
    {
        id: 110,
        ascii: "`'/|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 105,
        primaryComma: {
            monzo: [-14, 3, 4],
            position: 51.1198580555015,
        },
        elements: ["`|", "'|", "/|", "|)"],
    },
    {
        id: 111,
        ascii: "./|\\",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 105.57202549664000,
        primaryComma: {
            monzo: [10, -7, -1, 0, 1],
            position: 51.3192224422099,
        },
        elements: [".|", "/|", "|\\"],
    },
    {
        id: 112,
        ascii: "`./|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 106,
        primaryComma: {
            monzo: [1, -1, 0, 0, -1, 0, 1],
            position: 51.6824662702631,
        },
        elements: ["`|", ".|", "/|", "|\\"],
    },
    {
        id: 113,
        ascii: ",,/|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 107,
        primaryComma: {
            monzo: [7, -3, 1, 0, 0, 0, 0, 0, -1],
            position: 52.1743640002570,
        },
        elements: [",,|", "/|", "|\\"],
    },
    {
        id: 114,
        ascii: ",/|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 108,
        primaryComma: {
            monzo: [-1, 4, -2, 1, -1],
            position: 52.7005398362484,
        },
        elements: [",|", "/|", "|\\"],
    },
    {
        id: 115,
        ascii: "/|\\",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 109,
        primaryComma: {
            monzo: [-5, 1, 0, 0, 1],
            position: 53.2729432301441,
        },
        elements: ["/|", "|\\"],
    },
    {
        id: 116,
        ascii: "`/|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 110,
        primaryComma: {
            monzo: [-14, 7, 1, 0, -1, 0, 1],
            position: 53.6361870581975,
        },
        elements: ["`|", "/|", "|\\"],
    },
    {
        id: 117,
        ascii: ",(/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 111,
        primaryComma: {
            monzo: [0, -2, 1, -1, 0, 1],
            position: 54.1054674342458,
        },
        elements: [",|", "(|", "/|"],
    },
    {
        id: 118,
        ascii: "(/|",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 112,
        primaryComma: {
            monzo: [12, -4, 0, -2],
            position: 54.5281836002006,
        },
        elements: ["(|", "/|"],
    },
    {
        id: 119,
        ascii: "`(/|",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 113,
        primaryComma: {
            monzo: [5, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            position: 54.9644275357497,
        },
        elements: ["`|", "(|", "/|"],
    },
    {
        id: 120,
        ascii: "'/|\\",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 113.45170990741700,
        primaryComma: {
            monzo: [-20, 9, 1, 0, 1],
            position: 55.2266640180783,
        },
        elements: ["'|", "/|", "|\\"],
    },
    {
        id: 121,
        ascii: "`'/|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 114,
        primaryComma: {
            monzo: [-8, 7, 0, -1, 1, -1],
            position: 55.6493801840332,
        },
        elements: ["`|", "'|", "/|", "|\\"],
    },
    {
        id: 122,
        ascii: ",)/|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 115,
        primaryComma: {
            monzo: [-6, -2, 1, 1, 0, 0, 1],
            position: 56.1850281035923,
        },
        elements: [",|", ")|", "/|", "|\\"],
    },
    {
        id: 123,
        ascii: ")/|\\",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 116,
        primaryComma: {
            monzo: [-3, 4, 1, -2],
            position: 56.4819043881346,
        },
        elements: [")|", "/|", "|\\"],
    },
    {
        id: 124,
        ascii: "`)/|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 117,
        primaryComma: {
            monzo: [-8, 3, -1, 2],
            position: 57.2031016695774,
        },
        elements: ["`|", ")|", "/|", "|\\"],
    },
    {
        id: 125,
        ascii: "``)/|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 118,
        primaryComma: {
            monzo: [-5, 9, -1, -1, 0, 0, -1],
            position: 57.4999779541197,
        },
        elements: ["``|", ")|", "/|", "|\\"],
    },
    {
        id: 126,
        ascii: ",.(|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 119,
        primaryComma: {
            monzo: [-3, 0, 0, 1, -1, 1],
            position: 58.0356258736789,
        },
        elements: [",|", ".|", "(|", "|)"],
    },
    {
        id: 127,
        ascii: ".(|)",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 120,
        primaryComma: {
            monzo: [9, -2, -1, 0, -1],
            position: 58.4583420396336,
        },
        elements: [".|", "(|", "|)"],
    },
    {
        id: 128,
        ascii: ",|\\)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 120.70032964758700,
        primaryComma: {
            monzo: [-16, 7, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            position: 58.7205785219622,
        },
        elements: [",|", "|\\", "|)"],
    },
    {
        id: 129,
        ascii: "|\\)",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 121,
        primaryComma: {
            monzo: [-23, 11, 0, 2],
            position: 59.1568224575114,
        },
        elements: ["|\\", "|)"],
    },
    {
        id: 130,
        ascii: "`|\\)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 122,
        primaryComma: {
            monzo: [-11, 9, -1, 1, 0, -1],
            position: 59.5795386234664,
        },
        elements: ["`|", "|\\", "|)"],
    },
    {
        id: 131,
        ascii: ",(|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 123,
        primaryComma: {
            monzo: [3, 0, -1, 0, 1, 0, -1],
            position: 60.0488189995148,
        },
        elements: [",|", "(|", "|)"],
    },
    {
        id: 132,
        ascii: "(|)",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 124,
        primaryComma: {
            monzo: [-6, 6, 0, 0, -1],
            position: 60.4120628275676,
        },
        elements: ["(|", "|)"],
    },
    {
        id: 133,
        ascii: "`(|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 125,
        primaryComma: {
            monzo: [-10, 3, 2, -1, 1],
            position: 60.9844662214638,
        },
        elements: ["`|", "(|", "|)"],
    },
    {
        id: 134,
        ascii: "``(|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 126,
        primaryComma: {
            monzo: [-18, 10, -1, 0, 0, 0, 0, 0, 1],
            position: 61.5106420574550,
        },
        elements: ["``|", "(|", "|)"],
    },
    {
        id: 135,
        ascii: ",'(|)",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 127,
        primaryComma: {
            monzo: [-12, 8, 0, 0, 1, 0, -1],
            position: 62.0025397874486,
        },
        elements: [",|", "'|", "(|", "|)"],
    },
    {
        id: 136,
        ascii: "'(|)",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 128,
        primaryComma: {
            monzo: [-21, 14, 1, 0, -1],
            position: 62.3657836155021,
        },
        elements: ["'|", "(|", "|)"],
    },
    {
        id: 137,
        ascii: ",.(|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 128.58001405836400,
        primaryComma: {
            monzo: [3, 4, -4],
            position: 62.5651480022103,
        },
        elements: [",|", ".|", "(|", "|\\"],
    },
    {
        id: 138,
        ascii: ".(|\\",
        unicode: "",
        introducingLevel: "ULTRA",
        mina: 129,
        primaryComma: {
            monzo: [2, -3, 0, 1],
            position: 62.9609038729626,
        },
        elements: [".|", "(|", "|\\"],
    },
    {
        id: 139,
        ascii: "`.(|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 130,
        primaryComma: {
            monzo: [14, -5, -1, 0, 0, -1],
            position: 63.3836200389176,
        },
        elements: ["`|", ".|", "(|", "|\\"],
    },
    {
        id: 140,
        ascii: "|\\\\",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 131,
        primaryComma: {
            monzo: [-15, 9, 0, 0, -1, 0, 0, 1],
            position: 63.7900815560325,
        },
        elements: ["|\\", "|\\"],
    },
    {
        id: 141,
        ascii: ",(|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 132,
        primaryComma: {
            monzo: [-12, 12, -3],
            position: 64.5188687901447,
        },
        elements: [",|", "(|", "|\\"],
    },
    {
        id: 142,
        ascii: "(|\\",
        unicode: "",
        introducingLevel: "MEDIUM",
        mina: 133,
        primaryComma: {
            monzo: [-13, 5, 1, 1],
            position: 64.9146246608968,
        },
        elements: ["(|", "|\\"],
    },
    {
        id: 143,
        ascii: "`(|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 134,
        primaryComma: {
            monzo: [-1, 3, 0, 0, 0, -1],
            position: 65.3373408268518,
        },
        elements: ["`|", "(|", "|\\"],
    },
    {
        id: 144,
        ascii: "``(|\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 135,
        primaryComma: {
            monzo: [-8, 2, 2, 0, -1, 1],
            position: 65.7471488649985,
        },
        elements: ["``|", "(|", "|\\"],
    },
    {
        id: 145,
        ascii: ",,)|\\\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 136,
        primaryComma: {
            monzo: [-9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
            position: 66.2509690337472,
        },
        elements: [",,|", ")|", "|\\", "|\\"],
    },
    {
        id: 146,
        ascii: ",)|\\\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 137,
        primaryComma: {
            monzo: [-28, 13, 2, 1],
            position: 66.8683454488310,
        },
        elements: [",|", ")|", "|\\", "|\\"],
    },
    {
        id: 147,
        ascii: ")|\\\\",
        unicode: "",
        introducingLevel: "HIGH",
        mina: 138,
        primaryComma: {
            monzo: [-16, 11, 1, 0, 0, -1],
            position: 67.2910616147857,
        },
        elements: [")|", "|\\", "|\\"],
    },
    {
        id: 148,
        ascii: "`)|\\\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 139,
        primaryComma: {
            monzo: [1, 0, -2, 0, 0, 1],
            position: 67.9002340396410,
        },
        elements: ["`|", ")|", "|\\", "|\\"],
    },
    {
        id: 149,
        ascii: "``)|\\\\",
        unicode: "",
        introducingLevel: "EXTREME",
        mina: 140,
        primaryComma: {
            monzo: [-11, 8, 2, -1, -1],
            position: 68.1235858189,
        },
        elements: ["``|", ")|", "|\\", "|\\"],
    },
]

module.exports = {
    SYMBOLS,
}
