import { Level, Mina, SagittalSymbol, SymbolLongAscii, SymbolUnicode } from "./types"
import { Cents, Id } from "../../utilities/types"
import { Monzo } from "../../utilities/comma/types"

const SYMBOLS: SagittalSymbol[] = [
    {
        id: 0 as Id<SagittalSymbol>,
        ascii: "|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 0 as Mina,
        primaryComma: {
            monzo: [] as unknown as Monzo,
            position: 0.0000000000000 as Cents,
        },
        elements: [] as SymbolLongAscii[],
    },
    {
        id: 1 as Id<SagittalSymbol>,
        ascii: "`|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 1 as Mina,
        primaryComma: {
            monzo: [12, -2, -1, -1, 0, -1] as Monzo,
            position: 0.42271616595482 as Cents,
        },
        elements: ["`|"] as SymbolLongAscii[],
    },
    {
        id: 2 as Id<SagittalSymbol>,
        ascii: "``|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 2 as Mina,
        primaryComma: {
            monzo: [5, -3, 1, -1, -1, 1] as Monzo,
            position: 0.83252420410159 as Cents,
        },
        elements: ["``|"] as SymbolLongAscii[],
    },
    {
        id: 3 as Id<SagittalSymbol>,
        ascii: ".)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 3 as Mina,
        primaryComma: {
            monzo: [6, -5, -1, 0, 0, 0, 0, 1] as Monzo,
            position: 1.4242979405308 as Cents,
        },
        elements: [".|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 4 as Id<SagittalSymbol>,
        ascii: "'|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 4 as Mina,
        primaryComma: {
            monzo: [-15, 8, 1] as Monzo,
            position: 1.95372078793416 as Cents,
        },
        elements: ["'|"] as SymbolLongAscii[],
    },
    {
        id: 5 as Id<SagittalSymbol>,
        ascii: "`'|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 5 as Mina,
        primaryComma: {
            monzo: [-3, 6, 0, -1, 0, -1] as Monzo,
            position: 2.37643695388898 as Cents,
        },
        elements: ["`|", "'|"] as SymbolLongAscii[],
    },
    {
        id: 6 as Id<SagittalSymbol>,
        ascii: ",)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 6 as Mina,
        primaryComma: {
            monzo: [-8, 10, -4, -1, 0, 0, 0, 1] as Monzo,
            position: 2.98226285771248 as Cents,
        },
        elements: [",|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 7 as Id<SagittalSymbol>,
        ascii: ")|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 7 as Mina,
        primaryComma: {
            monzo: [-9, 3, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 3.37801872846485 as Cents,
        },
        elements: [")|"] as SymbolLongAscii[],
    },
    {
        id: 8 as Id<SagittalSymbol>,
        ascii: "`)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 8 as Mina,
        primaryComma: {
            monzo: [-3, 2, -1, 2, -1] as Monzo,
            position: 3.93015843943305 as Cents,
        },
        elements: ["`|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 9 as Id<SagittalSymbol>,
        ascii: "``)|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 9 as Mina,
        primaryComma: {
            monzo: [-7, -1, 1, 1, 1] as Monzo,
            position: 4.50256183332916 as Cents,
        },
        elements: ["``|", ")|"] as SymbolLongAscii[],
    },
    {
        id: 10 as Id<SagittalSymbol>,
        ascii: ",,|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 10 as Mina,
        primaryComma: {
            monzo: [5, -3, 0, 0, 1, -1] as Monzo,
            position: 4.92527799928397 as Cents,
        },
        elements: [",,|", "|("] as SymbolLongAscii[],
    },
    {
        id: 11 as Id<SagittalSymbol>,
        ascii: ",|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 11 as Mina,
        primaryComma: {
            monzo: [-11, 6, 0, 0, -1, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 5.44763529181809 as Cents,
        },
        elements: [",|", "|("] as SymbolLongAscii[],
    },
    {
        id: 12 as Id<SagittalSymbol>,
        ascii: "|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 12 as Mina,
        primaryComma: {
            monzo: [10, -6, 1, -1] as Monzo,
            position: 5.7578022033852 as Cents,
        },
        elements: ["|("] as SymbolLongAscii[],
    },
    {
        id: 13 as Id<SagittalSymbol>,
        ascii: "`|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 13 as Mina,
        primaryComma: {
            monzo: [5, -7, -1, 3] as Monzo,
            position: 6.47899948482794 as Cents,
        },
        elements: ["`|", "|("] as SymbolLongAscii[],
    },
    {
        id: 14 as Id<SagittalSymbol>,
        ascii: ".~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 14 as Mina,
        primaryComma: {
            monzo: [8, -1, -1, 0, 0, 0, -1] as Monzo,
            position: 6.77587576937045 as Cents,
        },
        elements: [".|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 15 as Id<SagittalSymbol>,
        ascii: ",'|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 15 as Mina,
        primaryComma: {
            monzo: [-4, 9, -2, -2] as Monzo,
            position: 7.31576712056731 as Cents,
        },
        elements: [",|", "'|", "|("] as SymbolLongAscii[],
    },
    {
        id: 16 as Id<SagittalSymbol>,
        ascii: "'|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 16 as Mina,
        primaryComma: {
            monzo: [-5, 2, 2, -1] as Monzo,
            position: 7.71152299131971 as Cents,
        },
        elements: ["'|", "|("] as SymbolLongAscii[],
    },
    {
        id: 17 as Id<SagittalSymbol>,
        ascii: ",~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 17 as Mina,
        primaryComma: {
            monzo: [-10, 1, 0, 3] as Monzo,
            position: 8.43272027276221 as Cents,
        },
        elements: [",|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 18 as Id<SagittalSymbol>,
        ascii: "~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 18 as Mina,
        primaryComma: {
            monzo: [-7, 7, 0, 0, 0, 0, -1] as Monzo,
            position: 8.72959655730475 as Cents,
        },
        elements: ["~|"] as SymbolLongAscii[],
    },
    {
        id: 19 as Id<SagittalSymbol>,
        ascii: ",)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 19 as Mina,
        primaryComma: {
            monzo: [-17, 2, 0, 0, 4] as Monzo,
            position: 9.18177118980167 as Cents,
        },
        elements: [",|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 20 as Id<SagittalSymbol>,
        ascii: ")|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 20 as Mina,
        primaryComma: {
            monzo: [7, -4, 0, 1, -1] as Monzo,
            position: 9.6879606428187 as Cents,
        },
        elements: [")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 21 as Id<SagittalSymbol>,
        ascii: "`)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 21 as Mina,
        primaryComma: {
            monzo: [3, -7, 2, 0, 1] as Monzo,
            position: 10.2603640367144 as Cents,
        },
        elements: ["`|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 22 as Id<SagittalSymbol>,
        ascii: "``)|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 22 as Mina,
        primaryComma: {
            monzo: [-13, 7, 0, 2, 0, -1] as Monzo,
            position: 10.8091572266510 as Cents,
        },
        elements: ["``|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 23 as Id<SagittalSymbol>,
        ascii: ",')|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 23 as Mina,
        primaryComma: {
            monzo: [21, -5, -2, -3] as Monzo,
            position: 11.1198485360183 as Cents,
        },
        elements: [",|", "'|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 24 as Id<SagittalSymbol>,
        ascii: "')|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 24 as Mina,
        primaryComma: {
            monzo: [-8, 4, 1, 1, -1] as Monzo,
            position: 11.6416814307528 as Cents,
        },
        elements: ["'|", ")|", "|("] as SymbolLongAscii[],
    },
    {
        id: 25 as Id<SagittalSymbol>,
        ascii: ")~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 25 as Mina,
        primaryComma: {
            monzo: [4, 2, 0, 0, -1, -1] as Monzo,
            position: 12.0643975967077 as Cents,
        },
        elements: [")|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 26 as Id<SagittalSymbol>,
        ascii: ".~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 26 as Mina,
        primaryComma: {
            monzo: [3, -3, -1, 0, 0, 0, 1] as Monzo,
            position: 12.7766930394100 as Cents,
        },
        elements: [".|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 27 as Id<SagittalSymbol>,
        ascii: "`.~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 27 as Mina,
        primaryComma: {
            monzo: [9, -5, 0, 0, 1, 0, 0, 0, -1] as Monzo,
            position: 13.2685907694041 as Cents,
        },
        elements: ["`|", ".|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 28 as Id<SagittalSymbol>,
        ascii: ",,~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 28 as Mina,
        primaryComma: {
            monzo: [1, 2, -3, 1] as Monzo,
            position: 13.7947666053953 as Cents,
        },
        elements: [",,|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 29 as Id<SagittalSymbol>,
        ascii: ",~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 29 as Mina,
        primaryComma: {
            monzo: [0, -5, 1, 2] as Monzo,
            position: 14.1905224761475 as Cents,
        },
        elements: [",|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 30 as Id<SagittalSymbol>,
        ascii: "~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 30 as Mina,
        primaryComma: {
            monzo: [-12, 5, 0, 0, 0, 0, 1] as Monzo,
            position: 14.7304138273444 as Cents,
        },
        elements: ["~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 31 as Id<SagittalSymbol>,
        ascii: "`~|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 31 as Mina,
        primaryComma: {
            monzo: [2, -4, 0, -1, 1, 1] as Monzo,
            position: 15.1996942033926 as Cents,
        },
        elements: ["`|", "~|", "|("] as SymbolLongAscii[],
    },
    {
        id: 32 as Id<SagittalSymbol>,
        ascii: ",,|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 32 as Mina,
        primaryComma: {
            monzo: [-14, 10, -2, 1] as Monzo,
            position: 15.7484873933296 as Cents,
        },
        elements: [",,|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 33 as Id<SagittalSymbol>,
        ascii: ",|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 33 as Mina,
        primaryComma: {
            monzo: [-15, 3, 2, 2] as Monzo,
            position: 16.1442432640817 as Cents,
        },
        elements: [",|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 34 as Id<SagittalSymbol>,
        ascii: "|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 34 as Mina,
        primaryComma: {
            monzo: [5, -6, 0, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 16.5443420760908 as Cents,
        },
        elements: ["|~"] as SymbolLongAscii[],
    },
    {
        id: 35 as Id<SagittalSymbol>,
        ascii: "`|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 35 as Mina,
        primaryComma: {
            monzo: [9, -1, 0, 0, 0, -2] as Monzo,
            position: 16.9896755959915 as Cents,
        },
        elements: ["`|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 36 as Id<SagittalSymbol>,
        ascii: "~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 36 as Mina,
        primaryComma: {
            monzo: [-1, 2, 0, -2, 1] as Monzo,
            position: 17.5761311572815 as Cents,
        },
        elements: ["~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 37 as Id<SagittalSymbol>,
        ascii: "`~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 37 as Mina,
        primaryComma: {
            monzo: [-8, 6, 0, 0, 1, 0, 0, 0, 0, 0, -1] as Monzo,
            position: 18.0123750928310 as Cents,
        },
        elements: ["`|", "~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 38 as Id<SagittalSymbol>,
        ascii: "``~~|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 38 as Mina,
        primaryComma: {
            monzo: [13, -9, 0, -1, 0, 0, 1] as Monzo,
            position: 18.5344952427957 as Cents,
        },
        elements: ["``|", "~|", "~|"] as SymbolLongAscii[],
    },
    {
        id: 39 as Id<SagittalSymbol>,
        ascii: ",./|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 39 as Mina,
        primaryComma: {
            monzo: [-1, -2, -1, 1, 0, 1] as Monzo,
            position: 19.1298526428258 as Cents,
        },
        elements: [",|", ".|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 40 as Id<SagittalSymbol>,
        ascii: "./|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 40 as Mina,
        primaryComma: {
            monzo: [11, -4, -2] as Monzo,
            position: 19.5525688087807 as Cents,
        },
        elements: [".|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 41 as Id<SagittalSymbol>,
        ascii: ")|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 41 as Mina,
        primaryComma: {
            monzo: [-10, 9, 0, 0, 0, 0, 0, -1] as Monzo,
            position: 20.0819916561843 as Cents,
        },
        elements: [")|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 42 as Id<SagittalSymbol>,
        ascii: ",,/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 42 as Mina,
        primaryComma: {
            monzo: [8, 0, 0, 0, -1, 0, 0, 0, -1] as Monzo,
            position: 20.4077103668277 as Cents,
        },
        elements: [",,|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 43 as Id<SagittalSymbol>,
        ascii: ",/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 43 as Mina,
        primaryComma: {
            monzo: [-16, 6, 0, 1, 0, 1] as Monzo,
            position: 21.0835734307600 as Cents,
        },
        elements: [",|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 44 as Id<SagittalSymbol>,
        ascii: "/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 44 as Mina,
        primaryComma: {
            monzo: [-4, 4, -1] as Monzo,
            position: 21.5062895967148 as Cents,
        },
        elements: ["/|"] as SymbolLongAscii[],
    },
    {
        id: 45 as Id<SagittalSymbol>,
        ascii: "`/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 45 as Mina,
        primaryComma: {
            monzo: [-5, -3, 3, 1] as Monzo,
            position: 21.9020454674670 as Cents,
        },
        elements: ["`|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 46 as Id<SagittalSymbol>,
        ascii: "``/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 46 as Mina,
        primaryComma: {
            monzo: [7, -5, 2, 0, 0, -1] as Monzo,
            position: 22.3247616334221 as Cents,
        },
        elements: ["``|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 47 as Id<SagittalSymbol>,
        ascii: ".)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 47 as Mina,
        primaryComma: {
            monzo: [2, -1, -2, 0, 0, 0, 0, 1] as Monzo,
            position: 22.9305875372457 as Cents,
        },
        elements: [".|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 48 as Id<SagittalSymbol>,
        ascii: "'/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 48 as Mina,
        primaryComma: {
            monzo: [-19, 12] as Monzo,
            position: 23.4600103846490 as Cents,
        },
        elements: ["'|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 49 as Id<SagittalSymbol>,
        ascii: "`'/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 49 as Mina,
        primaryComma: {
            monzo: [-20, 5, 4, 1] as Monzo,
            position: 23.8557662554013 as Cents,
        },
        elements: ["`|", "'|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 50 as Id<SagittalSymbol>,
        ascii: ",,)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 49.56756901073000 as Mina,
        primaryComma: {
            monzo: [4, -5, -1, 1, 1] as Monzo,
            position: 24.0551306421097 as Cents,
        },
        elements: [",,|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 51 as Id<SagittalSymbol>,
        ascii: ",)/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 50 as Mina,
        primaryComma: {
            monzo: [-8, 3, 3, 0, 0, -1] as Monzo,
            position: 24.2784824213563 as Cents,
        },
        elements: [",|", ")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 52 as Id<SagittalSymbol>,
        ascii: ")/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 51 as Mina,
        primaryComma: {
            monzo: [-13, 7, -1, 0, 0, 0, 0, 1] as Monzo,
            position: 24.8843083251798 as Cents,
        },
        elements: [")|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 53 as Id<SagittalSymbol>,
        ascii: ",.|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 51.45864857210600 as Mina,
        primaryComma: {
            monzo: [9, -8, 0, 0, 0, 1] as Monzo,
            position: 24.8876548462113 as Cents,
        },
        elements: [",|", ".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 54 as Id<SagittalSymbol>,
        ascii: ".|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 52 as Mina,
        primaryComma: {
            monzo: [21, -10, -1, -1] as Monzo,
            position: 25.3103710121659 as Cents,
        },
        elements: [".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 55 as Id<SagittalSymbol>,
        ascii: "`.|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 53 as Mina,
        primaryComma: {
            monzo: [-11, 3, 0, 1, 1] as Monzo,
            position: 26.0088514300439 as Cents,
        },
        elements: ["`|", ".|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 56 as Id<SagittalSymbol>,
        ascii: ",,|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 54 as Mina,
        primaryComma: {
            monzo: [1, 1, -1, 0, 1, -1] as Monzo,
            position: 26.4315675959986 as Cents,
        },
        elements: [",,|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 57 as Id<SagittalSymbol>,
        ascii: ",|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 55 as Mina,
        primaryComma: {
            monzo: [-6, 0, 1, 0, 0, 1] as Monzo,
            position: 26.8413756341454 as Cents,
        },
        elements: [",|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 58 as Id<SagittalSymbol>,
        ascii: "|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 56 as Mina,
        primaryComma: {
            monzo: [6, -2, 0, -1] as Monzo,
            position: 27.2640918001001 as Cents,
        },
        elements: ["|)"] as SymbolLongAscii[],
    },
    {
        id: 59 as Id<SagittalSymbol>,
        ascii: "`|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 57 as Mina,
        primaryComma: {
            monzo: [5, -9, 4] as Monzo,
            position: 27.6598476708525 as Cents,
        },
        elements: ["`|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 60 as Id<SagittalSymbol>,
        ascii: "``|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 58 as Mina,
        primaryComma: {
            monzo: [-14, 9, 0, 0, 1, -1] as Monzo,
            position: 28.3852883839327 as Cents,
        },
        elements: ["``|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 61 as Id<SagittalSymbol>,
        ascii: ",'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 59 as Mina,
        primaryComma: {
            monzo: [-21, 8, 2, 0, 0, 1] as Monzo,
            position: 28.7950964220796 as Cents,
        },
        elements: [",|", "'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 62 as Id<SagittalSymbol>,
        ascii: "'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 60 as Mina,
        primaryComma: {
            monzo: [-9, 6, 1, -1] as Monzo,
            position: 29.2178125880342 as Cents,
        },
        elements: ["'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 63 as Id<SagittalSymbol>,
        ascii: "`'|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 61 as Mina,
        primaryComma: {
            monzo: [-10, -1, 5] as Monzo,
            position: 29.6135684587868 as Cents,
        },
        elements: ["`|", "'|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 64 as Id<SagittalSymbol>,
        ascii: ",)|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 62 as Mina,
        primaryComma: {
            monzo: [5, -5, 1, 0, -1, 0, 1] as Monzo,
            position: 30.1761766735484 as Cents,
        },
        elements: [",|", ")|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 65 as Id<SagittalSymbol>,
        ascii: ")|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 63 as Mina,
        primaryComma: {
            monzo: [-3, 1, 0, -1, 0, 0, 0, 1] as Monzo,
            position: 30.6421105285650 as Cents,
        },
        elements: [")|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 66 as Id<SagittalSymbol>,
        ascii: ".(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 64 as Mina,
        primaryComma: {
            monzo: [3, 0, -1, 1, -1] as Monzo,
            position: 31.1942502395332 as Cents,
        },
        elements: [".|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 67 as Id<SagittalSymbol>,
        ascii: "|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 65 as Mina,
        primaryComma: {
            monzo: [-1, -3, 1, 0, 1] as Monzo,
            position: 31.7666536334294 as Cents,
        },
        elements: ["|\\"] as SymbolLongAscii[],
    },
    {
        id: 68 as Id<SagittalSymbol>,
        ascii: "`|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 66 as Mina,
        primaryComma: {
            monzo: [11, -5, 0, -1, 1, -1] as Monzo,
            position: 32.1893697993842 as Cents,
        },
        elements: ["`|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 69 as Id<SagittalSymbol>,
        ascii: ",(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 67 as Mina,
        primaryComma: {
            monzo: [-4, 1, 3, 0, 0, 0, 0, 0, -1] as Monzo,
            position: 32.6217951914765 as Cents,
        },
        elements: [",|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 70 as Id<SagittalSymbol>,
        ascii: "(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 68 as Mina,
        primaryComma: {
            monzo: [-12, 8, 0, 1, -1] as Monzo,
            position: 33.1479710274675 as Cents,
        },
        elements: ["(|"] as SymbolLongAscii[],
    },
    {
        id: 71 as Id<SagittalSymbol>,
        ascii: "`(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 69 as Mina,
        primaryComma: {
            monzo: [2, -1, 0, 0, 0, 1, -1] as Monzo,
            position: 33.6172514035158 as Cents,
        },
        elements: ["`|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 72 as Id<SagittalSymbol>,
        ascii: "``(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 70 as Mina,
        primaryComma: {
            monzo: [-1, 1, -2, 0, 0, 0, 1] as Monzo,
            position: 34.2829826361251 as Cents,
        },
        elements: ["``|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 73 as Id<SagittalSymbol>,
        ascii: ",'(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 71 as Mina,
        primaryComma: {
            monzo: [2, 2, 0, 1, 0, -1, 0, -1] as Monzo,
            position: 34.6952302982867 as Cents,
        },
        elements: [",|", "'|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 74 as Id<SagittalSymbol>,
        ascii: "'(|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 72 as Mina,
        primaryComma: {
            monzo: [1, 0, 2, -2] as Monzo,
            position: 34.9756147914198 as Cents,
        },
        elements: ["'|", "(|"] as SymbolLongAscii[],
    },
    {
        id: 75 as Id<SagittalSymbol>,
        ascii: ",~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 72.40486810762850 as Mina,
        primaryComma: {
            monzo: [3, -5, 0, 0, 0, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 35.2605681373132 as Cents,
        },
        elements: [",|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 76 as Id<SagittalSymbol>,
        ascii: "~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 73 as Mina,
        primaryComma: {
            monzo: [-4, -1, 0, 2] as Monzo,
            position: 35.6968120728623 as Cents,
        },
        elements: ["~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 77 as Id<SagittalSymbol>,
        ascii: "`~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 74 as Mina,
        primaryComma: {
            monzo: [-16, 9, -1, 0, 0, 0, 1] as Monzo,
            position: 36.2367034240592 as Cents,
        },
        elements: ["`|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 79 as Id<SagittalSymbol>,
        ascii: ",.(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 75 as Mina,
        primaryComma: {
            monzo: [-10, 7, 0, 0, 1, 0, 0, 0, -1] as Monzo,
            position: 36.7286011540533 as Cents,
        },
        elements: [",|", ".|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 80 as Id<SagittalSymbol>,
        ascii: ".(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 76 as Mina,
        primaryComma: {
            monzo: [13, -6, 0, 0, -1] as Monzo,
            position: 36.9520524429189 as Cents,
        },
        elements: [".|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 81 as Id<SagittalSymbol>,
        ascii: "'~|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 77 as Mina,
        primaryComma: {
            monzo: [-19, 7, 1, 2] as Monzo,
            position: 37.6505328607966 as Cents,
        },
        elements: ["'|", "~|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 82 as Id<SagittalSymbol>,
        ascii: "/|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 78 as Mina,
        primaryComma: {
            monzo: [1, -2, -1, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 38.0506316728057 as Cents,
        },
        elements: ["/|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 83 as Id<SagittalSymbol>,
        ascii: ",,(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 78.39014554523920 as Mina,
        primaryComma: {
            monzo: [-7, 5, 0, 1, 0, -1] as Monzo,
            position: 38.0732490267513 as Cents,
        },
        elements: [",,|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 84 as Id<SagittalSymbol>,
        ascii: ",(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 79 as Mina,
        primaryComma: {
            monzo: [7, -4, 0, 0, 1, 0, -1] as Monzo,
            position: 38.5425294027997 as Cents,
        },
        elements: [",|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 85 as Id<SagittalSymbol>,
        ascii: "(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 80 as Mina,
        primaryComma: {
            monzo: [-2, 2, 1, 0, -1] as Monzo,
            position: 38.9057732308529 as Cents,
        },
        elements: ["(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 86 as Id<SagittalSymbol>,
        ascii: "`(|(" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 81 as Mina,
        primaryComma: {
            monzo: [10, 0, 0, -1, -1, -1] as Monzo,
            position: 39.3284893968078 as Cents,
        },
        elements: ["`|", "(|", "|("] as SymbolLongAscii[],
    },
    {
        id: 87 as Id<SagittalSymbol>,
        ascii: "~|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 82 as Mina,
        primaryComma: {
            monzo: [-14, 6, 0, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 40.0043524607400 as Cents,
        },
        elements: ["~|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 88 as Id<SagittalSymbol>,
        ascii: ",.//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 83 as Mina,
        primaryComma: {
            monzo: [-5, 2, -2, 1, 0, 1] as Monzo,
            position: 40.6361422395406 as Cents,
        },
        elements: [",|", ".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 89 as Id<SagittalSymbol>,
        ascii: ".//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 84 as Mina,
        primaryComma: {
            monzo: [7, 0, -3] as Monzo,
            position: 41.0588584054956 as Cents,
        },
        elements: [".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 90 as Id<SagittalSymbol>,
        ascii: "`.//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 85 as Mina,
        primaryComma: {
            monzo: [6, -7, 1, 1] as Monzo,
            position: 41.4546142762478 as Cents,
        },
        elements: ["`|", ".|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 91 as Id<SagittalSymbol>,
        ascii: ",,//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 86 as Mina,
        primaryComma: {
            monzo: [-6, 3, 0, -1, 0, 0, 1] as Monzo,
            position: 41.9945056274446 as Cents,
        },
        elements: [",,|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 92 as Id<SagittalSymbol>,
        ascii: ",//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 87 as Mina,
        primaryComma: {
            monzo: [-20, 10, -1, 1, 0, 1] as Monzo,
            position: 42.5898630274750 as Cents,
        },
        elements: [",|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 93 as Id<SagittalSymbol>,
        ascii: "//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 88 as Mina,
        primaryComma: {
            monzo: [-8, 8, -2] as Monzo,
            position: 43.0125791934297 as Cents,
        },
        elements: ["/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 94 as Id<SagittalSymbol>,
        ascii: "`//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 89 as Mina,
        primaryComma: {
            monzo: [-9, 1, 2, 1] as Monzo,
            position: 43.4083350641820 as Cents,
        },
        elements: ["`|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 95 as Id<SagittalSymbol>,
        ascii: "``//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 90 as Mina,
        primaryComma: {
            monzo: [3, -1, 1, 0, 0, -1] as Monzo,
            position: 43.8310512301367 as Cents,
        },
        elements: ["``|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 96 as Id<SagittalSymbol>,
        ascii: ",'//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 91 as Mina,
        primaryComma: {
            monzo: [-11, 6, 0, 2, 0, 0, -1] as Monzo,
            position: 44.4264086301669 as Cents,
        },
        elements: [",|", "'|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 97 as Id<SagittalSymbol>,
        ascii: "'//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 92 as Mina,
        primaryComma: {
            monzo: [-1, 1, 0, 0, 0, 1, 0, -1] as Monzo,
            position: 44.9696465023956 as Cents,
        },
        elements: ["'|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 98 as Id<SagittalSymbol>,
        ascii: ",,)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 93 as Mina,
        primaryComma: {
            monzo: [0, -1, -2, 1, 1] as Monzo,
            position: 45.5614202388245 as Cents,
        },
        elements: [",,|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 99 as Id<SagittalSymbol>,
        ascii: ",)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 94 as Mina,
        primaryComma: {
            monzo: [-12, 7, 2, 0, 0, -1] as Monzo,
            position: 45.7847720180709 as Cents,
        },
        elements: [",|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 100 as Id<SagittalSymbol>,
        ascii: ")//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 95 as Mina,
        primaryComma: {
            monzo: [5, -4, -1, 0, 0, 1] as Monzo,
            position: 46.3939444429262 as Cents,
        },
        elements: [")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 101 as Id<SagittalSymbol>,
        ascii: "`)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 96 as Mina,
        primaryComma: {
            monzo: [17, -6, -2, -1] as Monzo,
            position: 46.8166606088810 as Cents,
        },
        elements: ["`|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 102 as Id<SagittalSymbol>,
        ascii: "``)//|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 97 as Mina,
        primaryComma: {
            monzo: [-2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 47.4340370239647 as Cents,
        },
        elements: ["``|", ")|", "/|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 103 as Id<SagittalSymbol>,
        ascii: ",,/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 98 as Mina,
        primaryComma: {
            monzo: [-3, 5, -2, 0, 1, -1] as Monzo,
            position: 47.9378571927136 as Cents,
        },
        elements: [",,|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 104 as Id<SagittalSymbol>,
        ascii: ",/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 99 as Mina,
        primaryComma: {
            monzo: [-10, 4, 0, 0, 0, 1] as Monzo,
            position: 48.3476652308603 as Cents,
        },
        elements: [",|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 105 as Id<SagittalSymbol>,
        ascii: "/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 100 as Mina,
        primaryComma: {
            monzo: [2, 2, -1, -1] as Monzo,
            position: 48.7703813968149 as Cents,
        },
        elements: ["/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 106 as Id<SagittalSymbol>,
        ascii: "`/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 101 as Mina,
        primaryComma: {
            monzo: [1, -5, 3] as Monzo,
            position: 49.1661372675673 as Cents,
        },
        elements: ["`|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 107 as Id<SagittalSymbol>,
        ascii: "(|~" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 102 as Mina,
        primaryComma: {
            monzo: [4, -2, 0, 0, 1, 0, 0, -1] as Monzo,
            position: 49.8949245016792 as Cents,
        },
        elements: ["(|", "|~"] as SymbolLongAscii[],
    },
    {
        id: 108 as Id<SagittalSymbol>,
        ascii: ",'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 103 as Mina,
        primaryComma: {
            monzo: [-25, 12, 1, 0, 0, 1] as Monzo,
            position: 50.3013860187944 as Cents,
        },
        elements: [",|", "'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 109 as Id<SagittalSymbol>,
        ascii: "'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 104 as Mina,
        primaryComma: {
            monzo: [-13, 10, 0, -1] as Monzo,
            position: 50.7241021847494 as Cents,
        },
        elements: ["'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 110 as Id<SagittalSymbol>,
        ascii: "`'/|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 105 as Mina,
        primaryComma: {
            monzo: [-14, 3, 4] as Monzo,
            position: 51.1198580555015 as Cents,
        },
        elements: ["`|", "'|", "/|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 111 as Id<SagittalSymbol>,
        ascii: "./|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 105.57202549664000 as Mina,
        primaryComma: {
            monzo: [10, -7, -1, 0, 1] as Monzo,
            position: 51.3192224422099 as Cents,
        },
        elements: [".|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 112 as Id<SagittalSymbol>,
        ascii: "`./|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 106 as Mina,
        primaryComma: {
            monzo: [1, -1, 0, 0, -1, 0, 1] as Monzo,
            position: 51.6824662702631 as Cents,
        },
        elements: ["`|", ".|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 113 as Id<SagittalSymbol>,
        ascii: ",,/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 107 as Mina,
        primaryComma: {
            monzo: [7, -3, 1, 0, 0, 0, 0, 0, -1] as Monzo,
            position: 52.1743640002570 as Cents,
        },
        elements: [",,|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 114 as Id<SagittalSymbol>,
        ascii: ",/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 108 as Mina,
        primaryComma: {
            monzo: [-1, 4, -2, 1, -1] as Monzo,
            position: 52.7005398362484 as Cents,
        },
        elements: [",|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 115 as Id<SagittalSymbol>,
        ascii: "/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 109 as Mina,
        primaryComma: {
            monzo: [-5, 1, 0, 0, 1] as Monzo,
            position: 53.2729432301441 as Cents,
        },
        elements: ["/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 116 as Id<SagittalSymbol>,
        ascii: "`/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 110 as Mina,
        primaryComma: {
            monzo: [-14, 7, 1, 0, -1, 0, 1] as Monzo,
            position: 53.6361870581975 as Cents,
        },
        elements: ["`|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 117 as Id<SagittalSymbol>,
        ascii: ",(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 111 as Mina,
        primaryComma: {
            monzo: [0, -2, 1, -1, 0, 1] as Monzo,
            position: 54.1054674342458 as Cents,
        },
        elements: [",|", "(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 118 as Id<SagittalSymbol>,
        ascii: "(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 112 as Mina,
        primaryComma: {
            monzo: [12, -4, 0, -2] as Monzo,
            position: 54.5281836002006 as Cents,
        },
        elements: ["(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 119 as Id<SagittalSymbol>,
        ascii: "`(/|" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 113 as Mina,
        primaryComma: {
            monzo: [5, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1] as Monzo,
            position: 54.9644275357497 as Cents,
        },
        elements: ["`|", "(|", "/|"] as SymbolLongAscii[],
    },
    {
        id: 120 as Id<SagittalSymbol>,
        ascii: "'/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 113.45170990741700 as Mina,
        primaryComma: {
            monzo: [-20, 9, 1, 0, 1] as Monzo,
            position: 55.2266640180783 as Cents,
        },
        elements: ["'|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 121 as Id<SagittalSymbol>,
        ascii: "`'/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 114 as Mina,
        primaryComma: {
            monzo: [-8, 7, 0, -1, 1, -1] as Monzo,
            position: 55.6493801840332 as Cents,
        },
        elements: ["`|", "'|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 122 as Id<SagittalSymbol>,
        ascii: ",)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 115 as Mina,
        primaryComma: {
            monzo: [-6, -2, 1, 1, 0, 0, 1] as Monzo,
            position: 56.1850281035923 as Cents,
        },
        elements: [",|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 123 as Id<SagittalSymbol>,
        ascii: ")/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 116 as Mina,
        primaryComma: {
            monzo: [-3, 4, 1, -2] as Monzo,
            position: 56.4819043881346 as Cents,
        },
        elements: [")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 124 as Id<SagittalSymbol>,
        ascii: "`)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 117 as Mina,
        primaryComma: {
            monzo: [-8, 3, -1, 2] as Monzo,
            position: 57.2031016695774 as Cents,
        },
        elements: ["`|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 125 as Id<SagittalSymbol>,
        ascii: "``)/|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 118 as Mina,
        primaryComma: {
            monzo: [-5, 9, -1, -1, 0, 0, -1] as Monzo,
            position: 57.4999779541197 as Cents,
        },
        elements: ["``|", ")|", "/|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 126 as Id<SagittalSymbol>,
        ascii: ",.(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 119 as Mina,
        primaryComma: {
            monzo: [-3, 0, 0, 1, -1, 1] as Monzo,
            position: 58.0356258736789 as Cents,
        },
        elements: [",|", ".|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 127 as Id<SagittalSymbol>,
        ascii: ".(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 120 as Mina,
        primaryComma: {
            monzo: [9, -2, -1, 0, -1] as Monzo,
            position: 58.4583420396336 as Cents,
        },
        elements: [".|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 128 as Id<SagittalSymbol>,
        ascii: ",|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 120.70032964758700 as Mina,
        primaryComma: {
            monzo: [-16, 7, 0, 0, 0, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 58.7205785219622 as Cents,
        },
        elements: [",|", "|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 129 as Id<SagittalSymbol>,
        ascii: "|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 121 as Mina,
        primaryComma: {
            monzo: [-23, 11, 0, 2] as Monzo,
            position: 59.1568224575114 as Cents,
        },
        elements: ["|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 130 as Id<SagittalSymbol>,
        ascii: "`|\\)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 122 as Mina,
        primaryComma: {
            monzo: [-11, 9, -1, 1, 0, -1] as Monzo,
            position: 59.5795386234664 as Cents,
        },
        elements: ["`|", "|\\", "|)"] as SymbolLongAscii[],
    },
    {
        id: 131 as Id<SagittalSymbol>,
        ascii: ",(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 123 as Mina,
        primaryComma: {
            monzo: [3, 0, -1, 0, 1, 0, -1] as Monzo,
            position: 60.0488189995148 as Cents,
        },
        elements: [",|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 132 as Id<SagittalSymbol>,
        ascii: "(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 124 as Mina,
        primaryComma: {
            monzo: [-6, 6, 0, 0, -1] as Monzo,
            position: 60.4120628275676 as Cents,
        },
        elements: ["(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 133 as Id<SagittalSymbol>,
        ascii: "`(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 125 as Mina,
        primaryComma: {
            monzo: [-10, 3, 2, -1, 1] as Monzo,
            position: 60.9844662214638 as Cents,
        },
        elements: ["`|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 134 as Id<SagittalSymbol>,
        ascii: "``(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 126 as Mina,
        primaryComma: {
            monzo: [-18, 10, -1, 0, 0, 0, 0, 0, 1] as Monzo,
            position: 61.5106420574550 as Cents,
        },
        elements: ["``|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 135 as Id<SagittalSymbol>,
        ascii: ",'(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 127 as Mina,
        primaryComma: {
            monzo: [-12, 8, 0, 0, 1, 0, -1] as Monzo,
            position: 62.0025397874486 as Cents,
        },
        elements: [",|", "'|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 136 as Id<SagittalSymbol>,
        ascii: "'(|)" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 128 as Mina,
        primaryComma: {
            monzo: [-21, 14, 1, 0, -1] as Monzo,
            position: 62.3657836155021 as Cents,
        },
        elements: ["'|", "(|", "|)"] as SymbolLongAscii[],
    },
    {
        id: 137 as Id<SagittalSymbol>,
        ascii: ",.(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 128.58001405836400 as Mina,
        primaryComma: {
            monzo: [3, 4, -4] as Monzo,
            position: 62.5651480022103 as Cents,
        },
        elements: [",|", ".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 138 as Id<SagittalSymbol>,
        ascii: ".(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.ULTRA,
        mina: 129 as Mina,
        primaryComma: {
            monzo: [2, -3, 0, 1] as Monzo,
            position: 62.9609038729626 as Cents,
        },
        elements: [".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 139 as Id<SagittalSymbol>,
        ascii: "`.(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 130 as Mina,
        primaryComma: {
            monzo: [14, -5, -1, 0, 0, -1] as Monzo,
            position: 63.3836200389176 as Cents,
        },
        elements: ["`|", ".|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 140 as Id<SagittalSymbol>,
        ascii: "|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 131 as Mina,
        primaryComma: {
            monzo: [-15, 9, 0, 0, -1, 0, 0, 1] as Monzo,
            position: 63.7900815560325 as Cents,
        },
        elements: ["|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 141 as Id<SagittalSymbol>,
        ascii: ",(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 132 as Mina,
        primaryComma: {
            monzo: [-12, 12, -3] as Monzo,
            position: 64.5188687901447 as Cents,
        },
        elements: [",|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 142 as Id<SagittalSymbol>,
        ascii: "(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.MEDIUM,
        mina: 133 as Mina,
        primaryComma: {
            monzo: [-13, 5, 1, 1] as Monzo,
            position: 64.9146246608968 as Cents,
        },
        elements: ["(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 143 as Id<SagittalSymbol>,
        ascii: "`(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 134 as Mina,
        primaryComma: {
            monzo: [-1, 3, 0, 0, 0, -1] as Monzo,
            position: 65.3373408268518 as Cents,
        },
        elements: ["`|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 144 as Id<SagittalSymbol>,
        ascii: "``(|\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 135 as Mina,
        primaryComma: {
            monzo: [-8, 2, 2, 0, -1, 1] as Monzo,
            position: 65.7471488649985 as Cents,
        },
        elements: ["``|", "(|", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 145 as Id<SagittalSymbol>,
        ascii: ",,)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 136 as Mina,
        primaryComma: {
            monzo: [-9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1] as Monzo,
            position: 66.2509690337472 as Cents,
        },
        elements: [",,|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 146 as Id<SagittalSymbol>,
        ascii: ",)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 137 as Mina,
        primaryComma: {
            monzo: [-28, 13, 2, 1] as Monzo,
            position: 66.8683454488310 as Cents,
        },
        elements: [",|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 147 as Id<SagittalSymbol>,
        ascii: ")|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.HIGH,
        mina: 138 as Mina,
        primaryComma: {
            monzo: [-16, 11, 1, 0, 0, -1] as Monzo,
            position: 67.2910616147857 as Cents,
        },
        elements: [")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 148 as Id<SagittalSymbol>,
        ascii: "`)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 139 as Mina,
        primaryComma: {
            monzo: [1, 0, -2, 0, 0, 1] as Monzo,
            position: 67.9002340396410 as Cents,
        },
        elements: ["`|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
    {
        id: 149 as Id<SagittalSymbol>,
        ascii: "``)|\\\\" as SymbolLongAscii,
        unicode: "" as SymbolUnicode,
        introducingLevel: Level.EXTREME,
        mina: 140 as Mina,
        primaryComma: {
            monzo: [-11, 8, 2, -1, -1] as Monzo,
            position: 68.1235858189 as Cents,
        },
        elements: ["``|", ")|", "|\\", "|\\"] as SymbolLongAscii[],
    },
]

export {
    SYMBOLS,
}
