export { DecimalNotDefaultingToPotentiallyIrrational, Decimal, PotentiallyIrrationalNumByDecimal } from "./types"
export { computeDecimalFromNum } from "./decimalFromNum"
export { computeDecimalFromMonzo } from "./decimalFromMonzo"
export { computeDecimalFromRatio } from "./decimalFromRatio"
export { isSuperDecimal, isUnisonDecimal, isSubDecimal, invertDecimal } from "./decimalDirection"
