export {Flacco, FlaccoSubset, Accent, Flag, FlagCombo, Symbolic} from "./types"
export {FLACCO_SUBSETS, FLACCO_SUBSETS_SORTED_BY_SIZE} from "./flaccoSubsets"
export {getSmallestFlaccoSubset} from "./smallestFlaccoSubset"
export {computeSymbolFromFlacco} from "./symbolFromFlacco"
export {getFlacco} from "./flacco"
export {FLACCOS} from "./flaccos"
