enum AccentId {
    TICK = "tick",
    WING = "wing",
    BIRD = "bird",
}

type Accent = {
    id: AccentId,
    against?: boolean,
}

type Arm = Array<Accent>

enum ArmId {
    WING = "wing",
    BIRD = "bird",
    WING_AGAINST_TICK = "wingAgainstTick",
    TICK = "tick",
    WING_AND_TICK = "wingAndTick",
}

enum FlagId {
    BARB = "barb",
    SCROLL = "scroll",
    ARC = "arc",
    BOATHOOK = "boathook",
}

// You *could* make:
/*
type Flag = {
    id: FlagId,
    double?: boolean,
}
 */
// If you strongly wanted parallelism between AccentId -> Accent -> Arm and FlagId -> Flag -> Head.
// However, I feel that because of the way "double" gets used in HeadId both for doubling a specific flag on one side
// And for

interface Head {
    left?: FlagId[],
    right?: FlagId[],
}

enum HeadId {
    BARE_SHAFT = "bareShaft",
    RIGHT_SCROLL = "rightScroll",
    LEFT_BARB = "leftBarb",
    RIGHT_ARC = "rightArc",
    DOUBLE_LEFT_BARB = "doubleLeftBarb",
    BARB_AND_ARC = "barbAndArc",
    DOUBLE_BARB = "doubleBarb",
    DOUBLE_ARC = "doubleArc",
    ARC_AND_BARB = "arcAndBarb",
    DOUBLE_SCROLL = "doubleScroll",
    BOATHOOK_AND_SCROLL = "boathookAndScroll",
    RIGHT_BARB = "rightBarb",
    LEFT_ARC = "leftArc",
    ARC_AND_SCROLL = "arcAndScroll",
    RIGHT_BOATHOOK = "rightBoathook",
    LEFT_SCROLL_AND_BARB = "leftScrollAndBarb",
    BARB_AND_BOATHOOK = "barbAndBoathook",
    LEFT_SCROLL = "leftScroll",
    LEFT_BOATHOOK = "leftBoathook",
    LEFT_SCROLL_AND_BOATHOOK = "leftScrollAndBoathook",
    DOUBLE_LEFT_BOATHOOK = "doubleLeftBoathook",
    SCROLL_AND_BOATHOOK = "scrollAndBoathook",
    SCROLL_AND_ARC = "scrollAndArc",
    BOATHOOK_AND_ARC = "boathookAndArc",
    BOATHOOK_AND_BARB = "boathookAndBarb",
    LEFT_SCROLL_DOUBLE_LEFT_BARB = "leftScrollDoubleLeftBarb",
    ARC_AND_BOATHOOK = "arcAndBoathook",
    LEFT_ARC_AND_BARB = "leftArcAndBarb",
    LEFT_SCROLL_AND_DOUBLE_BARB = "leftScrollAndDoubleBarb",
    RIGHT_BARB_AND_ARC = "rightBarbAndArc",
    DOUBLE_RIGHT_BARB = "doubleRightBarb",
    LEFT_SCROLL_DOUBLE_RIGHT_BARB = "leftScrollDoubleRightBarb",
}

enum FlaccoId {
    NULL = "bare",
    WING = "wwing",
    BIRD = "bird",
    TICK_AGAINST_LEFT_SCROLL = "tickAgainstLeftScroll",
    TICK = "tick",
    WING_AND_TICK = "wingAndTick",
    WING_AGAINST_LEFT_SCROLL = "wingAgainstLeftScroll",
    LEFT_SCROLL = "leftScroll",
    WING_AND_LEFT_SCROLL = "wingAndLeftScroll",
    BIRD_AND_LEFT_SCROLL = "birdAndLeftScroll",
    BIRD_AGAINST_RIGHT_SCROLL = "birdAgainstRightScroll",
    WING_AGAINST_RIGHT_SCROLL = "wingAgainstRightScroll",
    RIGHT_SCROLL = "rightScroll",
    WING_AND_RIGHT_SCROLL = "wingAndRightScroll",
    TICK_AGAINST_LEFT_BOATHOOK = "tickAgainstLeftBoathook",
    WING_AGAINST_TICK_AND_RIGHT_SCROLL = "wingAgainstTickAndRightScroll",
    TICK_AND_RIGHT_SCROLL = "tickAndRightScroll",
    WING_AGAINST_LEFT_BOATHOOK = "wingAgainstLeftBoathook",
    LEFT_BOATHOOK = "leftBoathook",
    WING_AGAINST_DOUBLE_SCROLL = "wingAgainstDoubleScroll",
    DOUBLE_SCROLL = "doubleScroll",
    WING_AND_DOUBLE_SCROLL = "wingAndDoubleScroll",
    BIRD_AND_DOUBLE_SCROLL = "birdAndDoubleScroll",
    WING_AGAINST_TICK_AND_DOUBLE_SCROLL = "wingAgainstTickAndDoubleScroll",
    TICK_AND_DOUBLE_SCROLL = "tickAndDoubleScroll",
    LEFT_SCROLL_AND_BOATHOOK = "leftScrollAndBoathook",
    TICK_AGAINST_BOATHOOK_AND_SCROLL = "tickAgainstBoathookAndScroll",
    WING_AGAINST_TICK_AGAINST_BOATHOOK_AND_SCROLL = "wingAgainstTickAgainstBoathookAndScroll",
    BIRD_AGAINST_BOATHOOK_AND_SCROLL = "birdAgainstBoathookAndScroll",
    WING_AGAINST_BOATHOOK_AND_SCROLL = "wingAgainstBoathookAndScroll",
    BOATHOOK_AND_SCROLL = "boathookAndScroll",
    WING_BOATHOOK_AND_SCROLL = "wingBoathookAndScroll",
    BIRD_AGAINST_RIGHT_BOATHOOK = "birdAgainstRightBoathook",
    WING_AGAINST_RIGHT_BOATHOOK = "wingAgainstRightBoathook",
    RIGHT_BOATHOOK = "rightBoathook",
    WING_AND_RIGHT_BOATHOOK = "wingAndRightBoathook",
    DOUBLE_LEFT_BOATHOOK = "doubleLeftBoathook",
    WING_AND_DOUBLE_LEFT_BOATHOOK = "wingAndDoubleLeftBoathook",
    BIRD_AND_DOUBLE_LEFT_BOATHOOK = "birdAndDoubleLeftBoathook",
    WING_AND_TICK_AGAINST_LEFT_BARB = "wingAndTickAgainstLeftBarb",
    TICK_AGAINST_LEFT_BARB = "tickAgainstLeftBarb",
    SCROLL_AND_BOATHOOK = "scrollAndBoathook",
    BIRD_AGAINST_LEFT_BARB = "birdAgainstLeftBarb",
    WING_AGAINST_LEFT_BARB = "wingAgainstLeftBarb",
    LEFT_BARB = "leftBarb",
    WING_AND_LEFT_BARB = "wingAndLeftBarb",
    BIRD_AND_LEFT_BARB = "birdAndLeftBarb",
    TICK_AGAINST_LEFT_SCROLL_AND_BARB = "tickAgainstLeftScrollAndBarb",
    TICK_AND_LEFT_BARB = "tickAndLeftBarb",
    WING_TICK_AND_LEFT_BARB = "wingTickAndLeftBarb",
    BIRD_AGAINST_LEFT_SCROLL_AND_BARB = "birdAgainstLeftScrollAndBarb",
    WING_AGAINST_LEFT_SCROLL_AND_BARB = "wingAgainstLeftScrollAndBarb",
    LEFT_SCROLL_AND_BARB = "leftScrollAndBarb",
    WING_AND_TICK_AGAINST_RIGHT_ARC = "wingAndTickAgainstRightArc",
    TICK_AGAINST_RIGHT_ARC = "tickAgainstRightArc",
    WING_AGAINST_TICK_AGAINST_RIGHT_ARC = "wingAgainstTickAgainstRightArc",
    BIRD_AGAINST_RIGHT_ARC = "birdAgainstRightArc",
    WING_AGAINST_RIGHT_ARC = "wingAgainstRightArc",
    RIGHT_ARC = "rightArc",
    WING_AND_RIGHT_ARC = "wingAndRightArc",
    BIRD_AND_RIGHT_ARC = "birdAndRightArc",
    WING_AGAINST_TICK_AND_RIGHT_ARC = "wingAgainstTickAndRightArc",
    TICK_AND_RIGHT_ARC = "tickAndRightArc",
    WING_TICK_AND_RIGHT_ARC = "wingTickAndRightArc",
    WING_AGAINST_SCROLL_AND_ARC = "wingAgainstScrollAndArc",
    SCROLL_AND_ARC = "scrollAndArc",
    TICK_AGAINST_LEFT_ARC = "tickAgainstLeftArc",
    RIGHT_BARB = "rightBarb",
    WING_AND_RIGHT_BARB = "wingAndRightBarb",
    WING_AGAINST_LEFT_ARC = "wingAgainstLeftArc",
    LEFT_ARC = "leftArc",
    WING_AND_LEFT_ARC = "wingAndLeftArc",
    BIRD_AND_LEFT_ARC = "birdAndLeftArc",
    WING_AGAINST_TICK_AND_LEFT_ARC = "wingAgainstTickAndLeftArc",
    TICK_AND_LEFT_ARC = "tickAndLeftArc",
    WING_AGAINST_BOATHOOK_AND_ARC = "wingAgainstBoathookAndArc",
    BOATHOOK_AND_ARC = "boathookAndArc",
    WING_BOATHOOK_AND_ARC = "wingBoathookAndArc",
    WING_AND_TICK_AGAINST_ARC_AND_SCROLL = "wingAndTickAgainstArcAndScroll",
    TICK_AGAINST_ARC_AND_SCROLL = "tickAgainstArcAndScroll",
    TICK_BOATHOOK_AND_ARC = "tickBoathookAndArc",
    BARB_AND_BOATHOOK = "barbAndBoathook",
    BIRD_AGAINST_ARC_AND_SCROLL = "birdAgainstArcAndScroll",
    WING_AGAINST_ARC_AND_SCROLL = "wingAgainstArcAndScroll",
    ARC_AND_SCROLL = "arcAndScroll",
    WING_ARC_AND_SCROLL = "wingArcAndScroll",
    BOATHOOK_AND_BARB = "boathookAndBarb",
    WING_AND_TICK_AGAINST_DOUBLE_LEFT_BARB = "wingAndTickAgainstDoubleLeftBarb",
    TICK_AGAINST_DOUBLE_LEFT_BARB = "tickAgainstDoubleLeftBarb",
    WING_AGAINST_TICK_AGAINST_DOUBLE_LEFT_BARB = "wingAgainstTickAgainstDoubleLeftBarb",
    BIRD_AGAINST_DOUBLE_LEFT_BARB = "birdAgainstDoubleLeftBarb",
    WING_AGAINST_DOUBLE_LEFT_BARB = "wingAgainstDoubleLeftBarb",
    DOUBLE_LEFT_BARB = "doubleLeftBarb",
    WING_AND_DOUBLE_LEFT_BARB = "wingAndDoubleLeftBarb",
    BIRD_AND_DOUBLE_LEFT_BARB = "birdAndDoubleLeftBarb",
    WING_AGAINST_TICK_AND_DOUBLE_LEFT_BARB = "wingAgainstTickAndDoubleLeftBarb",
    TICK_AND_DOUBLE_LEFT_BARB = "tickAndDoubleLeftBarb",
    BIRD_AGAINST_LEFT_SCROLL_DOUBLE_LEFT_BARB = "birdAgainstLeftScrollDoubleLeftBarb",
    WING_AGAINST_LEFT_SCROLL_DOUBLE_LEFT_BARB = "wingAgainstLeftScrollDoubleLeftBarb",
    LEFT_SCROLL_DOUBLE_LEFT_BARB = "leftScrollDoubleLeftBarb",
    WING_AND_LEFT_SCROLL_DOUBLE_LEFT_BARB = "wingAndLeftScrollDoubleLeftBarb",
    BIRD_AND_LEFT_SCROLL_DOUBLE_LEFT_BARB = "birdAndLeftScrollDoubleLeftBarb",
    BIRD_AGAINST_BARB_AND_ARC = "birdAgainstBarbAndArc",
    WING_AGAINST_BARB_AND_ARC = "wingAgainstBarbAndArc",
    BARB_AND_ARC = "barbAndArc",
    WING_BARB_AND_ARC = "wingBarbAndArc",
    ARC_AND_BOATHOOK = "arcAndBoathook",
    WING_AGAINST_TICK_BARB_AND_ARC = "wingAgainstTickBarbAndArc",
    TICK_BARB_AND_ARC = "tickBarbAndArc",
    WING_TICK_BARB_AND_ARC = "wingTickBarbAndArc",
    TICK_AGAINST_DOUBLE_BARB = "tickAgainstDoubleBarb",
    WING_AGAINST_TICK_AGAINST_DOUBLE_BARB = "wingAgainstTickAgainstDoubleBarb",
    BIRD_AGAINST_DOUBLE_BARB = "birdAgainstDoubleBarb",
    WING_AGAINST_DOUBLE_BARB = "wingAgainstDoubleBarb",
    DOUBLE_BARB = "doubleBarb",
    WING_AND_DOUBLE_BARB = "wingAndDoubleBarb",
    WING_AGAINST_LEFT_ARC_AND_BARB = "wingAgainstLeftArcAndBarb",
    LEFT_ARC_AND_BARB = "leftArcAndBarb",
    WING_AND_LEFT_ARC_AND_BARB = "wingAndLeftArcAndBarb",
    TICK_AND_DOUBLE_BARB = "tickAndDoubleBarb",
    WING_TICK_AND_DOUBLE_BARB = "wingTickAndDoubleBarb",
    WING_AGAINST_LEFT_SCROLL_AND_DOUBLE_BARB = "wingAgainstLeftScrollAndDoubleBarb",
    LEFT_SCROLL_AND_DOUBLE_BARB = "leftScrollAndDoubleBarb",
    WING_LEFT_SCROLL_AND_DOUBLE_BARB = "wingLeftScrollAndDoubleBarb",
    BIRD_LEFT_SCROLL_AND_DOUBLE_BARB = "birdLeftScrollAndDoubleBarb",
    WING_AND_TICK_AGAINST_DOUBLE_ARC = "wingAndTickAgainstDoubleArc",
    TICK_AGAINST_DOUBLE_ARC = "tickAgainstDoubleArc",
    WING_AGAINST_RIGHT_BARB_AND_ARC = "wingAgainstRightBarbAndArc",
    RIGHT_BARB_AND_ARC = "rightBarbAndArc",
    WING_AND_RIGHT_BARB_AND_ARC = "wingAndRightBarbAndArc",
    WING_AGAINST_DOUBLE_ARC = "wingAgainstDoubleArc",
    DOUBLE_ARC = "doubleArc",
    WING_AND_DOUBLE_ARC = "wingAndDoubleArc",
    BIRD_AND_DOUBLE_ARC = "birdAndDoubleArc",
    WING_AGAINST_TICK_AND_DOUBLE_ARC = "wingAgainstTickAndDoubleArc",
    TICK_AND_DOUBLE_ARC = "tickAndDoubleArc",
    WING_AND_TICK_AGAINST_ARC_AND_BARB = "wingAndTickAgainstArcAndBarb",
    TICK_AGAINST_ARC_AND_BARB = "tickAgainstArcAndBarb",
    WING_AGAINST_TICK_AGAINST_ARC_AND_BARB = "wingAgainstTickAgainstArcAndBarb",
    DOUBLE_RIGHT_BARB = "doubleRightBarb",
    WING_AGAINST_ARC_AND_BARB = "wingAgainstArcAndBarb",
    ARC_AND_BARB = "arcAndBarb",
    WING_ARC_AND_BARB = "wingArcAndBarb",
    BIRD_ARC_AND_BARB = "birdArcAndBarb",
    BIRD_AGAINST_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "birdAgainstLeftScrollDoubleRightBarb",
    WING_AGAINST_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "wingAgainstLeftScrollDoubleRightBarb",
    LEFT_SCROLL_DOUBLE_RIGHT_BARB = "leftScrollDoubleRightBarb",
    WING_AND_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "wingAndLeftScrollDoubleRightBarb",
    BIRD_AND_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "birdAndLeftScrollDoubleRightBarb",
}

// FlagId and AccentId Combination (see: http://forum.sagittal.org/viewtopic.php?p=2474#p2474)
interface Flacco extends Head {
    arm?: Arm,
}

export {
    Flacco,
    FlagId,
    AccentId,
    Head,
    HeadId,
    Arm,
    ArmId,
    Accent,
    FlaccoId,
}
