enum Accent {
    TICK = "tick",
    WING = "wing",
    BIRD = "bird",
}

// TODO: ORIENTATION - BOOLEAN OR 2-ELEMENT ENUM?
//  Would this be better if it was just a boolean? drop "with" altogether and it's either "" or "against"
//  Not sure if that has better synergy with the shifted/negated/mirrored booleans, or should be more like
//  Left/right and up/down
//  - Recursive against is okay; That is wings can be against ticks just as ticks against cores
//  This is that crust layers conceptualization of Dave's popping up (as opposed to a mere dichotomy)
enum Orientation {
    WITH = "with",
    AGAINST = "against",
}

type OrientedAccent = {
    orientation: Orientation,
    accent: Accent,
}

type Arm = Array<OrientedAccent>

enum ArmId {
    WING = "wing",
    BIRD = "bird",
    WING_FROM_TICK = "wingFromTick",
    TICK = "tick",
    WING_AND_TICK = "wingAndTick",
}

enum Flag {
    BARB = "barb",
    SCROLL = "scroll",
    ARC = "arc",
    BOATHOOK = "boathook",
}

enum HeadId {
    BARE_SHAFT = "bareShaft",
    RIGHT_SCROLL = "rightScroll",
    LEFT_BARB = "leftBarb",
    RIGHT_ARC = "rightArc",
    DOUBLE_LEFT_BARB = "doubleLeftBarb",
    BARB_AND_ARC = "barbAndArc",
    DOUBLE_BARB = "doubleBarb",
    DOUBLE_ARC = "doubleArc",
    ARC_AND_BARB = "arcAndBarb",
    DOUBLE_SCROLL = "doubleScroll",
    BOATHOOK_AND_SCROLL = "boathookAndScroll",
    RIGHT_BARB = "rightBarb",
    LEFT_ARC = "leftArc",
    ARC_AND_SCROLL = "arcAndScroll",
    RIGHT_BOATHOOK = "rightBoathook",
    LEFT_SCROLL_AND_BARB = "leftScrollAndBarb",
    BARB_AND_BOATHOOK = "barbAndBoathook",
    LEFT_SCROLL = "leftScroll",
    LEFT_BOATHOOK = "leftBoathook",
    LEFT_SCROLL_AND_BOATHOOK = "leftScrollAndBoathook",
    DOUBLE_LEFT_BOATHOOK = "doubleLeftBoathook",
    SCROLL_AND_BOATHOOK = "scrollAndBoathook",
    SCROLL_AND_ARC = "scrollAndArc",
    BOATHOOK_AND_ARC = "boathookAndArc",
    BOATHOOK_AND_BARB = "boathookAndBarb",
    LEFT_SCROLL_DOUBLE_LEFT_BARB = "leftScrollDoubleLeftBarb",
    ARC_AND_BOATHOOK = "arcAndBoathook",
    LEFT_ARC_AND_BARB = "leftArcAndBarb",
    LEFT_SCROLL_AND_DOUBLE_BARB = "leftScrollAndDoubleBarb",
    RIGHT_BARB_AND_ARC = "rightBarbAndArc",
    DOUBLE_RIGHT_BARB = "doubleRightBarb",
    LEFT_SCROLL_DOUBLE_RIGHT_BARB = "leftScrollDoubleRightBarb",
}

interface Head {
    left?: Flag[],
    right?: Flag[],
}

enum FlaccoId {
    NULL = "bare",
    WING = "wwing",
    BIRD = "bird",
    TICK_AGAINST_LEFT_SCROLL = "tickAgainstLeftScroll",
    TICK = "tick",
    WING_AND_TICK = "wingAndTick",
    WING_AGAINST_LEFT_SCROLL = "wingAgainstLeftScroll",
    LEFT_SCROLL = "leftScroll",
    WING_WITH_LEFT_SCROLL = "wingWithLeftScroll",
    BIRD_WITH_LEFT_SCROLL = "birdWithLeftScroll",
    BIRD_AGAINST_RIGHT_SCROLL = "birdAgainstRightScroll",
    WING_AGAINST_RIGHT_SCROLL = "wingAgainstRightScroll",
    RIGHT_SCROLL = "rightScroll",
    WING_WITH_RIGHT_SCROLL = "wingWithRightScroll",
    TICK_AGAINST_LEFT_BOATHOOK = "tickAgainstLeftBoathook",
    WING_FROM_TICK_WITH_RIGHT_SCROLL = "wingFromTickWithRightScroll",
    TICK_WITH_RIGHT_SCROLL = "tickWithRightScroll",
    WING_AGAINST_LEFT_BOATHOOK = "wingAgainstLeftBoathook",
    LEFT_BOATHOOK = "leftBoathook",
    WING_AGAINST_DOUBLE_SCROLL = "wingAgainstDoubleScroll",
    DOUBLE_SCROLL = "doubleScroll",
    WING_WITH_DOUBLE_SCROLL = "wingWithDoubleScroll",
    BIRD_WITH_DOUBLE_SCROLL = "birdWithDoubleScroll",
    WING_FROM_TICK_WITH_DOUBLE_SCROLL = "wingFromTickWithDoubleScroll",
    TICK_WITH_DOUBLE_SCROLL = "tickWithDoubleScroll",
    LEFT_SCROLL_AND_BOATHOOK = "leftScrollAndBoathook",
    TICK_AGAINST_BOATHOOK_AND_SCROLL = "tickAgainstBoathookAndScroll",
    WING_FROM_TICK_AGAINST_BOATHOOK_AND_SCROLL = "wingFromTickAgainstBoathookAndScroll",
    BIRD_AGAINST_BOATHOOK_AND_SCROLL = "birdAgainstBoathookAndScroll",
    WING_AGAINST_BOATHOOK_AND_SCROLL = "wingAgainstBoathookAndScroll",
    BOATHOOK_AND_SCROLL = "boathookAndScroll",
    WING_WITH_BOATHOOK_AND_SCROLL = "wingWithBoathookAndScroll",
    BIRD_AGAINST_RIGHT_BOATHOOK = "birdAgainstRightBoathook",
    WING_AGAINST_RIGHT_BOATHOOK = "wingAgainstRightBoathook",
    RIGHT_BOATHOOK = "rightBoathook",
    WING_WITH_RIGHT_BOATHOOK = "wingWithRightBoathook",
    DOUBLE_LEFT_BOATHOOK = "doubleLeftBoathook",
    WING_WITH_DOUBLE_LEFT_BOATHOOK = "wingWithDoubleLeftBoathook",
    BIRD_WITH_DOUBLE_LEFT_BOATHOOK = "birdWithDoubleLeftBoathook",
    WING_AND_TICK_AGAINST_LEFT_BARB = "wingAndTickAgainstLeftBarb",
    TICK_AGAINST_LEFT_BARB = "tickAgainstLeftBarb",
    SCROLL_AND_BOATHOOK = "scrollAndBoathook",
    BIRD_AGAINST_LEFT_BARB = "birdAgainstLeftBarb",
    WING_AGAINST_LEFT_BARB = "wingAgainstLeftBarb",
    LEFT_BARB = "leftBarb",
    WING_WITH_LEFT_BARB = "wingWithLeftBarb",
    BIRD_WITH_LEFT_BARB = "birdWithLeftBarb",
    TICK_AGAINST_LEFT_SCROLL_AND_BARB = "tickAgainstLeftScrollAndBarb",
    TICK_WITH_LEFT_BARB = "tickWithLeftBarb",
    WING_AND_TICK_WITH_LEFT_BARB = "wingAndTickWithLeftBarb",
    BIRD_AGAINST_LEFT_SCROLL_AND_BARB = "birdAgainstLeftScrollAndBarb",
    WING_AGAINST_LEFT_SCROLL_AND_BARB = "wingAgainstLeftScrollAndBarb",
    LEFT_SCROLL_AND_BARB = "leftScrollAndBarb",
    WING_AND_TICK_AGAINST_RIGHT_ARC = "wingAndTickAgainstRightArc",
    TICK_AGAINST_RIGHT_ARC = "tickAgainstRightArc",
    WING_FROM_TICK_AGAINST_RIGHT_ARC = "wingFromTickAgainstRightArc",
    BIRD_AGAINST_RIGHT_ARC = "birdAgainstRightArc",
    WING_AGAINST_RIGHT_ARC = "wingAgainstRightArc",
    RIGHT_ARC = "rightArc",
    WING_WITH_RIGHT_ARC = "wingWithRightArc",
    BIRD_WITH_RIGHT_ARC = "birdWithRightArc",
    WING_FROM_TICK_WITH_RIGHT_ARC = "wingFromTickWithRightArc",
    TICK_WITH_RIGHT_ARC = "tickWithRightArc",
    WING_AND_TICK_WITH_RIGHT_ARC = "wingAndTickWithRightArc",
    WING_AGAINST_SCROLL_AND_ARC = "wingAgainstScrollAndArc",
    SCROLL_AND_ARC = "scrollAndArc",
    TICK_AGAINST_LEFT_ARC = "tickAgainstLeftArc",
    RIGHT_BARB = "rightBarb",
    WING_WITH_RIGHT_BARB = "wingWithRightBarb",
    WING_AGAINST_LEFT_ARC = "wingAgainstLeftArc",
    LEFT_ARC = "leftArc",
    WING_WITH_LEFT_ARC = "wingWithLeftArc",
    BIRD_WITH_LEFT_ARC = "birdWithLeftArc",
    WING_FROM_TICK_WITH_LEFT_ARC = "wingFromTickWithLeftArc",
    TICK_WITH_LEFT_ARC = "tickWithLeftArc",
    WING_AGAINST_BOATHOOK_AND_ARC = "wingAgainstBoathookAndArc",
    BOATHOOK_AND_ARC = "boathookAndArc",
    WING_WITH_BOATHOOK_AND_ARC = "wingWithBoathookAndArc",
    WING_AND_TICK_AGAINST_ARC_AND_SCROLL = "wingAndTickAgainstArcAndScroll",
    TICK_AGAINST_ARC_AND_SCROLL = "tickAgainstArcAndScroll",
    TICK_WITH_BOATHOOK_AND_ARC = "tickWithBoathookAndArc",
    BARB_AND_BOATHOOK = "barbAndBoathook",
    BIRD_AGAINST_ARC_AND_SCROLL = "birdAgainstArcAndScroll",
    WING_AGAINST_ARC_AND_SCROLL = "wingAgainstArcAndScroll",
    ARC_AND_SCROLL = "arcAndScroll",
    WING_WITH_ARC_AND_SCROLL = "wingWithArcAndScroll",
    BOATHOOK_AND_BARB = "boathookAndBarb",
    WING_AND_TICK_AGAINST_DOUBLE_LEFT_BARB = "wingAndTickAgainstDoubleLeftBarb",
    TICK_AGAINST_DOUBLE_LEFT_BARB = "tickAgainstDoubleLeftBarb",
    WING_FROM_TICK_AGAINST_DOUBLE_LEFT_BARB = "wingFromTickAgainstDoubleLeftBarb",
    BIRD_AGAINST_DOUBLE_LEFT_BARB = "birdAgainstDoubleLeftBarb",
    WING_AGAINST_DOUBLE_LEFT_BARB = "wingAgainstDoubleLeftBarb",
    DOUBLE_LEFT_BARB = "doubleLeftBarb",
    WING_WITH_DOUBLE_LEFT_BARB = "wingWithDoubleLeftBarb",
    BIRD_WITH_DOUBLE_LEFT_BARB = "birdWithDoubleLeftBarb",
    WING_FROM_TICK_WITH_DOUBLE_LEFT_BARB = "wingFromTickWithDoubleLeftBarb",
    TICK_WITH_DOUBLE_LEFT_BARB = "tickWithDoubleLeftBarb",
    BIRD_AGAINST_LEFT_SCROLL_DOUBLE_LEFT_BARB = "birdAgainstLeftScrollDoubleLeftBarb",
    WING_AGAINST_LEFT_SCROLL_DOUBLE_LEFT_BARB = "wingAgainstLeftScrollDoubleLeftBarb",
    LEFT_SCROLL_DOUBLE_LEFT_BARB = "leftScrollDoubleLeftBarb",
    WING_WITH_LEFT_SCROLL_DOUBLE_LEFT_BARB = "wingWithLeftScrollDoubleLeftBarb",
    BIRD_WITH_LEFT_SCROLL_DOUBLE_LEFT_BARB = "birdWithLeftScrollDoubleLeftBarb",
    BIRD_AGAINST_BARB_AND_ARC = "birdAgainstBarbAndArc",
    WING_AGAINST_BARB_AND_ARC = "wingAgainstBarbAndArc",
    BARB_AND_ARC = "barbAndArc",
    WING_WITH_BARB_AND_ARC = "wingWithBarbAndArc",
    ARC_AND_BOATHOOK = "arcAndBoathook",
    WING_FROM_TICK_WITH_BARB_AND_ARC = "wingFromTickWithBarbAndArc",
    TICK_WITH_BARB_AND_ARC = "tickWithBarbAndArc",
    WING_AND_TICK_WITH_BARB_AND_ARC = "wingAndTickWithBarbAndArc",
    TICK_AGAINST_DOUBLE_BARB = "tickAgainstDoubleBarb",
    WING_FROM_TICK_AGAINST_DOUBLE_BARB = "wingFromTickAgainstDoubleBarb",
    BIRD_AGAINST_DOUBLE_BARB = "birdAgainstDoubleBarb",
    WING_AGAINST_DOUBLE_BARB = "wingAgainstDoubleBarb",
    DOUBLE_BARB = "doubleBarb",
    WING_WITH_DOUBLE_BARB = "wingWithDoubleBarb",
    WING_AGAINST_LEFT_ARC_AND_BARB = "wingAgainstLeftArcAndBarb",
    LEFT_ARC_AND_BARB = "leftArcAndBarb",
    WING_WITH_LEFT_ARC_AND_BARB = "wingWithLeftArcAndBarb",
    TICK_WITH_DOUBLE_BARB = "tickWithDoubleBarb",
    WING_AND_TICK_WITH_DOUBLE_BARB = "wingAndTickWithDoubleBarb",
    WING_AGAINST_LEFT_SCROLL_AND_DOUBLE_BARB = "wingAgainstLeftScrollAndDoubleBarb",
    LEFT_SCROLL_AND_DOUBLE_BARB = "leftScrollAndDoubleBarb",
    WING_WITH_LEFT_SCROLL_AND_DOUBLE_BARB = "wingWithLeftScrollAndDoubleBarb",
    BIRD_WITH_LEFT_SCROLL_AND_DOUBLE_BARB = "birdWithLeftScrollAndDoubleBarb",
    WING_AND_TICK_AGAINST_DOUBLE_ARC = "wingAndTickAgainstDoubleArc",
    TICK_AGAINST_DOUBLE_ARC = "tickAgainstDoubleArc",
    WING_AGAINST_RIGHT_BARB_AND_ARC = "wingAgainstRightBarbAndArc",
    RIGHT_BARB_AND_ARC = "rightBarbAndArc",
    WING_WITH_RIGHT_BARB_AND_ARC = "wingWithRightBarbAndArc",
    WING_AGAINST_DOUBLE_ARC = "wingAgainstDoubleArc",
    DOUBLE_ARC = "doubleArc",
    WING_WITH_DOUBLE_ARC = "wingWithDoubleArc",
    BIRD_WITH_DOUBLE_ARC = "birdWithDoubleArc",
    WING_FROM_TICK_WITH_DOUBLE_ARC = "wingFromTickWithDoubleArc",
    TICK_WITH_DOUBLE_ARC = "tickWithDoubleArc",
    WING_AND_TICK_AGAINST_ARC_AND_BARB = "wingAndTickAgainstArcAndBarb",
    TICK_AGAINST_ARC_AND_BARB = "tickAgainstArcAndBarb",
    WING_FROM_TICK_AGAINST_ARC_AND_BARB = "wingFromTickAgainstArcAndBarb",
    DOUBLE_RIGHT_BARB = "doubleRightBarb",
    WING_AGAINST_ARC_AND_BARB = "wingAgainstArcAndBarb",
    ARC_AND_BARB = "arcAndBarb",
    WING_WITH_ARC_AND_BARB = "wingWithArcAndBarb",
    BIRD_WITH_ARC_AND_BARB = "birdWithArcAndBarb",
    BIRD_AGAINST_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "birdAgainstLeftScrollDoubleRightBarb",
    WING_AGAINST_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "wingAgainstLeftScrollDoubleRightBarb",
    LEFT_SCROLL_DOUBLE_RIGHT_BARB = "leftScrollDoubleRightBarb",
    WING_WITH_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "wingWithLeftScrollDoubleRightBarb",
    BIRD_WITH_LEFT_SCROLL_DOUBLE_RIGHT_BARB = "birdWithLeftScrollDoubleRightBarb",
}

// Flag and Accent Combination; basically a "symbol class" (see: http://forum.sagittal.org/viewtopic.php?p=2474#p2474)
interface Flacco {
    arm?: Arm,
    core?: Head,
}

enum FlaccoSubset {
    COMPATIBLE = "compatible",
    SPARTAN = "spartan",
    ATHENIAN = "athenian",
    PROMETHEAN = "promethean",
    HERCULEAN = "herculean",
    OLYMPIAN = "olympian",
    MAGRATHEAN = "magrathean",
    TROJAN = "trojan",
}

export {
    FlaccoSubset,
    Flacco,
    Flag,
    Accent,
    Head,
    HeadId,
    Arm,
    ArmId,
    Orientation,
    OrientedAccent,
    FlaccoId,
}
